### ISSUE TITLE
CovPassCheck camera very slow on some phones

### ISSUE THREAD

**Issue by treysis** [Digitaler-Impfnachweis/covpass-android#102]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Ulefone S1
- OS version: Android 8
- App version: 1.12.0 (probably earlier versions affected as well)

## Describe the bug

The app has very bad performance on some lesser equipped phones. Specificslly Ulefone S1. The default camera app on the phone works smoothly, but the scanner of the CovPassCheck-app has huge lag with only 1-2 frames per second. The Austrian GreenCheck app works smooth as well.

## Steps to reproduce the issue

Try scanning certificates on smartphones with low-spec hardware.

## Expected behaviour

Camera should work smoothly without stuttering/lagging.

## Additional context

The fork on f-droid (based on an older version of CovPassCheck) works flawless.

**Comment by treysis** [comment]
The fork on f-droid works flawless.

**Comment by alexcimander** [comment]
Thank you treysis for your feedback! 
Looks like there is still room for improvement when it comes to the scanning-behavior. Let's see what we can do here. We have some improvements ready for release 1.13 - maybe they will help out. However, we will investigate on that!

**Comment by s09bQ5** [comment]
Just a guess, but maybe the app uses a much higher camera resolution since it was switched from ZXing to BoofCV?

**Comment by treysis** [comment]
@09bQ5 That could very well be the case. The f-droid version doesn't yet use BoofCV. Maybe it's not the resolution, but the general performance of BoofCV? On the other hand, Switzerland's Covid Certificate Check doesn't seem to use BoofCV but just ZXing, and it's also slow (the Austrian GreenCheck app however works fine).

Maybe it's within the crypto package? I don't know how I could test it. Maybe try with the last version before BoofCV was introducted? Which one is it and where would I get it?

**Comment by elschman** [comment]
even 1.13 from google playstore contains this bug .. please reopen

**Comment by memartinb** [comment]
Hm, interesting. Experiencing camera stutter on Galaxy S5 mini (G800F) with LineageOS 16 / Android 9, Corona Tracing App works fine. Tested today with v1.27.0. Possibly related to #114?

**Comment by pucherd** [comment]
Hello @treysis, @memartinb, are you still experiencing this issue in version 1.30.0? We did some minor improvements in this version.

**Comment by treysis** [comment]
@pucherd I don't have the device anymore so I cannot test.

**Comment by memartinb** [comment]
Yes, still a problem on v1.31.1, tested today (latest on F-Droid).

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
