### ISSUE TITLE
Only show QR-Code and remove personal information in App

### ISSUE THREAD

**Issue by SecJoe** [Digitaler-Impfnachweis/covpass-android#104]
## Current Implementation
This is not a technical problem, but we can solve this problem technical. In my homeland 90% of all restaurants, bars, clubs, events are using the CovPass app incorrect (in a way that a unvaccinated can come in). The customer shows his CovPass App tot he employee and he checks only the personal data on the app with his ID-card. But nobody scans the QR Code with the CovPassCheck App. We all know an Android dev can build in 1 hour (with help of reverse engineering) a app which is a duplicate of this one (precisely the Activity with the qr code is enough). So an unvaccinated person can check in with this fake app nearly everywhere. 
To check the real vaccination status, you have to scan the code with the CovPassCheck App.

## Suggested Enhancement
First Option (soft way): Show a Popup in the CovPass which explains, that its not enough to watch on the customers app to check the vaccination status. Explain, that the QR Code, which contains a digital signature which can only issue the government (expressed in a simple way), it the only way to check the state.

Second Option (hard way): Remove the personal data on the CovPass App, so the employees have to scan the QR-Code to see name, day of birth etc.

## Expected Benefits
The CovPass app is used correctly. Unvaccinated can not enter a mass event, bar, restaurant....

**Comment by Ein-Tim** [comment]
I would prefer the first option, as the second would practically render the app useless for normal users & make it impossible to manage more than one certificate in the app.

**Comment by timokoenig** [comment]
The first option has already been implemented in the last version. There is a popup that explains the use of CovPassCheck, a remark below the QR code and on the detail view of a certificate.

**Comment by BenKing87** [comment]
@Ein-Tim wouldn´t it be a possible solution to allow some kind of "free naming" but just names without spaces so that one can give names for wife/husband/child1/child2 etc. Those could be shown on upper right corner but would not allow an identification.

**Comment by Ein-Tim** [comment]
@SecJoe I guess not many users would actually do this. Also this does not solve a problem as even if the QR code is scanned with CovPassCheck most people checking don't want to see an ID...

**Comment by SecJoe** [comment]
> @SecJoe I guess not many users would actually do this. Also this does not solve a problem as even if the QR code is scanned with CovPassCheck most people checking don't want to see an ID...

From my experience they want to see the ID very often. If they do not check the ID, they know that they doing its wrong. We can not protect them against willful misuse. But:

The big problem is, that most people are not familiar with the technical aspects behind a QR-Code and signatures. That i have to use another handy to see if the QR code is correct and check that information with the id, despite the customers app already reports everything as correct and also shows the information is for normal users not intuitive. In contrast that they have to compare it with the ID is intuitive.

So we can at least fix that unintuitive misuse case. Proposal: Lets adjust the idea from @BenKing87 a little bit: Let not the user choose a name. Let the app only show the first name and the first (or first few) letters of the last name. That bypasses the first and second concerns from @Ein-Tim : The app is still usable in the more-certificate context and nobody has the choose a name (maybe we can use it as an optional feature).

As a consequence for everybody its intuitive that the QR code has to be scanned to see all the information which is needed the check the ID.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
