### ISSUE TITLE
Active certificate switched before it is valid

### ISSUE THREAD

**Issue by KinNeko-De** [Digitaler-Impfnachweis/covpass-android#106]
## Avoid duplicates
* [ x ] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [ x ] Bug is not already reported in another issue

## Technical details

- Device name: A52S 5G
- OS version: Android
- App version: 1.12.0

## Describe the bug

I had a booster on 03.11.2021 09:19. I got the exact time from the end date for the certificate
On 18.11.2021 (after 14 days at 00:01) the active certificate in the covpass app switched to the booster certificate.
When I check in the covpass app on 18.11.2021 00:28 if the certificate is valid for germany, the validation says : not valid!
When I check on 18.11.2021 if the certificate is valid for 19:11:2021 it says valid!
CovPassCheck also says on 18.11.2021 00:33: Certificate not valid!

I guess : everyone considers time, except the code that selects the active certificate

## Steps to reproduce the issue

I think this bug is easy to reproduce with a unit test.
I do not know how to generate test certificates.

## Expected behavior

After the active certificate is switched, it must be considered valid from CovPassCheck.

## Possible Fix

I think the easiest way to fix this is that the active certificate also considers the time and switch on18.11.2021 09:19 (or 9:20) (Consider a boundary test)

## Workaround
Manually select the old certificate and show the QR Code

## Additional context

I can not change the country because of another bug. So I can only provide details for germany.

**Comment by KinNeko-De** [comment]
Maybe it is a UTC Timestamp problem. so UTC Timestamp is 17.11.2021
I saw some UTC based code.
I will updated this in 9 minutes :)

**Comment by KinNeko-De** [comment]
When I check on 18.11.2021 01:01 if the certificate is valid for germany, the validation says : valid!
CovPassCheck also says on 18.11.2021 01:01: Certificate valid!

So i would like to change my guess that the code for selecting the active certificate uses local time and the rest uses UTC time.

## Possible fix
Consider using UTC on selecting the active certificate.
It will be also the best for flights.

**Comment by Ein-Tim** [comment]
FYI, you might find this interesting: https://github.com/corona-warn-app/cwa-app-android/issues/3990#issuecomment-907110796
Cc @vaubeahn

**Comment by KinNeko-De** [comment]
Thank you for pointing me to that issue.
But I do not agree with the issue :) I am a developer and use only UTC too  When you work with containers you do not even have "german local time".

To clarify this. I do not want that someone uses local german time. I suggest only using UTC timestamp on calculating with the certificate should be shown. This is still a minor change and also supports scenarios where you travel.

## Expected behavior:
The active certificate switched at 18.11.2021 01:00 (local german time)/18.11.2021 00.00 to the booster certificate.

**Comment by vaubaehn** [comment]
@KinNeko-De 
> I am a developer and use only UTC too

Hi, I'm @vaubaehn , I am a user and use German local time most of the time.

> To clarify this. I do not want that someone uses local german time. I suggest only using UTC timestamp on calculating which certificate should be shown. This is still a minor change and also supports scenarios where you travel.

@Ein-Tim referenced another issue for you, and I think you missed one important point:
Many (most?) EU DCCs do neither contain any time zone information nor are the dates stored inside the DCCs UTC time for the day of vaccination. This makes it impossible to associate the "right" time zone for validation. In theses cases, the validation engine for the business rules CertLogic assumes UTC time as the "kleinsten gemeinsamen Nenner" to be able to validate at all.

The only counter measures that could be taken to align in-app assignment of "day the vaccination is valid" and business rule validation of "day of valid vaccination" are explained in the comment that @Ein-Tim referenced. Unfortunately they're rather hard to achieve as this would need changes for many (most?) DCC issuing parties and still doesn't cover already issued DCCs.

> Expected behavior:
> The active certificate switched at 18.11.2021 01:00 (local german time)/18.11.2021 00.00 (UTC) to the booster certificate.

Then we will again(!) see many user reports here, that "there is a bug" because the certificate becomes valid too late, like "I needed to wait one hour longer before I could enter the club because my certificate was not valid!". Users often do not understand underlying concepts like UTC time, so for them it's just bad UX. And I know that, because i'm a user.

**Comment by vaubaehn** [comment]
@Thiefmaster

Picking up your comment from here (https://github.com/Digitaler-Impfnachweis/covpass-android/issues/94#issuecomment-972825223):
> > Then the number 2/2 must be noted in the certificate. In this case, the app cannot recognize whether it is the second vaccination of the basic immunization or a booster vaccination. Therefore a two-week waiting period is indicated. In this case, please show your old certificate with the number 1/1. This is still valid."
> 
> Maybe the app should then prefer that certificate and not require the user? Because if I was a non-techie user I would certainly not expect that I need to keep using an old certificate for 2 weeks...

I think as long as boosters are not required to enter a venue, this would be a good solution. But at the moment that boosters become mandatory then this algorithm wouldn't work also. And that could change fast - iirc, some weeks ago France thought about making boosters mandatory, but don't know whether they actually introduced it into in their legislation.
 
> Of course the ideal solution would be to have a way to indicate a booster in the certificate's data which would then not require the 2 week wait period...

I agree, but I suppose that won't happen, unfortunately. Some months ago I discussed a somewhat related topic with one of the central persons in the development of the EU DCC, and her reply was rather interesting but a bit discouraging, see
https://github.com/ehn-dcc-development/ehn-dcc-schema/issues/110#issuecomment-907308313 and following.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
