### ISSUE TITLE
Google Play app icons

### ISSUE THREAD

**Issue by G00fY2** [Digitaler-Impfnachweis/covpass-android#108]
This "bug" is only about the Play Store appearance. In #43 I fixed the app launcher icon behaviour and by doing so also updated the **ic_launcher-playstore.png** files (these got automatically generated by the Android Studio Image Asset Studio).

The current Store icons doesn't seem to match the [Google Play icon design specifications](https://developer.android.com/distribute/google-play/resources/icon-design-specifications#attributes) and should therefore be replaced with the newly generated ones from this repo.

Here is a screenshot that shows the visual issue with the current icon:
![Screenshot_20211119-132435](https://user-images.githubusercontent.com/1990806/142624547-44afbe7f-aa12-4f27-b389-da8e4947f21c.png)

Here are the new assets that match the design specifications and should be used in the Store:

> After the asset is uploaded, Google Play dynamically applies the rounded mask and shadow to ensure consistency across all app/game icons.

![ic_launcher-playstore](https://raw.githubusercontent.com/Digitaler-Impfnachweis/covpass-android/main/common-app-covpass/src/main/ic_launcher-playstore.png)
https://github.com/Digitaler-Impfnachweis/covpass-android/blob/main/common-app-covpass/src/main/ic_launcher-playstore.png

![ic_launcher-playstore](https://raw.githubusercontent.com/Digitaler-Impfnachweis/covpass-android/main/common-app-covpass-check/src/main/ic_launcher-playstore.png)
https://github.com/Digitaler-Impfnachweis/covpass-android/blob/main/common-app-covpass-check/src/main/ic_launcher-playstore.png

**Comment by pucherd** [comment]
Hi @G00fY2, thank you for pointing out this issue.
@alexcimander can you please update the Google Play Store icons?

**Comment by alexcimander** [comment]
Thank you @G00fY2! We will include a new logo with the next update of the app :-)

**Comment by G00fY2** [comment]
@alexcimander there is still the old icon in the Play Store btw. So this "issue" is still open.

**Comment by G00fY2** [comment]
@pucherd @alexcimander this issue is still not fixed inside the Google Play Store profile.

**Comment by alexcimander** [comment]
Hey everyone,

should be fixed with 1.32 - sorry for the delay!

**Comment by G00fY2** [comment]
Can confirm that this was fixed in the Play Store developer page.
