### ISSUE TITLE
CovPassCheck is incredible slow

### ISSUE THREAD

**Issue by elschman** [Digitaler-Impfnachweis/covpass-android#109]
## Avoid duplicates
* [x ] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [ x] Question has not already been asked in another issue

## Your Question
CovpassCheck seems to be incredible slow with the camera.
I run Android 9 on a Samsung 5 mini but all other pass like camera and threema cam and all the qrcode scanners are quick as they should be. Is thatsomething I can improve...

**Comment by Ein-Tim** [comment]
HI @elschman 

Your issue seems to be a duplicate of #102, or?

Thank you anyways for rising it!

Have a nice evening.

**Comment by elschman** [comment]
yes your right ! sorry for the duplicate
