### ISSUE TITLE
Valid after 14 days or after 15 days?

### ISSUE THREAD

**Issue by HeikoTheissen** [Digitaler-Impfnachweis/covpass-android#11]
https://github.com/Digitaler-Impfnachweis/covpass-android/blob/0801f33bd9dec0b0ec8734488870f61dab4fc065/covpass-sdk/src/main/java/de/rki/covpass/sdk/utils/LocalDateUtils.kt#L33
The combination of `plusDays(14)` and `isBefore()` means that the vaccination certificate is effectively accepted only after 15 days (instead of after 14 days, as it should be).

**Comment by Ein-Tim** [comment]
Take a look at https://digitaler-impfnachweis-app.de/faq/ from the Robert Koch-Institut:

"**Warum ist der QR-Code als Nachweis für den vollständigen Impfschutz erst nach 14 Tagen gültig?**

"Der volle Corona-Impfschutz ist erst 14 Tage nach der letzten erforderlichen Impfung erreicht. Der QR-Code als Nachweis für den kompletten Impfschutz ist daher erst ab Tag 15 nach der vollständigen Corona-Impfung gültig."

So after 15 days is correct.

**Comment by Ein-Tim** [comment]
Related to: https://github.com/corona-warn-app/cwa-documentation/issues/638

In this issue you can also find some more informations.
