### ISSUE TITLE
App shows wrong validity periods

### ISSUE THREAD

**Issue by kroerig** [Digitaler-Impfnachweis/covpass-android#112]
- App version: 1.12.0

## Describe the bug

When scanning an outdated QR code the app reports the wrong validity periods. 48h for Schnelltest, 72h for PCR Test.

## Steps to reproduce the issue

Scan an outdated QR code.

## Expected behaviour
Show correct validity periods: 24h for Schnelltest, 48h for PCR Test.

**Comment by timokoenig** [comment]
The EU rules for Germany are still 48 hours (rapid) and 72 hours (pcr), therefore the validity period is right. Currently it is not possible to check EU and local rules at the same time.

As a feature request I would suggest a possibility to switch between local and EU rules within the CovPass Check. @alexcimander @JilAuraya what is your opinion on this topic?

**Comment by alexcimander** [comment]
Hi Kroerig, Hi Timo,

good catch! - Yes, currently we are facing different values between the current digital EU-Rules and the "local" rules. A possible adjustment is in discussion. A switch of the rule-sets would be one way to adapt to a more dynamic environment and should be brought into the discussion. 

Thank you for the feedback!

**Comment by vaubaehn** [comment]
@alexcimander @timokoenig 
I strongly vote for a rule pre-set/profile enhancement.
I didn't try it myself yet, but did you have a look to the official Austrian check-app? I read it's supporting rule pre-sets.
If you will be able to implement it in the way of CertLogic business/booster-notification rules, would be possibly easy and likely won't need much adapting to the app itself.
Please have a look to https://github.com/Digitaler-Impfnachweis/covpass-android/issues/107 , I placed a link to the CWA Android repo there, where you can find the code on how to integrate more than one stored certificate (e.g., recovery plus booster DCC) for validating with CertLogic. This would also work with 2G+ when users have their test stored as DCC.

**Comment by JilAuraya** [comment]
In addition, we check against the travel rules and what it needs to enter Germany. 

> How recent must the test be?
The test result must pertain to a test taken no earlier than 48 hours (for antigen tests) or 72 hours (for PCR tests) beforehand. Relevant when calculating these time frames is the time of entry into Germany. When entering from areas of variants of concern, this time frame is reduced to 24 hours with antigen tests.
https://www.bundesgesundheitsministerium.de/en/coronavirus/infos-reisende/faq-tests-einreisende.html

The display time of the validity in the app is only for information, ultimately the duty of the control authority is to check the date and time of the test and thus evaluate the validity.

**Comment by jleufgen** [comment]
@kroerig could we close this tickt? Do you have any other questions about this topic?
