### ISSUE TITLE
CovPass Check on Android: QR Codes with certain features are not recognized at all

### ISSUE THREAD

**Issue by natori-umi** [Digitaler-Impfnachweis/covpass-android#113]
## Avoid duplicates
* [ x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x ] Bug is not already reported in another issue
I have not been able to find this bug reported elsewhere. Please let me know if I am wrong.

## Technical details

- Device name: Xiaomi Mi Note 10 Lite
- OS version: Android 11 RKQ1.200826.002, MIUI Global 12.5.4 stable
- App version: 1.12.0

## Steps to reproduce the issue

Some vaccine certificates I have tried to check have a square missing in the *upper* right corner or the QR code instead of the lower right corner in upward position. These certificates are not recognized as anything by CovPass Check on my phone. They are also not recognized if I flip the QR code.

The iOS application apparently recognizes the codes, as has been reported to me by a second person I asked to double-check. I have also checked the certificates above with the Luxemburgian checking app "CovidCheck.lu", which recognized all of them with no issue. 

## Expected behaviour

I expected the codes to be recognized.

## Possible Fix

Are there any differences between iOS and Android that lead to this problem? Or is there an issue with specific phone manufacturers / GUIs?

**Comment by pucherd** [comment]
Hi @natori-umi, can you please try to reproduce this behaviour with our latest Android version 1.13.2?

**Comment by jleufgen** [comment]
closed due to inactive
