### ISSUE TITLE
QR code of test certificate invalid in CovPass check app (both Android and ios) but valid in CWA

### ISSUE THREAD

**Issue by ugroempi** [Digitaler-Impfnachweis/covpass-android#118]
## Avoid duplicates
* [x ] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x ] Bug is not already reported in another issue, but related to #59

## Technical details

- Device name: Samsung Note 10
- OS version: Android 11
- App version: 1.13.2

## Describe the bug
I have a test certificate that is imported as valid by the corona warn app without problems, but is claimed to be invalid in CovPass check, both by Android 11 (Samsung phone) and ios 15. The error message looks exactly the same like in the closed issue #59 (but also occurs on ios). The printed QR code is relatively small but works without problems using a QR code scanner (clicking on the link then downloads the pdf). 

## Steps to reproduce the issue
Get tested at "Corona Testzentrum Schmargendorf (Breite Str. 24)"
Print pdf of test certificate.
Scan QR code with CovPass check app.
The result is exactly the screenshot shown in #59.

## Expected behaviour
app shows test result with date and time and identity information

## Possible Fix
Could this be due to the issuing body not being registered in all necessary places? However, the test certificate is imported as valid by the corona warn app, don't CWA and CovPass check use the same list (both are current on my phone)?

**Comment by Ein-Tim** [comment]
@ugroempi 

CWA is NOT checking the validity of your certificates. Thus, solely being able to import the certificate in the CWA is NOT a proof that the certificate is valid. How old is the test?

**Comment by ugroempi** [comment]
About 11 hours.
I am in e-mail contact with the issuing body, and they say that the QR code is not meant for third parties to check, and that they don't know how to produce one for third party checking.

**Comment by Ein-Tim** [comment]
@ugroempi Probably you are scanning a test result QR code for the CWA and not an EU digital COVID test certificate, or?

**Comment by ugroempi** [comment]
Yes, it shows up under the "status" in CWA.

**Comment by Ein-Tim** [comment]
@ugroempi 

Okay yeah this is a test result but not an EU digital COVID test certificate, which CovPassCheck can verify. So this is not an issue with CovPassCheck.

**Comment by ugroempi** [comment]
So, can CovPassCheck generally not verify test results? Issue #59 is also about a test certificate, and I thought the ability of checking test certificates was implemented some time ago?

**Comment by Ein-Tim** [comment]
@ugroempi 


CovPassCheck can verify EU digital COVID certificates (Certificate of Recovery, Vaccination or Test). But what you are trying to scan is a QR-Code intended for the Corona-Warn-App so that you can get your test result via the the CWA. This is, however, NOT a EU digital COVID certificate.

**Comment by ugroempi** [comment]
Thanks! So does that mean that I usually can't digitally check someone else's test certificate if that person does not use the CWA (or perhaps the Luca app)?

**Comment by Ein-Tim** [comment]
@ugroempi 

Mh, not necessarily. You can only check tests with CovPassCheck if they have an EU digital COVID test certificate. 

There are some other services which offer digital verifiable test certificates, however, in this case, you have to use their apps / websites and not CovPassCheck.

**Comment by ugroempi** [comment]
Thanks - I find that quite unsatisfactory, but it's not CovPassCheck's fault - so I close this issue.
