### ISSUE TITLE
Why do you decide against providing the release APKs via an official, open source?

### ISSUE THREAD

**Issue by andycandy-de** [Digitaler-Impfnachweis/covpass-android#120]
This question relates to #28 

Some use cases an release APK is relevant:
- Some people don't have and don't want an google account
- Some people don't want to use commercial app stores
- Some android systems are set up to work without commercial software
- The app is not available in all countries
- Some companies have a lot of android devices. They do not rollout apps via app store. They use EMM (Enterprise Mobility Management) to deploy apps.

This app is implemented for general public and must be available for everyone without the requirement to have a google or huawei account!

Why do you decide against providing the release APKs via an official, open source? What are the reasons for this decision? Without a release APK the use cases above are gratuitous complicated.

**Comment by axtimwalde** [comment]
I strongly support this issue.  The purpose of this app is to enable access to facilities and events for people living in or visiting Gemany and/ or the EU, not to those with a Google account (or Huawei or Apple but this is another story). The decision to not distribute it through open channels is inconsistent with the honorable approach taken to develop it as Open Source and to limit the collection of private data to the minimum necessary to achieve the original purpose.  The Google app store is a commercial gate keeper that limits access to this app to those with a Google account and various other conditions (such as geographic location) and it tracks information about by whom, when, and where the app is being installed.

**Comment by olof-nord** [comment]
I very much support this issue, and would also like to understand the reasoning behind the current decision better.
This application is, with the introduction of the German 2G rules (recovered/vaccinated), effectively an essential element of any German citizens life. As such, if one cannot install this, the implications are wide-reaching.

**Comment by oliver-steinbrecher** [comment]
As already state we're not going to publish apks . The project is open source and this enables others to build the app. In addition feel free to contribute.

**Comment by andycandy-de** [comment]
Why did you close this issue? The question is still unanswered.

Developers can build the app, but a lot of people can't. Furthermore it shouldn't be a big thing to publish a realease apk. So why do you decide against? It's more complicated when everyone builds an independent APK.

**Comment by olof-nord** [comment]
Adding to the question from @andycandy-de, I would like to point out to the [open PR](https://github.com/Digitaler-Impfnachweis/covpass-android/pull/37) which publishes apk artifacts when pushing a new version.

Wit that in mind, what exactly do you mean with "In addition feel free to contribute."?
