### ISSUE TITLE
Unable to integrate SDK

### ISSUE THREAD

**Issue by uranberisha** [Digitaler-Impfnachweis/covpass-android#121]
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.ibm.health.de.rki.covpass:covpass-bom:1.241.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/ibm/health/de/rki/covpass/covpass-bom/1.241.0/covpass-bom-1.241.0.pom
       - https://repo.maven.apache.org/maven2/com/ibm/health/de/rki/covpass/covpass-bom/1.241.0/covpass-bom-1.241.0.pom
       - https://jcenter.bintray.com/com/ibm/health/de/rki/covpass/covpass-bom/1.241.0/covpass-bom-1.241.0.pom
     Required by:
         project :app
   > Could not find com.ibm.health.de.rki.covpass:covpass-sdk:.
     Required by:
         project :app
   > Could not find org.conscrypt:conscrypt-android:.
     Required by:
         project :app
   > Could not find org.bouncycastle:bcprov-jdk15to18:.
     Required by:
         project :app
   > Could not find org.bouncycastle:bcpkix-jdk15to18:.
     Required by:
         project :app

**Comment by wkornewald** [comment]
Please see our README and #86 for how to integrate it. You're most likely missing the maven repo in your build.gradle.

**Comment by andycandy-de** [comment]
Is there a reason why the SDK is not available via maven central? Or are you incapable to integrate it to the release pipeline? Again you force the community to use a account of a commercial platform. I don't understand this.

**Comment by wkornewald** [comment]
@andycandy-de This is not a technical difficulty, but a matter of prioritizing time investments and giving people access rights and coordinating the process across several parties. The current solution is the quick fix to at least get the packages accessible at all. I think on the long run we'll have a better solution, but I can't provide any promises or time estimates.

**Comment by wkornewald** [comment]
Also, some of our dependencies are also only published via GitHub Packages.
