### ISSUE TITLE
Long app startup time

### ISSUE THREAD

**Issue by fm-sys** [Digitaler-Impfnachweis/covpass-android#122]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Huawei mate 20 lite 
- OS version: Android 10
- App version: 1.13.2

## Describe the bug

Since a few versions, I'm experiencing very long app startup times, around ~3-5 seconds. This is way too long if you often need to quickly present your QR code. Why does it take that long to render a simple QR code? I don't have such problems with other apps... 

## Possible Fix

Haven't looked into the code yet... But probably we should light up the `onCreate` method

**Comment by jleufgen** [comment]
@fm-sys thanks for the hint! We have to look at the issue more closely and then get back to you.

**Comment by G00fY2** [comment]
Another way for optimizing startup and general app performance would be enableding R8 optimization. Currently only the apps are build with the `dontoptimize` option: https://github.com/Digitaler-Impfnachweis/covpass-android/blob/41f79b787d87c14f628da8a6eb863afc00a0e1e5/gradle/common/android-app.gradle#L64

The CWA and all professional apps that I worked on so far used the **proguard-android-optimize.txt** rules. This could also improve startup times.

**Comment by wkornewald** [comment]
As the comment above that line states we ran into issues with optimizations turned on (in other projects), so we wanted to be more conservative. But that was some time ago and under special circumstances, so maybe we can try it here. Though, I highly doubt that the effect will be noticeable in this app. The issue must be somewhere else.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
