### ISSUE TITLE
[CovPassCheck] larger font

### ISSUE THREAD

**Issue by lnussel** [Digitaler-Impfnachweis/covpass-android#123]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Suggested Enhancement
I just explained how to use the covpass check app to an older restaurant owner. She had issues reading the small font of the name and birth date. Maybe the font size could be increased.

## Expected Benefits
Easier to use for older people

**Comment by pucherd** [comment]
Hello @lnussel, 
Have you tried to set the Font size in phone settings? 
It should be in Settings -> Display -> Font size and style. The App will use the font size you choose.
Please let me know if it works.

**Comment by pucherd** [comment]
Hello @lnussel, have you had a chance to try it with Font size in phone settings?
Can we close this ticket?

**Comment by pucherd** [comment]
Closing the enhancement ticket as both apps supports font resizing which is available in Android Phone Settings as described above.
