### ISSUE TITLE
CovPass shows vaccinations with "Spikevax" as "COVID-19 Vaccine Moderna"

### ISSUE THREAD

**Issue by jkrwdf** [Digitaler-Impfnachweis/covpass-android#124]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
When displaying the details of a vaccination with "Spikevax" (Moderna), the field "Vaccine" is shown as "COVID-19 Vaccine Moderna". 

![image](https://user-images.githubusercontent.com/5329491/144421159-66e7753a-ace5-47be-8383-574241320d0d.png)

## Suggested Enhancement
As per [Value Sets for EU Digital COVID Certificates](https://ec.europa.eu/health/sites/default/files/ehealth/docs/digital-green-value-sets_en.pdf), the display name is "Spikevax (previously COVID-19 Vaccine Moderna)".

![image](https://user-images.githubusercontent.com/5329491/144421514-e4e608d8-4117-4a95-9a36-c9891ac1bb12.png)

The Corona-Warn-App already uses the new display name.

## Expected Benefits
New batch labels for this vaccine might label it as "Spikevax" (similar to "Comirnaty" for BioNTech), so using the new official display name would allow better recall factor when matching the paper vaccination booklet and the digital version in CovPass.

Note: Current batch labels still use "COVID-19 Vaccine Moderna", therefore a change to "Spikevax" alone would be incorrect. The clumsy name chosen by the value-sets document giving new and old name is intentional.

**Comment by pucherd** [comment]
Hello @jkrwdf , the bug should be fixed with your latest 1.16.1 release.

**Comment by jkrwdf** [comment]
I literally got 1.16.1 it in this minute and confirm. 

Thanks. Closing.

**Comment by jkrwdf** [comment]
I got feedback from someone with an Apple device (which also got a new version named "1.16 (2)" yesterday) and there it is still the old value "COVID-19 Vaccine Moderna" (no "Spikevax to see). 

I hope this is just a delivery delay between the platforms and that no new issue in the iOS-repository is required.

**Comment by timokoenig** [comment]
@jkrwdf thanks for the hint. Just confirmed the bug in iOS
