### ISSUE TITLE
More space between text and QR Code

### ISSUE THREAD

**Issue by KaypieCode** [Digitaler-Impfnachweis/covpass-android#127]
## Current Implementation
Underneath the QR-Code on the first page, there is a text telling the user that the QR-Code can be checked by the CovPassCheckApp.

## Suggested Enhancement
In my opinion the text is placed a bit too close to the QR-Code which makes it look a little "squeezed". I would suggest adding a bit more space between those two objects. 
The problem occurs more extreme when the App is in Dark Mode as you can see on the screenshot. 

![IMG_20211203_163052~2.jpg](https://user-images.githubusercontent.com/29100375/144629713-eb7edf6f-faea-45c6-a8c2-afeb68e326c2.jpg)

![IMG_20211210_002051.jpg](https://user-images.githubusercontent.com/29100375/145491119-bdb80e17-2cf0-4195-b1de-f35508a1ed91.jpg)

**Comment by KaypieCode** [comment]
It looks like this problem occurs more intensely in dark mode.

**Comment by timokoenig** [comment]
Yes since there is still no update since November in the Google Play Store

**Comment by KaypieCode** [comment]
> @KaypieCode is the space display topic still reproducible?

Yes, when I open the app in dark mode.

**Comment by jleufgen** [comment]
@KaypieCode unfortunately, the apps do not support the dark mode function.

**Comment by KaypieCode** [comment]
Gjh

**Comment by KaypieCode** [comment]
I just realized that my system UI was the problem because it forced the app to be in dark mode.

**Comment by timokoenig** [comment]
This is not a dark mode issue even though it appears more clearly in dark mode. Lets see if this is fixed in the new version when it gets released
