### ISSUE TITLE
Information über Booster bei CovPassCheck

### ISSUE THREAD

**Issue by al-Iskandar** [Digitaler-Impfnachweis/covpass-android#128]
Mit den neuen 2G+-Regeln in manchen Bundesländern sollte bei CovPassCheck neben "vollständig geimpft", auch "geboostert" erkennbar sein.

**Comment by derOtto** [comment]
detailed Issue: Ref Digitaler-Impfnachweis/covpass-ios#73

**Comment by vaubaehn** [comment]
It is right, to handle the new access rules to venues (2G+, 2G+w/o test for the boostered) it would need different adaptations to CovPassCheck. One of them could be implementation of serial scanning of multiple certificates per user: https://github.com/Digitaler-Impfnachweis/covpass-android/issues/107

**Comment by Jo-Achim** [comment]
I don't know, I had an interesting experience today (December 10th, 2021). My booster vaccination (3/3) was on December 2nd, 2021; see below. And at an admission control I was asked for the first time whether this was my 3rd vaccination ... "because of the otherwise valid 14-day waiting period".

![Screenshot_20211210-184714_CovPass_2](https://user-images.githubusercontent.com/21124877/145619818-21377cbc-840b-4771-a514-12288aeed81e.jpg)

That this was not entirely correct because CovPass would not have displayed "Vaccination complete since December 2nd, 2021" is clear - but obviously not really well known.

The question is, could a text change be helpful here? Maybe omit the date and only show "Vaccination Certificate Complete"?

**Comment by Ein-Tim** [comment]
@Jo-Achim 
See #94

**Comment by Jo-Achim** [comment]
Thanks @Ein-Tim,

at the moment I am not entirely sure whether the "solution" fits, but we can wait and see. Because there are more important things ;-).

**Comment by Jo-Achim** [comment]
> @Jo-Achim wrote:
> That this was not entirely correct because CovPass would not have displayed "Vaccination complete since December 2nd, 2021" is clear - but obviously not really well known.
> 
> The question is, could a text change be helpful here? Maybe omit the date and only show "Vaccination Certificate Complete"?

Sorry, due to current / upcoming rule changes for boosted people - usually no additional corona test required (except for old people's and nursing homes, etc.) - a 'boost info' must be added.
Cross reference: [IMPORTANT (CovPassCheck): Add a 'Booster'-Info to the "Certificate valid"-Screen...](https://github.com/Digitaler-Impfnachweis/covpass-android/issues/139#issue-1077846503).

**Comment by alexcimander** [comment]
Hey everyone! We are working on a feasable solution so that the Covpasscheck can deal with the present and upcoming "Check-scenarios". However -please bear with us for more information. we will keep you updated about release details asap.

Thank you everyone!

**Comment by al-Iskandar** [comment]
Herzlichen Glückwunsch. Selbst die Schweizer haben das schon vor Wochen auf die Reihe bekommen: https://play.google.com/store/apps/details?id=ch.admin.bag.covidcertificate.verifier - es lebe die Effektivität der BRD

**Comment by sleeksorrow** [comment]
Die Auswertung des Booster Status dürfte ab jetzt wesentlich einfacher gehen, die Sonderbehandlung für den Impfstoff von Johnson&Johnson wurde aufgehoben. Damit gilt man durch alle Impfstoffe hindurch als geboostert, wenn das aktuellste Zertifikat 3/3 Dosen anzeigt.
Quelle: https://www.bundesgesundheitsministerium.de/service/gesetze-und-verordnungen/vo-aend-covid-19-schausnahmv-und-coronavirus-einreisev.html

**Comment by jmichler** [comment]
> Die Auswertung des Booster Status dürfte ab jetzt wesentlich einfacher gehen, die Sonderbehandlung für den Impfstoff von Johnson&Johnson wurde aufgehoben. Damit gilt man durch alle Impfstoffe hindurch als geboostert, wenn das aktuellste Zertifikat 3/3 Dosen anzeigt. Quelle: https://www.bundesgesundheitsministerium.de/service/gesetze-und-verordnungen/vo-aend-covid-19-schausnahmv-und-coronavirus-einreisev.html

Das ist m.E. irrelvant. Zum Beispiel in den meisten Restaurants gilt man auch automatisch als 2g+ wenn die zweite Impfung mit einem mRNA Impfstoff weniger als 3 Monate zurück liegt. Das Ändern der J&J Beurteilung ändert daran nichts

**Comment by Jo-Achim** [comment]
> 
> Das ist m.E. irrelvant. Zum Beispiel in den meisten Restaurants gilt man auch automatisch als 2g+ wenn die zweite Impfung mit einem mRNA Impfstoff weniger als 3 Monate zurück liegt. 

Ist das offiziell und gibt es einen Link zu dieser Regelung / Verordnung?
Is this official and is there a link to this provision / regulation?

**Comment by jmichler** [comment]
In Baden-Württemberg hier: https://www.baden-wuerttemberg.de/de/service/presse/pressemitteilung/pid/ausnahmen-von-der-testpflicht-bei-2g-plus-1/
In wieweit das "jenseits von Booster vereinheitlicht ist: Ich weiß es nicht

**Comment by sleeksorrow** [comment]
@jmichler Achtung, Missverständnisgefahr. Mein Kommentar dreht sich nur um die Identifikation des Booster Status anhand des aktuellen Zertifikats. Das war zuvor nicht möglich, weil ein mRNA 2/2 Zertifikat auch Johnson + Biontech Booster sein konnte, oder ein Biontech + Biontech ohne Booster. Dieses Problem fällt jetzt weg, 3/3 gilt immer als geboostert, 2/2 immer vollständig ohne Booster.

Was das dann für die Location und Vorschrift und Regelung bedeutet, ist ein anderes Thema, das möglicherweise zu großen Teilen der Betreiber zu beachten hat. Das beides zu vermischen macht diesen Issue mMn unnötig komplizierter.

**Comment by jmichler** [comment]
Möglich. Fakt ist: Aktuell hat der Restaurant-Betreiber mit der covpass-check app keine chance zu beurteilen, ob der Gast einen zusätzlichen Test braucht. Solange die covpass-check app nicht anzeigt: Die wievielte Impfung ist es und wann ist die Impfung erfolgt, wird er auf "meinem" Handy schauen müssen. Mit den zwei Infos prominent könnte er immerhin mit den Daten die er sieht entscheiden (müsste dann immer noch die Regeln kennen), aber heute hat er keine Chance. Bis hin zu dass ich es auf meinem Gerät ja beliebig fälschen könnte und dann den QR-Code noch anzeigen der halt schon viel älter als 3 Monate ist.

**Comment by Jo-Achim** [comment]
Na ja, zunächst wird eine Grundlage benötigt, damit CovPassCheck überhaupt in der Lage ist, eine Aussage bzgl. des aktuellen Impfstatus zu treffen bzw. anzuzeigen. 
Danach sind - dank Föderalismus - dann in den einzelnen Bundesländern die jeweilig zur Prüfung Verpflichteten in der Verantwortung, die jeweils gültigen Regeln basierend auf der Info von CovPassCheck zu beachten bzw. umzusetzen.

Well, first of all a basis is needed so that CovPassCheck is even able to make or display a statement regarding the current vaccination status.
After that - thanks to federalism - those in the individual federal states who are obliged to carry out the test are responsible for observing or implementing the applicable rules based on the information from CovPassCheck.

**Comment by Ein-Tim** [comment]
With version 1.17 which was released today, 2G+ scenarios can now be checked. However, CovPassCheck does not take boosters into account yet. This feature will be added in version 1.18.

**Comment by waldie11** [comment]
> However, CovPassCheck does not take boosters into account yet. This feature will be added in version 1.18.

Can this be advertised a little bit more, i.e. within the app during scanning for 2g+? I fear most users were awaiting a check for boostered by this update 1.17 already and whilst its lack is placed in the update description on playstore, it is hidden in the details as one only reads "Mit dem neuen Update der Check-App können ihre Zertifikate nun auch nach 2G+ Regeln geprüft...." (<- follow up hidden)

Is there a schedule for release of v1.18?

**Comment by timokoenig** [comment]
@waldie11 that would be in roughly two weeks

**Comment by timokoenig** [comment]
@niwla23 nobody says anything about showing it in CovPassCheck. The upcoming release notes just indicate the booster recognition that is done automatically and not by the person that checks the certificate

**Comment by Ein-Tim** [comment]
@al-Iskandar 

Hi, hast du mal mit Version 1.18 getestet? Die zeigt ab nun im 2G+-Modus an, wenn es sich bei dem gescannten Zertifikat um eine Auffrischimpfung handelt.

<img src="https://user-images.githubusercontent.com/67682506/154630886-0b0571ff-6cfb-46ed-afeb-f3b13bd005e9.jpeg" width="300">

**Comment by MikeMcC399** [comment]
This issue is probably obsolete. AFAIK there are no longer any German states using 2G/3G rules and no plans to reintroduce.

The nearest similar rule is for the introduction of mask rules at the discretion of states.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
