### ISSUE TITLE
Main screen with QR code ideally shows all info without scrolling down

### ISSUE THREAD

**Issue by ralxxx** [Digitaler-Impfnachweis/covpass-android#129]
## Avoid duplicates
* [X ] This enhancement request has not already been raised before

## Current Implementation
Purpose of the CovPass app is to show upon request name and QR code connected to this person. Ideally this key information is being displayed with one click (opening the app) without the need for additional manipulation (further scrolling).
As of today (depending on the screen size, the selected font size and the length of the name often this is impossible at the same time the app CovPass app screen has a lot of unused or not efficiently used space (frames, white color background).

Sample (when opening the app, the users' name is not shown at all on old 6:9 screen)
![285_ScreenshotCovPass](https://user-images.githubusercontent.com/36100882/144702863-61fc0132-2464-4e12-859e-46338917f43b.png)

## Suggested Enhancement
I am proposing that the app becomes more self-adapting to a phone and its settings in order to be capable to display the following elements without further scrolling:
- Check validity/Gültigkeit prüfen
- Title (Impfzertificat / Vollständiger Schutz)   
- Holders name
- Display certificated/Zertifikate anzeigen

## Expected Benefits
- Easier usage of the CovPass application for digital non-natives.   
- Overall easier usage

**Comment by timokoenig** [comment]
The spacing between _vaccination_ and _certificate_ is totally off 😅

On the one side it is great to see all information but on the other side it is not bad not to show everything. By showing only the QR code it gives the incentive for the other person to use the CovPass Check app

**Comment by jleufgen** [comment]
@timokoenig thanks for answering @ralxxx is the topic still relevant for you or can we close this ticket?

**Comment by timokoenig** [comment]
@jleufgen did you fix the spacing?

**Comment by jleufgen** [comment]
@timokoenig we hope that the "neutral screen" in the next release these bugs will be fixed.

**Comment by pucherd** [comment]
Hello @ralxxx,
Can you please check with the latest version 1.38?
Thank you.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
