### ISSUE TITLE
There is no way to get a valid certificate if you have been infected and thus only receive one shot

### ISSUE THREAD

**Issue by thorbenheins** [Digitaler-Impfnachweis/covpass-android#13]
As a formerly infected citizen I would like to be able to obtain a valid certificate after the first shot of Biontech (and the other non J&J vaccines), in order to be able to use the app.

Right now the validation will fail like this:

![E3_DdMxWYAAb-iR](https://user-images.githubusercontent.com/1863209/122881159-1bed4d80-d33b-11eb-91e0-d04d68805169.jpg)

**Comment by Ein-Tim** [comment]
Same as https://github.com/Digitaler-Impfnachweis/certification-apis/issues/94

**Comment by thorbenheins** [comment]
Closing in favor of Digitaler-Impfnachweis/certification-apis#94
