### ISSUE TITLE
Deep link support

### ISSUE THREAD

**Issue by cyptus** [Digitaler-Impfnachweis/covpass-android#130]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
The app does not support deep links

## Suggested Enhancement
Add support for deep links

## Expected Benefits
Business Apps do provide management portals to companies where they do their daily work.
A new task for this daily work is checking covid certificates.
To make it easy it would be a great benefit if such apps could just link to a deep link that do opens the CovPass app directly (on the scanner page?).

See also: https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/79

**Comment by alexcimander** [comment]
Hey @cyptus,

thank you for the suggestion. Looking at our current workload I cannot promise that we can prioritize this in the near future but I definetly added it to our backlog.

Thank you! 👍

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
