### ISSUE TITLE
Astra Zeneca Vaccination reminder incoherent between DE/EN

### ISSUE THREAD

**Issue by pc-coholic** [Digitaler-Impfnachweis/covpass-android#132]
https://github.com/Digitaler-Impfnachweis/covpass-android/blob/41f79b787d87c14f628da8a6eb863afc00a0e1e5/covpass-sdk/src/main/assets/covpass-sdk/eu-booster-rules.json#L195-L204

"was more than 3 months ago" vs. "vor mehr als 5 Monaten war."

**Comment by jleufgen** [comment]
@pc-coholic thanks for the hint! This is already updated in the latest version.
