### ISSUE TITLE
Why are there "Project Lombok" files in APK?

### ISSUE THREAD

**Issue by Jabb0** [Digitaler-Impfnachweis/covpass-android#133]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Question has not already been asked in another issue

## Your Question
I am not an Android dev but I stumbled upon an interesting finding. Can you please explain to me why this is happening? Thank you!

After compiling the covpass scan APK (release config) myself I noticed that inside the APK there files of "project lombok" (a java library to reduce boilerplate code - see [here](https://projectlombok.org/)).
The files on the root level of the APK include:
- Project Lombok AUTHORS
- Project Lombok changelog.txt
- Project Lombok README.md

I have checked the official PlayStore APK (1.13.2) from my device and the files are in there as well.
I have found a related question: https://stackoverflow.com/questions/37889343/android-studio-apk-analyzer-lombok-files

"lombok" is not mentioned in the whole project, especially not in the gradle files where it should be.
Likely the lombok library is not used correctly in an upstream dependency?
I also wonder why it is used in the first place and the implications of it.

Best

**Comment by G00fY2** [comment]
I can confirm this. Looks like `org.boofcv:boofcv-core` (which is not really optimized for android projects) pulls in a lot of transitive dependencies that affect the runtime classpath and therefore the final apk.

**Comment by wkornewald** [comment]
The reason for switching to BoofCV is that ZXing is not reliable enough when scanning printed QR codes and we received many complaints. ZXing is very susceptible to tiny distortions often caused by printers (e.g. one column being slightly narrower than the others). BoofCV turned out to be much more reliable and unlike ZXing it's actively maintained.

We'll have to check which files and dependencies can be stripped from the resulting APK and maybe it can even be fixed directly in BoofCV.

**Comment by oliver-steinbrecher** [comment]
@wkornewald @alexcimander let's but this on the backlog list

**Comment by alexcimander** [comment]
I added it to our backlog. Thank you everyone for participating!

**Comment by Jabb0** [comment]
Thank you everyone for having a look after my issue!

**Comment by pucherd** [comment]
Hello @Jabb0,

1.18.0 version already includes BoofCV 0.40 which removes the Lombok dependency.
