### ISSUE TITLE
CovCertificate.birthDateFormatted can be simplified

### ISSUE THREAD

**Issue by rillig** [Digitaler-Impfnachweis/covpass-android#134]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

The method `String.substringBefore` already takes care of the case when the string does not contain the delimiter.

## Current Implementation
~~~kotlin
else -> {
    if (birthDate.contains(dateTimeSeparator)) {
        birthDate.substringBefore(dateTimeSeparator)
    } else {
        birthDate
    }
}
~~~

## Suggested Enhancement
~~~kotlin
else -> birthDate.substringBefore(dateTimeSeparator)
~~~

## Expected Benefits
The code becomes lighter and unnoticeably faster.

**Comment by wkornewald** [comment]
Good catch 😄 Will be fixed in the next release. Thank you!
