### ISSUE TITLE
Booster immuization not considered after full after initial immunization with Jannsen - Johnsons 

### ISSUE THREAD

**Issue by SvenHi** [Digitaler-Impfnachweis/covpass-android#135]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy S20 Ultra 5g
- OS version: Android 11
- App version: 1.13.3

## Describe the bug

I have full immunization with Janssen vaccine (need only applied once(!))
Now I received the Booster immunization. The second certificate is not valid, because detected as 2/2.
Then it will become active in two weeks!!
This is wrong. The booster should be valid immediately!

## Steps to reproduce the issue

Just put in the booster certificate after Jannsen Basic immunization 

## Expected behaviour

The Booster should be displayed as a booster

**Comment by Ein-Tim** [comment]
This bug is known and mentioned in the FAQ: 

"**Why is the certificate for my booster vaccination invalid or not immediately valid?**"

says:

"Certificates for booster vaccinations can also be scanned in the CovPass app. After the booster vaccination, you will have an immediate vaccination protection. However, in some cases, this is not displayed in the app.

Is the booster vaccination your third vaccination? Then the number 3/3 must appear on your certificate under "Initial vaccination/re-vaccination". If this is not the case, the certificate was issued incorrectly. Please contact the issuer of the certificate to have this corrected.
Is the booster vaccination your second vaccination? Then the number 2/2 must be noted in the certificate. **In this case, the app cannot recognize whether it is the second vaccination of the basic immunization or a booster vaccination. Therefore a two-week waiting period is indicated. In this case, please show your old certificate with the number 1/1. This is still valid.**

In principle, the start screen of the CovPass app will show the currently valid certificate. If your name is spelled differently on the second certificate than on the first (e.g. by displaying a second name or changing your last name), the app will create a second "card". You can see this by swiping to the left."

**Comment by SvenHi** [comment]
"This is still valid." => This is only partly right: In BW - 2G+. You need additional test if the initial immunization is older than 6 months. => So this is definitely an issue!
If you just count certificates without checking dependencies this is wrong and bad architecture.

**Comment by SvenHi** [comment]
https://bnn.de/nachrichten/politik/corona-impfung-fehlermeldungen-booster-zertifikat-johnson-johnson-genesene-2g-plus-kontrollen-sozialministerium-bund

**Comment by Ein-Tim** [comment]
> So this is definitely an issue!

You can just explain that this is a booster, or not?

> If you just count certificates without checking dependencies this is wrong and bad architecture.

I suggest you read through https://github.com/corona-warn-app/cwa-app-android/issues/4473 to understand the problem & why this can't be fixed.

**Comment by SvenHi** [comment]
"You can just explain that this is a booster, or not?"
==> How should I explain it?
My second (Booster) immunization is not yet valid for two weeks in CovPass Check!
Classic paper is not accepted anymore in most locations.

**Comment by Ein-Tim** [comment]
> How should I explain it?

Show them your first J&J certificate and then show your second certificate & explain that this is your booster.

I know, this is not optimal, but that's the only thing possible at the moment, sorry.

**Comment by molk-ibm** [comment]
As @Ein-Tim pointed out already, there is not much we can do here([cwa-app-android/issues/4473](https://github.com/corona-warn-app/cwa-app-android/issues/4473#issuecomment-985784109)).
The root of this annoying behaviour is the rejection of the suggestion by Germany and some other member states in the EU-debate, to allow apps to detect a booster by choosing the dose order `2/1` for cases like J&J or recovery boosters.

**Comment by oliver-steinbrecher** [comment]
This topic is pressing on EU-level and in further discussion.  At the moment the specification is declared.

**Comment by DarkBlue-Night** [comment]
So - all boostered persons, with first vac JJ just have to wait and can't do anything about it?

**Comment by vaubaehn** [comment]
If there is actually a decision on EU-level to change the numbering for boosters to something like 2/1 (https://github.com/Digitaler-Impfnachweis/covpass-android/issues/135#issuecomment-991178695), it would mean that
a) at least all 1-time J&J vaccinated people who want to be recognized as boostered would have to be issued a new QR code - _on EU-level_, and
b) all wallet apps and checking apps (EU-wide) would need to be able to process two different types of numberings: 1/1, 2/1, 3/1... and 1/1, 2/2, 3/3... Otherwise _all_ boostered people would need to get new QR codes issued to be recognized as boostered - _on EU-level_, and
c) all national platform solutions for issuing QR codes (DCCs; e.g. for pharmacies, vaccination centers etc.) would need to adapt for a new numbering, and all the medical staff using the systems would need to be trained accordingly - _on EU-level_

I'm very curious what will be decided.

**Comment by oliver-steinbrecher** [comment]
To change the current state the specifications need to be updated and then all members need to adopt this. The impact is high for sure @vaubaehn. Personally I don’t understand your point - there is no change without implications

**Comment by vaubaehn** [comment]
@oliver-steinbrecher and @molk-ibm 
Wouldn't it be easier to go the same way like "GreenCheck" in Austria? (that is my point)
They recently implemented serial scanning of DCCs (released last week). For checking the DCCs, in the check app a pre-set (2G, 2G+, 3G...) can be chosen. When 2 different certificates are necessary to validate the status, GreenCheck scans the first, presents an intermediary result and scans the 2nd. In our case this would work for J&J-jabbed-mRNA-boostered people in a similar way (or for recovered, jabbed and boostered people). Only 2 extensions are necessary:
- CovPassCheck would need to implement serial scanning (what was proposed 1 month ago already in #107), and
- CovPass as well as Corona-Warn-App should enhance their UI in the way, that all necessary certificates can be accessed/displayed by a single finger tip. Corona-Warn-App will release this feature (2G check-in) soon: https://github.com/corona-warn-app/cwa-app-android/pull/4469,

**Comment by DarkBlue-Night** [comment]
The App which creates the QR-Codes already has the option "2/2 Booster" - is this correct. I was told so.

**Comment by oliver-steinbrecher** [comment]
> @oliver-steinbrecher and @molk-ibm Wouldn't it be easier to go the same way like "GreenCheck" in Austria? (that is my point) They recently implemented serial scanning of DCCs (released last week). For checking the DCCs, in the check app a pre-set (2G, 2G+, 3G...) can be chosen. When 2 different certificates are necessary to validate the status, GreenCheck scans the first, presents an intermediary result and scans the 2nd. In our case this would work for J&J-jabbed-mRNA-boostered people in a similar way (or for recovered, jabbed and boostered people). Only 2 extensions are necessary:
> 
> * CovPassCheck would need to implement serial scanning (what was proposed 1 month ago already in [[CovPassCheck] 2G+ & (recent) Boosters: Introduce optional serial scanning of multiple DCCs per user #107](https://github.com/Digitaler-Impfnachweis/covpass-android/issues/107)), and
> * CovPass as well as Corona-Warn-App should enhance their UI in the way, that all necessary certificates can be accessed/displayed by a single finger tip. Corona-Warn-App will release a basic feature (2G check-in) soon: [[Featurebranch] Check in for 2G events (EXPOSUREAPP-10632) corona-warn-app/cwa-app-android#4469](https://github.com/corona-warn-app/cwa-app-android/pull/4469),

All features cross CovPass and CWA related to DCC are aligned. The feature will be delivered as well in CovPass

**Comment by vaubaehn** [comment]
@DarkBlue-Night 
> The App which creates the QR-Codes already has the option "2/2 Booster" - is this correct. I was told so.

I'm not fully understanding your question, or which app should do what, so I'm trying to break it up a bit:
- The QR code is the representation of a EU Digital Covid Certificate (DCC), e.g., for vaccination.
- For the DCC there is a scheme, which information can be contained into the DCC - there was a resolution on EU-level about it, member countries cannot change it at will.
- In the current DCC scheme there is no possibility to store the information "booster". There is only a numbering of the series of vaccinations and an agreement on how to count and encode them (currently: 1/1, 1/2, 2/2, 3/3...)
- However, wallet apps _could_ show "2/2 Booster" as a text next to the QR code, when beside the 2/2 vacconation also the J&J 1/1 DCC is stored in the wallet app,
- and check apps could validate these 2/2 boosters, if serial scanning of DCCs was implemented and first the J&J DCC and then the 2/2 booster was scanned and evaluated.

**Comment by vaubaehn** [comment]
> All features cross CovPass and CWA related to DCC are aligned. The feature will be delivered as well in CovPass

That's nice to hear!
Do you have any plans for serial scanning in CovPassCheck?

**Comment by DarkBlue-Night** [comment]
@vaubaehn 
At the pharmacy I got my QR-Code from, they told me, that they have the option for "2/2" and the option for "2/2 Booster", when creating the QR-Code.

**Comment by vaubaehn** [comment]
@DarkBlue-Night 

> At the pharmacy I got my QR-Code from, they told me, that they have the option for "2/2" and the option for "2/2 Booster", when creating the QR-Code.

That's interesting, didn't know that! Maybe @molk-ibm has more information about that feature?

However, the information "booster" can not directly be encoded into the DCC currently, as the scheme only allows for the numbering mentioned above.

**Comment by oliver-steinbrecher** [comment]
> > All features cross CovPass and CWA related to DCC are aligned. The feature will be delivered as well in CovPass
> 
> That's nice to hear! Do you have any plans for serial scanning in CovPassCheck?

Features embracing 2G+ Situation will be shipped in Release 1.17 including both apps CovPass and CovPass Check

**Comment by oliver-steinbrecher** [comment]
> @vaubaehn
> At the pharmacy I got my QR-Code from, they told me, that they have the option for "2/2" and the option for "2/2 Booster", when creating the QR-Code.
> But they were not aware, that this is worth nothing...

Be careful with those information - we‘re aligning all DCC issuing tools . In some cases the UIs have been Design in a bad way

**Comment by DarkBlue-Night** [comment]
@oliver-steinbrecher 
And this verion 1.17 will include the JJ-Booster problem? And for people who are recovered, vaccinated and boostered? Because they face the same problem.

**Comment by Ein-Tim** [comment]
FYI: https://ec.europa.eu/commission/presscorner/detail/en/ip_21_6837 says:

"Boosters will be recorded as follows:

3/3 for a booster dose following a primary 2-dose vaccination series.
2/1 for a booster dose following a single-dose vaccination or a one dose of a 2-dose vaccine administered to a recovered person."

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
