### ISSUE TITLE
Camerawindow does not focus on QR-Code

### ISSUE THREAD

**Issue by holysh1t** [Digitaler-Impfnachweis/covpass-android#137]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy S5 (SM-G900F)
- OS version: 6.0.1
- App version: 1.13.3

## Describe the bug
The camera window does not focus.

## Steps to reproduce the issue
Install app on Android 6.0.1.
Try to scan booster certificate.
Can't scan because camera won't focus.

Tested with other QR-Code Scanners and the camera is not defect. I've worked around the issue by fotographing and then sizing the QR-Code.

![no_focus](https://user-images.githubusercontent.com/30555166/145711782-6aeb97ee-fa7e-42a7-99e7-84aadc5a6d76.jpg)

## Expected behaviour
Camera needs to focus. Either on tap or automaticly.

**Comment by Ein-Tim** [comment]
This looks very similar to #114.

**Comment by holysh1t** [comment]
It is the same issue. Sorry for the duplicate.
