### ISSUE TITLE
This code doesn't contain build instructions to self-compile the app.

### ISSUE THREAD

**Issue by tkrahn** [Digitaler-Impfnachweis/covpass-android#14]
Can you please provide at least brief instructions how to compile an APK for the demo and production version of this code so that an end-user can install the covpass-android app without using the Android Play environment.

**Comment by Gundul42** [comment]
That would be one possibilty. what about making the app available in the f-droid app store ?

**Comment by wkornewald** [comment]
@Gundul42 please avoid abusing other issues for unrelated requests. ;) We already have a issue #2 for F-Droid.

@tkrahn did you run into any specific issues that we should document? It should be possible to just build the debug version with Android Studio out of the box. Only release builds are special in that you have to add a signing key by putting a debug.keystore file into the repo root folder or alternatively build the unsigned bundle/APK and sign manually.

**Comment by iNPUTmice** [comment]
FWIW the app builds fairly straight forward just like any other Android app.

```shell
git clone https://github.com/Digitaler-Impfnachweis/covpass-android.git
cd covpass-android
export ANDROID_SDK_ROOT=/opt/android-sdk
./gradlew assemble
adb install ./app-covpass-prod/build/outputs/apk/debug/covpassprod-1.19.1-main-SNAPSHOT-debug.apk
```

(Assuming the Android SDK has been installed to `/opt/android-sdk`)

**Comment by tkrahn** [comment]
Thanks Daniel, this is helpful. At least those 5 lines should be included somewhere in the documentation, please.
Sorry, but Android Studio wasn't mentioned anywhere. I'll give it a try.
Gundul: Where do I get the debug.keystore file from, so that the app can be practically used in the real world? I guess self signing doesn't work.

**Comment by wkornewald** [comment]
@tkrahn I'd recommend using Android Studio because that works out of the box and is much easier than manually installing the latest Android SDK. The debug.keystore can be an arbitrary keystore created with keytool or Android Studio (it generates a default one in your home folder and you can just copy that). Self-signing is fine as long as your phone is configured to accept arbitrary APKs/bundles.

**Comment by Gundul42** [comment]
> Thanks Daniel, this is helpful. At least those 5 lines should be included somewhere in the documentation, please.
> Sorry, but Android Studio wasn't mentioned anywhere. I'll give it a try.
> Gundul: Where do I get the debug.keystore file from, so that the app can be practically used in the real world? I guess self signing doesn't work.

Sry for hijacking this thread I did not see the open fdroid issue. I have absolutely no experience in compiling together with android SDK. That is why I suggested adfing it there. Probably more people
would enjoy just downloading the app without having to have a google account.
But talking about compiling, I guess all what I would need to do so is available for Linux and without sharing any data with google  ?

**Comment by tkrahn** [comment]
After a few hours of guessing I managed to install the apk on my phone. Here is what I did:

Install adb
`sudo apt install android-tools-adb`

Download and install Android Studio from here:
`https://developer.android.com/studio`

As an example I've unpacked Android Studio in ~/bin/android-studio
Using the default directory ~/Android when asked.

Clone Covidpass from GitHub:
`git clone https://github.com/Digitaler-Impfnachweis/covpass-android.git`

As an example I've installed the covpass-android sources in ~/src/covpass-android/

We need to start Android Studio at least once, so that it pulls and installs the Android SDK
`cd ~/bin/android-studio/bin
./studio.sh`

Open the directory with Android Studio
File > Open... 
covpass-android

Compiling with the GUI did create an apk, but for some reason it didn't work on the phone. 
The error was INSTALL_FAILED_NO_MATCHING_ABIS meaning that it was compiled for the wrong processor architecture. 
I believe I missed some settings in the totally confusing Android Studio GUI.
I don't think that it's very useful to give build instructions with that GUI for a non-android programmer.
Therefore I tried the command line approach which worked fine:

`cd ~/src/covpass-android
export ANDROID_SDK_ROOT=~/Android/Sdk
./gradlew assemble`

Before pushing the apk to the phone, it was necessary to turn on developer settings and USB debugging on the Android phone:
Go to Settings > About phone
Tap on the Build number option for about 7-8 times.
Head back to the Settings app and you’ll find a new option saying Developer options. 
Get inside this new option and turn on the option that says USB debugging.

Now we can install the covpass apk via USB cable:
`adb install ./app-covpass-prod/build/outputs/apk/debug/covpassprod-1.19.1-main-SNAPSHOT-debug.apk`

It should return:
`Performing Streamed Install
Success`

Now the CovPass launcher icon should appear on the phone and can be started.

**Comment by martin3000** [comment]
With android studio, you can directly create a new "project from versioncontrol" and point to git clone https://github.com/Digitaler-Impfnachweis/covpass-android.git. Android studio then downloads the code from github. But the symbolic link "text-vaccination" does not work. It is also ignored by git clone.

**Comment by tkrahn** [comment]
If somebody takes his time just to copy and paste the instructions to the official documentation, then I could finally close this bug.

**Comment by wkornewald** [comment]
"text-vaccination" is not a symlink, but a git submodule and if you set `submodule.recurse = true` in your gitconfig it'll automatically get cloned/updated. However, this submodule isn't required to build the app.

What I don't quite understand yet is why just using Android Studio wasn't enough. Our dev team is doing just this:

* Open the project with Android Studio.
* At the top right select which app you want to run (e.g. app-covpass-demo).
* Click the "play" button.

There really shouldn't be any need to set ANDROID_SDK_ROOT or manual use of adb.

**Comment by tkrahn** [comment]
When I click on the "play" button, it'll launch the app in a simulator on my desktop. It's not obvious what to do to get the app installed on a phone for a lay person. If there is a way to use Android Studio to move the app to the phone, I haven't found it. So it was necessary to use adb install and configure the phone for USB debugging. I think all this should go in a build and install documentation. At least a professional programmer would do this.

That said, I can confirm that the app builds flawlessly and I was able to use it with my real vaccination certificate, including the scan option. This was all necessary because the official covpass Android app is only available in the Android Play store if your Google account is registered in Germany (or Europe?). Despite my current location is Berlin, my phone number is in Germany and the SIM card of my cellphone is from 1 & 1 Germany as well.

**Comment by wkornewald** [comment]
The device picker is between the app picker and the „play“ button. Your phone should appear when you connect it to your computer. You might need to turn on developer options on your phone though.

**Comment by tkrahn** [comment]
Thanks for the hint. Naive as I am, I never thought about plugging in the phone *before* starting the build. Therefore I've never seen my phone in the list.
I still like the command line version better, because it feels like Android Studio takes half an hour to start up and check for all possible and unnecessary updates. However if you grew up with just clicking on a screen and playing on cellphones, then I can understand that this is easier for you.
Regardless what you think is better, please write it up and add it to the instructions so that a classic "Perl on the command line coder" like me can reproduce it. It isn't that hard to write a few paragraphs and insert a few screenshots. Without a documentation a code isn't complete. Thanks.

**Comment by wkornewald** [comment]
The README now contains the recommended way to develop on Android which is the IDE. This works the same way on all operating systems and even for non-developers. So, I think we can make this issue as done.

The command line requires different instructions per operating system and is way too complicated for no real benefit. Spending 1-3 hours setting up the command line (and us writing documentation for all platforms the whole day) just to save 1 minute on Android Studio load times is not something our README should suggest at all.
