### ISSUE TITLE
License is not customized

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-android#140]
The [LICENSE](https://github.com/Digitaler-Impfnachweis/covpass-android/blob/main/LICENSE) file is not customized. It includes, e.g. [this](https://github.com/Digitaler-Impfnachweis/covpass-android/blob/41f79b787d87c14f628da8a6eb863afc00a0e1e5/LICENSE#L190) line:
>    Copyright [yyyy] [name of copyright owner]

I suggest you customize the license by adding the correct information.

**Comment by wkornewald** [comment]
This is actually correct because that text is in the `APPENDIX: How to apply the Apache License to your work.` just describes how to apply the license. Modifying that text would be a modification of the APACHE license.

**Comment by Ein-Tim** [comment]
@wkornewald 

The Appendix says:
"To apply the Apache License to your work, attach the following boilerplate notice, with the fields enclosed by brackets "[]" ** replaced with your own identifying information**. (Don't include the brackets!)  The text should be enclosed in the appropriate comment syntax for the file format. We also recommend that a file or class name and description of purpose be included on the same "printed page" as the copyright notice for easier identification within third-party archives."

So why not do it this way?

**Comment by wkornewald** [comment]
Yes it says that you should attach the note, but it means: to your README.md or your source code.

**Comment by timokoenig** [comment]
@Ein-Tim as @wkornewald already said, the appendix is for everyone that wants to use your work and not for the project license itself.

**Comment by Ein-Tim** [comment]
@wkornewald Okay then https://github.com/Digitaler-Impfnachweis/certification-apis/blob/master/LICENSE is wrong, or?

**Comment by MikeMcC399** [comment]
According to https://opensource.stackexchange.com/questions/4149/include-appendix-of-apache-2-0-in-license-file, the Appendix is not part of the license.

**Comment by MikeMcC399** [comment]
There is also an article https://www.linkedin.com/pulse/how-apply-apache-20-license-your-open-source-software-vladim%C3%ADr-gorej/ which says that the text should not be modified at all. This agrees more or less with the statement from @wkornewald in https://github.com/Digitaler-Impfnachweis/covpass-android/issues/140#issuecomment-992286799.

**Comment by wkornewald** [comment]
> @wkornewald Okay then https://github.com/Digitaler-Impfnachweis/certification-apis/blob/master/LICENSE is wrong, or?

Right, that shoud be changed. Can you please open an issue there?

**Comment by Ein-Tim** [comment]
@wkornewald

Closing here and opening a new issue.
