### ISSUE TITLE
Enable setting expiration periods in CovPassCheck

### ISSUE THREAD

**Issue by schtandard** [Digitaler-Impfnachweis/covpass-android#147]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Current Implementation and Why This Is Lacking
Currently, when scanning a certificate, the app only reports it to be "valid" (in case it is) and displays the name and birth date of the person it belongs to. It does not provide any information on the vaccination or recovery date.

Regulations are changing and already vaccinations older than six months are treated differently to those younger in many places (but not in others). This will presumably stay that way for the remaining usage time of this app. Different stages in the immunization process will likely even lead to further differentiation in the future (seven months after the third dose may be regulated differently than seven months after the second dose). A rule allowing businesses to choose between different models (e.g. choosing between "2G no older than 6 months without mask mandate" and "2G with mask mandate", in analogy to the "2G without masks" or "3G with masks" we already saw in some places) may also be in the future.

Currently the workaround is to scan the QR code and then also scroll down in the app / read on the paper the code was scanned from, as the vaccination/test date is usually displayed there. This is bad for obvious reasons.
- The print around the QR code is easily forged.
- It adds another step to the checking procedure, making it more of a hassle as well as more prone for errors.
- Since all of the relevant information is contained in the QR code, people should really be able to _just_ show the QR code. I have seen people using just a printout of their QR code, which is a bit obnoxious but should work. It currently doesn't.

## Suggested Enhancement
The easiest fix would be to just display the required information directly (e.g. "2nd dose 4 months ago", "recovered 8 months ago", etc.). I gather from #111 that this is undesired due to privacy concerns (although I would be interested if this has been reconsidered in light of the more differentiated regulations).

An alternative that avoids displaying this information directly would be a settings menu where the user of the app can define different requirements for the certificate to be accepted as "valid", e.g. "3rd dose at least one week ago or 2nd dose at least 2 weeks and at most 6 months ago or recovered at most 6 months ago". When a code is scanned, the app would just display "valid"/"meets all of your criteria" or "invalid"/"does not meed all of your criteria". (Maybe a different message than for actually invalid certificate (e.g. forged ones) would be good.)

## Expected Benefits
The practical issues outlined above would be resolved. People checking certificates could adjust the settings to the policies of their local government / organization. This would also provide more privacy to the person being checked than the current workarounds.

**Comment by andycandy-de** [comment]
> I have seen people using just a printout of their QR code, which is a bit obnoxious but should work. It currently doesn't.

Why do you think it's obnoxious? I think that's how this should work. You shouldn't need more than the QR Code.
I also have a printout of the QR Code in my mobile phone case as a backup. So the Check app should show all relevant informations. If someone is evil it's not a problem to read the data from the QR Code. So to hide the data in the App is just a ostensible protection.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
