### ISSUE TITLE
This application is not available in your country - remove country restrictions

### ISSUE THREAD

**Issue by idc77** [Digitaler-Impfnachweis/covpass-android#149]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name:
Samsung A72
- OS version:
N/A
- App version:
latest as of 17.12.2021

## Describe the bug

My mom was vaccinated today. She received a certificate on paper. I wanted to install the app on her phone to scan the QR code.
She has a Croatian SIM card, her phone's language is set to Croatia. She is here with me in Germany.
Location services are enabled.
"This article can not be installed in your country"
when I try to install the app.

I have to change the phone's language to German, reboot the phone. Only then I'm able to download and install.
Given the amount of pressure people are exposed to about being vaccinated that's unacceptable.
You can't have your phone in a different language? Why the hell not?

I'm aware this is a play store bug, but you have the power to change or remove region restrictions.

## Steps to reproduce the issue

see above

## Expected behaviour

Able to install the app with a different language selected.

## Possible Fix

Get rid of location / language restrictions

**Comment by mariozelaschi** [comment]
I can confirm the bug/feature: the solution is to publish the app as available for all Europe/World instead of just Germany.

Please note that the user's country is set by the Google account more than the phone settings (or gps): other people with an Italian simcard and Italian phone language are able to download the app because they set up the Google account in Germany with a German payment option.

I live in Germany and I need to use the app, but I have an Italian Google Account and even if I set up the phone language in German and I use a local SIMcard the app is shown as not available in my country.

**Comment by Ein-Tim** [comment]
@mariozelaschi 

As an alternative you can use the Corona-Warn-App for now (-:

**Comment by mariozelaschi** [comment]
yes, but it has the covid tracking that i prefer not to use (not for privacy issues but for battery drain)

**Comment by Ein-Tim** [comment]
@mariozelaschi 

You can use the CWA without having to activate exposure logging.

**Comment by github-tomster** [comment]
@idc77 
sit down, relax and read on:
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/28
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/120
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/141

feel free to 😭 
this is 🇩🇪 !
oh and we have to keep the tone fine and down. 💢 🗯️ 

the german upper-level federal agency driven by public taxes <- am i wrong on that ❓ 
is not able/unwilling to provide a **free-accessible apk** to the public 🤦🏻‍♂️ 
i am close to the point to think they are violating german law with this attitude 👮🏻‍♂️ 

however, check here:
https://f-droid.org/en/packages/ch.admin.bag.covidcertificate.wallet/
https://github.com/admin-ch/CovidCertificate-App-Android/releases
https://github.com/admin-ch/CovidCertificate-App-Android
maybe this helps you.
and one can see: it is possible and the only acceptable way 🥇

**Comment by Karl-WE** [comment]
The application can be used in different EU countries but not all EU countries.
Spain is missing for example.
It's not an App that's only meant for Germany.

**Comment by Ein-Tim** [comment]
@Karl-WE 

> It's not an App that's only meant for Germany.

Actually, it is, isn't it?

**Comment by Karl-WE** [comment]
@Ein-Tim to avoid a duplicate discussion
See my reply on the same topic here
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/139#issuecomment-1028924665

**Comment by Karl-WE** [comment]
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/139#issuecomment-1028937488

When the app can be downloaded but doesn't include any regional rules, why is it blocked in some countries anyway I don't see the motivation why it's not available in all EU countries. Therefore hope for a clarification from the Devs and if they would like to follow this PR.
I support this PR . My friend in Catalunya was really eager to try the covpass app but Spain is also locked for yet unclear reasons.

**Comment by Ein-Tim** [comment]
@Karl-WE 

I don't know why the app is only available in some EU countries and in others not, the Corona-Warn-App is available in all and also offers the feature to store certificates.

**Comment by memartinb** [comment]
I used to have CovPass hidden in AuroraStore (not available in my Region - degoogled LOS16 with en-GB language setting) but now it is shown to me. Maybe resolved? Also I might point out that as of today, F-Droid and Aurora both show v1.27.0 (15 Jun 2022) as the most recent update. So something seems to have improved :-)

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
