### ISSUE TITLE
Use Standardized Name as merge criterion

### ISSUE THREAD

**Issue by mrtnmueller** [Digitaler-Impfnachweis/covpass-android#151]
My surname has an umlaut (ü) and I was inoculated by different doctors. The first put the same for name and standardized name, the second did it right and put the umlaut name as my name. The standardized name is the same for both, however now I got 2 different slides in the app.

Maybe use the standardized name (together with date of birth?) as the merge criterion, not the name itself. Otherwise this will probably happen to a lot of people.

**Comment by Ein-Tim** [comment]
Same as #117.

**Comment by mrtnmueller** [comment]
yeah, sorry. I searched beforehand but did not find that issue.
