### ISSUE TITLE
Invalidated/fake certificates shown as valid

### ISSUE THREAD

**Issue by fabfre** [Digitaler-Impfnachweis/covpass-android#152]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Question has not already been asked in another issue

## Your Question

* Question:
When I build the current version of the Corona Check app (app-covpass-check-prod), vaccination certificates (production certificates) [marked as fake](https://www.spiegel.de/netzwelt/apps/corona-warn-app-markiert-gefaelschte-impfzertifikate-als-ungueltig-a-15080d16-86b0-437e-9afd-c8f5ef0add80) are shown as valid. The Google Play version recognizes these certificates as fake. The CovPass iOS SDK also detects them as fake. 
So my question: Do I need to set or run something special? I have downloaded the latest DSC List.

**Comment by wkornewald** [comment]
Did you build from the latest release branch or from main?

**Comment by treysis** [comment]
Some fraudulent certificates are still accepted although apps of other countries already invalidated them.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
