### ISSUE TITLE
Crash when opening the scanning on samsung devices

### ISSUE THREAD

**Issue by stefan-weiss** [Digitaler-Impfnachweis/covpass-android#157]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy Fold 3 (SM-F926B)
- OS version: Android 11
- App version: 1.13.3

## Describe the bug

App just crashes. I just can give the information which the OS gave me. I read in the Google Play Store that a lot of people have the same Issue and I don't find here a bug for that. They said it happens also on Samsung Galaxy Flips and Samsung S20

- Package name: de.rki.covpass.app
- Package version: 679
- Package version name: 1.13.3
- Installed by com.android.vending
- Process name de.rki.covpass.app
- Device: q2q
- Build ID: RP1A.200720.012.F926BXXS1AUJB
- Build fingerprint: samsung/q2qxeea/q2q:11/RP1A.200720.012/F926BXXS1AUJB:user/release-keys
- Model: SM-F926B
- Product: q2qxeea
- SDK version: 30
- Release: 11
- Incremental version F926BXXS1AUJB
- Codename: REL
- Board: Iahaina
- Brand: samsung
- Exception class name: java.lang.AbstractMethodError
- Source file: SamsungSidecarImpl.java
- Source class: androidx.window.sidecar.SamsungSidecarImpl
- Source method: updateDevicePosture
- Line number: 85
- Stacktrace: ```java.lang.AbstractMethodError: abstract method "void androidx.window.sidecar.Sidecarinterface$SidecarCallback.onDeviceStateChanged(androidx.window.sidecar.SidecarDeviceState)" at and roidx.window.sidecarSamsungSidecarImpl.updateDevicePosture(SamsungSide carlmpl.java:85) at androidx.window.sidecarSamsungSidecarlmpl.access$000(SamsungSidecarlmpl.java:44) at and roidx.window.sidecarSamsungSidecarlmpl$SamsungSidecarCallbackListener.onDeviceStateChanged(SamsungSidecarlmpl.java:62) at android.view.-$ $Lambda$5NelMm5rLKQbeBRvtLr6OjxYQ 74.run(Unknown Source:2) at android.os.Handler.handleCallback(Handler.java:938) at android.os.HandlerdispatchMessage(Handler.java:99) at android.os.Looperloop(Looperjava:247) at and roid.app.ActivityThread.main(ActivityThread.java:8656) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.Runtimelnit$MethodAndArgsCallerrun(Runtimelnitjava:602) at com.android.internal.os.ZygoteInit.main(ZygoteInit:1130) ```

## Steps to reproduce the issue

1. Open App
2. Click on + to add a new certificate
3. Click on QR-Code scannen 

## Expected behaviour

No crash and the camera opens for scanning.

**Comment by Ein-Tim** [comment]
Hi @stefan-weiss 👋

Thanks for reporting this bug! Did you take a look at #100? It seems like this issue is a duplicate of #100, or am I mistaken?

Thanks for your feedback.

**Comment by stefan-weiss** [comment]
Hi @Ein-Tim  

yeah you are right, should I just close this one and  mention #100 ? I#m not sure if the stacktrace is known, because I didn't saw it in the other issue.

**Comment by Ein-Tim** [comment]
@stefan-weiss

The issue is well-known, AFAIK, it's a problem on folding devices.

I think this issue can be closed, you can add your comment (with the stack trace) to #100.

**Comment by stefan-weiss** [comment]
Close Issue because of duplicate. See #100
