### ISSUE TITLE
Function 'EU-Ausdruck erstellen' does not dump correct certificate with 3 Certificates available (3rd selected).

### ISSUE THREAD

**Issue by BWolfer54** [Digitaler-Impfnachweis/covpass-android#158]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Samsung S20
- OS version: 11
- App version: 1.13.3

## Describe the bug

I have Certificates imported for 3 vaccinations (regular 1st and 2nd shot plus booster shot) for one person and try to create the 'EU-Ausdruck' for each. Works fine for 1st and 2nd. When trying for the 3rd, I get again a dump of the 1st.

## Steps to reproduce the issue

See description

## Expected behaviour

The app should always create a 'EU Ausdruck' for the selected Certificate.

**Comment by lukalt** [comment]
I tried this with Version 1.13.3 on a Samsung Galaxy A52s 5G. I was not able to reproduce this. For all three certificates, the export yields the correct PDF:

**Comment by jleufgen** [comment]
@BWolfer54 do you still have the bug?

**Comment by BWolfer54** [comment]
Hello all,
meanwhile I tried on a different device (Ipad) and could not reproduce the issue.
Now I uninstalled CovPass from the initial device (Samsung S20), re-installed it and re-imported the same certificates. Now the issue cannot be reproduced on this device any more either.

**Comment by timokoenig** [comment]
@BWolfer54 I just had a look on the implementation and the exported file always has the same name. Therefore the third certificate might got overwritten from another exported certificate. I will open a ticket to change that

**Comment by BWolfer54** [comment]
@timokoenig: I don't think that was the issue for me, but improving the naming is definitely a good idea!
