### ISSUE TITLE
Installation issues on Android

### ISSUE THREAD

**Issue by Smit-tay** [Digitaler-Impfnachweis/covpass-android#16]
I have been a Google user for longer than I can remember, and originally had my Google account in USA. I have been living in Germany for over 10 years, and never had a problem installing any other app from the play store. I was unable to install this app until I switched my Play account to Germany.  As a side note, getting that to work (changing to Germany Play Store) was also a PITA !

There appears to be some kind of a Geographic restriction on installation .
This seems to be a needless requirement.

**Comment by Ein-Tim** [comment]
Same as https://github.com/Digitaler-Impfnachweis/documentation/issues/5

You can also find some more infos there.

**Comment by jleufgen** [comment]
Hello, there are currently no plans to release the app in others Stores. Therefore, I will close the ticket.

**Comment by Smit-tay** [comment]
Great Job just ignoring the problem.
This is not about releasing it to another app Store, it is about removing the geo-restriction for the account used to download it.
There is zero reason to geo restrict the account.  If I have an account in USA, then move to Germany, I am not required to open a German account.  Every other application I have ever installed just works.  But not this one.  

Why ?
