### ISSUE TITLE
log4j in build files and APK

### ISSUE THREAD

**Issue by xtronic94** [Digitaler-Impfnachweis/covpass-android#160]
## log4j in build files and APK

* Source File: Build files and in the APK
* Line(s): -
* Question: If you search log4j in the covpass app folder you can find it in the build files and the APK. Is their a secrutiy issue with this? See Screenshot.

![image](https://user-images.githubusercontent.com/22410199/148035086-037db75b-5bd9-417d-910a-07cd924db26d.png)

**Comment by wkornewald** [comment]
This code is part of lombok which is mistakenly marked as a runtime dependency by BoofCV.

* It's not the actual log4j library, but just some annotation type that happens to have Log4j in its name: https://github.com/projectlombok/lombok/tree/master/src/core/lombok/extern/log4j
* That code is not used anywhere.
* A fix in BoofCV is ready for their next release: https://github.com/lessthanoptimal/BoofCV/issues/319

You will also find other strings with references to log4j in the APK, but again those are meaningless. In our actual runtime dependencies there is no log4j.

So, closing this ticket as there is nothing to worry about.

**Comment by molk-ibm** [comment]
This should be the referenced code in the provided screenshot:
https://github.com/projectlombok/lombok/blob/master/src/core/lombok/eclipse/handlers/HandleLog.java#L250

So, no log4j code, as @wkornewald pointed out and we hope you agree on closing this issue.
