### ISSUE TITLE
PDF ist nicht schreibgeschützt

### ISSUE THREAD

**Issue by cannothing** [Digitaler-Impfnachweis/covpass-android#166]
Die PDFs, welche die App erstellt sind nicht schreibgeschützt. 

Ich wollte eigentlich das PDF in Inkscape (kostenlos) - geht aber auch mit anderen Programmen, so runterskalieren, sodass vier Zertifikate auf eine DIN 4 Seite passen. Was muss ich da sehen? Ich kann den kompletten Text wie in einer Textverarbeitung ändern.

Aus der Zweitimpfung wird dann z.B.  eine Boosterimpfung, die die CovpassCheckApp nicht unterscheiden kann.  

Macht man aber von dem abgeänderten Zertifikat ein windschiefes Photo, wenn möglich noch bei schlechten Lichtverhältnissen und jammert in der Apotheke, der QR -Code wird nicht erkannt, der Impfpass ist aber zu Hause in einer anderen Stadt, in wie vielen Apotheken ist man behilflich und gibt dann den falsch hineingeschriebenen Namen, Geburtsdatum usw. ein und man geht als Ungeimpfter als Geboosterter raus?

**Comment by RobTho** [comment]
Auch wenn das PDF schreibgeschützt wäre, könnte man es ohne Probleme manipulieren.

**Comment by thinkberg** [comment]
Selbst wenn das PDF textuell manipuliert werden kann, ist der QR Code der entscheidende Informationstraeger. Der ist manipulationssicher.

**Comment by oliver-steinbrecher** [comment]
Mit den Releases 1.17 und 1.18 werden diese Art von Problemen bei Prüfungen adressiert . D.h. die CheckApp kann dann 2G+ Situationen abprüfen.

**Comment by oliver-steinbrecher** [comment]
Einen Schreibschutz in PDFs zu etablieren, ist erst einmal nicht in der Planung.

**Comment by Ein-Tim** [comment]
@oliver-steinbrecher 

Es dauert mMn zu lange, bis diese Versionen veröffentlicht werden. Das Feature wird jetzt gebraucht. Wie soll jetzt geprüft werden? Gibt es eine Empfehlung des CovPassCheck-Temas dazu?
