### ISSUE TITLE
[covpass-sdk] Does the SDK automatically refresh the required information?

### ISSUE THREAD

**Issue by luzianscherrer** [Digitaler-Impfnachweis/covpass-android#167]
## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Question has not already been asked in another issue

## Your Question
When running in a kiosk mode application that is always on, does the SDK automatically periodically refresh the required information (dsc list, vailidation rules) or does one have to implement that part? In case it has to be implemented by the user of the SDK, is there any example code available?

**Comment by pucherd** [comment]
Hello @luzianscherrer,
The SDK is not refreshing the required information automatically (dsc list, rules, ..) but we already have helper functions which could be called from the host apps.

For example:
https://github.com/Digitaler-Impfnachweis/covpass-android/blob/20faa2bc04f4296d2a220d5676e964272ad3092b/common-app/src/main/java/de/rki/covpass/commonapp/BackgroundUpdateViewModel.kt

**Comment by oliver-steinbrecher** [comment]
@luzianscherrer Did the answer help ?

**Comment by luzianscherrer** [comment]
Yes, thank you. An example would of course be helpful but I think I can manage to use it now.
