### ISSUE TITLE
Two different click areas/ripple effects 

### ISSUE THREAD

**Issue by MDXDave** [Digitaler-Impfnachweis/covpass-android#17]
There are two different click areas/ripple effects on the home screen.

For the first one (the light one) click and hold on the qr code. For the second one (the dark one) click and hold on the bottom pixels of the certificate card.

![Screenshot_20210627-200807__01](https://user-images.githubusercontent.com/6099976/123556236-536c5780-d78a-11eb-979a-863cf49154b0.jpg)
![Screenshot_20210627-200745__01](https://user-images.githubusercontent.com/6099976/123556237-5404ee00-d78a-11eb-83be-63d73de733db.jpg)

**Comment by thomasaugsten** [comment]
Please remove your certificates

**Comment by MDXDave** [comment]
@thomasaugsten thanks. I accidentally selected the wrong images. I replaced them with the censored Version. 😬

**Comment by Ein-Tim** [comment]
@MDXDave Your certificates are still visible through GitHubs edit history. You can delete them.

See: https://docs.github.com/en/communities/moderating-comments-and-conversations/tracking-changes-in-a-comment

**Comment by MDXDave** [comment]
Thanks for the hint!

**Comment by jleufgen** [comment]
Hi all, thanks for the feedback! It will be scheduled in one of the next sprints. Best regards!
