### ISSUE TITLE
(req) option to include QR code manually (without scanning!)

### ISSUE THREAD

**Issue by robovoice1** [Digitaler-Impfnachweis/covpass-android#173]
## Current Implementation

Actual QR codes can only be scanned with the smartphone.

## Suggested Enhancement

Typing in the QR code manually is optinal possible.
For example:
In every post office they can also type in the qr codes when scanning is not possible ( too dark, qr code is not recognized because of dirt etc.).

## Expected Benefits

Those users without a working cam can type in the qr code manually and use this app!

**Comment by RobTho** [comment]
"Post labels" only contain a short number and use data from a server to validate it.
The Vaccination QR code contains much more data and do not contact any server due to privacy.
So it would be nearly impossible to type in such data by hand without errors.

**Comment by Ein-Tim** [comment]
Yeah you would actually have to type in over 500 characters.

**Comment by robovoice1** [comment]
I can type, maybe some other users, too ;-)

**Comment by Ein-Tim** [comment]
@robovoice1 

You would need to type something like this:

```
HC1:6BFOXN%TSMAHN-H+XO5XF7:UY%FJ.G0II:3O6NRBD295QJQC8G9Z3RRAC/GPWBI$C9UDBQEAJJKHHGEC8.-B97U: K8*NHQ2VAP1US1Q7OKHHUEPOP%WUXQ72QETZU3UQRVULKHWWU:16Q8Q*7R-PP9$PB/9OK5JWEMN1/9VSL1Y813.UNNUR+UK0VF/94O5%ZE/NEVTEJAVX5NGTUY*U9/9-3APF6:66A$QZ76LZ6Q59HEDN*I4OIMEDTJCJKDLEDL9CVTAUPIAK29VC4/D-FD8RDVTADYI7VCE8C09DC8CMCI7UJ$JCDVC$XINYJ3A41VCSWC%PD:NKC7D$JCYJC1VCW CTCKY004SIVOHD C9DG4:GXMRD$S+A5M2FNW04QK7TSJWODTUOQ2CVE2JAWH6 $U0QPSXQ:PI*VIUXFOH68ZUOP6OH6XO9IE5IVU4S2PQONTI4L6OUC6VH6ZL4XP0N6F1L3RVT5BZ-H67NMWE7*UHS6NYHY8ES$ILVCK4L2+1M2LDD9GQS4.R1N52FVNCU8+NV6H2+9/$V:%G2.2.$JPJJPKK6U94QMXLMQAL1NJV8U3CW:BP40TX7A$B44W8:VD5J4*101AI
```

This is not practical at all IHMO.

**Comment by RobTho** [comment]
And even if the APP would support such, where you get the data from, if QR code is not readable by dirty print?

**Comment by robovoice1** [comment]
Thanks @Ein-Tim for the info!
@RobTho :  i see it now, unpractical solution. 

I am closing this " idea".
