### ISSUE TITLE
Usage of covpass SDK: Unresolved reference "de.rki.covpass"

### ISSUE THREAD

**Issue by PaulHBauer** [Digitaler-Impfnachweis/covpass-android#174]
Hello, I am trying to use the covpass SDK in a student team project but always get the error "unresolved reference de.rki.covpass". 

You mentioned in an already closed issue (#86) an example project which successfully implements the SDK (https://github.com/pc-coholic/covpass-sdk-demo_test) but even when I clone this project I get the same "unresolved reference" error.

It would be great if someone could help me or give me a hint what the problem could be

In attachment are my build.gradle files
[buildGradleApp.txt](https://github.com/Digitaler-Impfnachweis/covpass-android/files/7905930/buildGradleApp.txt)
[buildGradleProject.txt](https://github.com/Digitaler-Impfnachweis/covpass-android/files/7905949/buildGradleProject.txt)

**Comment by pucherd** [comment]
Hello @PaulHBauer,
Can you please use version 1.297.7 instead of 1.38.0?

**Comment by PaulHBauer** [comment]
Hello @pucherd,
thank you for your quick response.

I now updated the version to 1.297.7 but the "unresolved reference" error is still existing.

**Comment by pucherd** [comment]
Sorry for this question but have you followed the steps mentioned in the README file (under "Building the app")?
https://github.com/Digitaler-Impfnachweis/covpass-android/blob/main/README.md

**Comment by PaulHBauer** [comment]
Thank you for the hint, the file which contains the personal access token was at the wrong place. Now the import worked and the unresolved reference error disappeared.

In the last step of "Building the app" is the command to fetch the latest DSC list described with "./gradlew downloadDscList" but when i try to run this command in the project terminal i get a build failure: "Task 'downloadDscList' not found in root project 'Covpass SDK Demo Test'". Is there a known common problem causing this build failure?

**Comment by wkornewald** [comment]
That task is only availble within this repo. As a workaround you can copy the respective gradle file into your project.

Recarding the NoClassDefFoundError: Please reproduce exactly all steps as described in the README. You're missing coreLibraryDesugaring and maybe other things. Nothing in the "Using the SDK" section is optional.

**Comment by chlorophyll-zz** [comment]
@PaulHBauer I want to suggest for a successful build, that you use Android Studio to open the covpass-android folder and set the build type of the app you want to build to "debug". Then connect an adb-enabled phone and use the run on device option (green "Play" Button). Works for me.

**Comment by PaulHBauer** [comment]
After the issue with the "covpass.properties" file I found an example project which I tried to use but there is "coreLibraryDesugaring" missing what I didn't notice.

So I started my third attempt, followed the README step for step and now it works.
Thank you for your support! :)
