### ISSUE TITLE
Inconsistency in displayed Booster-Rules for AstraZeneca

### ISSUE THREAD

**Issue by julian-af-19** [Digitaler-Impfnachweis/covpass-android#175]
Hi,

there is an inconsistency in the description text for the Booster Rules for AstraZeneca in lines 195 onwards in https://github.com/Digitaler-Impfnachweis/covpass-android/blob/7f333711845394018e71c432d346c352427e3960/covpass-sdk/src/main/assets/covpass-sdk/eu-booster-rules.json 
```
    "Description": [
      {
        "lang": "en",
        "desc": "You may be eligible for a booster because your vaccination with Astra Zeneca was more than 3 months ago."
      },
      {
        "desc": "Sie könnten für eine Auffrischungsimpfung berechtigt sein, da Ihre Impfung mit Astra Zeneca vor mehr als 5 Monaten war.",
        "lang": "de"
      }
    ],
```
Looking at the Logic for the rules I think both the German and the English text should say 3 months, right?

**Comment by timokoenig** [comment]
The local file is outdated but shouldn't affect the booster check since the app loads the updated rules from the national backend.

A simple fix is to update the local file so that it doesn't cause any confusion

**Comment by pucherd** [comment]
Correct, thank you @timokoenig. The local file will be updated in our next release.

**Comment by julian-af-19** [comment]
Alright, thanks! I assumed it wouldn't do much harm anyway if it were still active but since I came a cross it i thought it better to report just in case.
