### ISSUE TITLE
QR-SCAN fail for specific smartphones and or settings [persistent]

### ISSUE THREAD

**Issue by llouc** [Digitaler-Impfnachweis/covpass-android#18]
we have several android-smartphones with failure on QR-code scanning.
"Impfzertifikat enthält keine gültige Signatur"

our test permutations:
- Devices: Huawei P30lite, Samsung Galaxy S6, Samsung J5
- Android versions: 10, 7, 6
- PIN-lockscreen: on/off
- Developer Options: on/off
- Developer Options: Stay Awake: on/off
- Developer Options: Screen Lock - Require to be unlocked: on/off
- internet: blocked (LAN/router NTP always active)
- playstore: blocked/enabled
- region/language: english/german
- REAL QR code ("Impfzertifikat" sheet)
- SAMPLE QR code ("Erika Musterfrau") => FAIL always 

results are persistent, INDEPENDENT from conditions above:
- CovPass v0.160.7 => FAIL => [update] **PASS** after reinstall + internet access enabled (why?)
- CovPassCheck v0.160.7 => FAIL => [update] **PASS** after reinstall + internet access enabled (why?)
- CoronaWarnApp v2.3.4 => PASS (any case)
- CoronaWarnApp v2.4.2 => PASS (any case)

developers,
please check & publish REASON/CONDITION/failuremode asap! (WA if possible)
please confirm if specific "keychain attributes" (see also iOS bug) are relevant (e.g. specific android settings) asap!

QR-codes can by copied by concept.
it is a severe development-flaw, to add specific background-checks (e.g. for pin-screenlock) that are NOT known and NOT clearly shown in case of failure mode.

regards, llouc

[update] https://github.com/Digitaler-Impfnachweis/covpass-android/issues/18#issuecomment-870424413

**Comment by Ein-Tim** [comment]
Does the QR-Code have a valid signature?

**Comment by llouc** [comment]
see above. REAL and SAMPLE QR are working with CoronaWarnApp.

**Comment by Ein-Tim** [comment]
@llouc The Corona-Warn-App is not checking the signature, see https://github.com/corona-warn-app/cwa-documentation/issues/634.

**Comment by llouc** [comment]
how should millions of ENDusers know that ?

**Comment by Ein-Tim** [comment]
@llouc 

Let's discuss this in https://github.com/corona-warn-app/cwa-documentation/issues/634.

Please make sure that the QR-Codes have a valid signature and retest with QR-Codes that have valid signatures. 
If you find QR-Codes with valid signatures and can't import them to CovPass or check them with CovPassCheck, you can report back here.

**Comment by yaerox** [comment]
My dad got an issue with his
Galaxy A3 (2017)
Model SM-A320FL
Android 8.0.0
Samsung Experience 9.0
 
the App doesn't scan the QR. Nothing happens. No error nothing.

When I scanned it using QR-Scanner the read data is identical to a different Phone (iPhone 12 Mini) where the App does accept and read the same QR-Code.

Android and Covpass are bot on the latest Version. If more information are required please let me know. Would be great to get some information.

**Comment by Ein-Tim** [comment]
> why would the SAMPLE QR ("Erika Musterfrau" delivered HERE) have a wrong signature ?
https://github.com/Digitaler-Impfnachweis/certification-apis/tree/master/examples

I don't know why it has a invalid signature but it is not valid.

**Comment by Ein-Tim** [comment]
@yaerox Could you please [open a new issue](https://github.com/Digitaler-Impfnachweis/covpass-android/issues/new) for your error?

**Comment by llouc** [comment]
@Ein-Tim  - my "real" codes come from a real "arztpraxis". they do cross-checks right now. will update if available

**Comment by Ein-Tim** [comment]
@llouc Thanks.

**Comment by llouc** [comment]
[update] added to top entry

**Comment by wkornewald** [comment]
@llouc If Internet access allows validation then this can be caused by changes to the CA. We regularly download CA updates, so the app needs Internet from time to time to keep up with any changes.

**Comment by llouc** [comment]
@wkornewald sure!

**I consider my described use case as extremely rare (e.g. "first app-run offline").**
**so please mark thread as "closed" or solved.
thanks to all contributors!**

After more testing it is clear now that all printed QR-codes ("arztpraxis") are valid.
This is great! As "they" are also doing a very big roll-out (on paper).

But nevertheless, the yielded "Impfzertifikat ungültig/Prüfung nicht erfolgreich" after scanning a valid QR-code is simply wrong/misleading.
After a couple of seconds "online" you'll get a PASS for the same QR-code. (tested repeatedly).

There is no clear indication what exactly has been updated (so far).
I personally would add a strict blocking of QR-scanning, until the first internal update has been conducted successfully.
Plus "internet connection mandatory for first scan" to inform the user during this (short) period.

Additionally I had ONE use case (Android 6) that didn't even work with "always online".
I assume due to some issue with google/playstore service. (= in-app code dependency ?)
But this is just a wild guess.

CWA is a different topic (for sure), as it has a different concept (what a mess).
I predict a lot of people will just show their fake "passes" in CWA and a lot of gate-keepers will accept it. (without re-scan)
This is a severe security issue. No matter what "type of app" CWA wants to be.

thank god we have CovPass/Check :)

**Comment by wkornewald** [comment]
The problem is a little bit more general in that these DSC list / CA updates can happen any day. So, even if having Internet today solves the scanning, not having Internet for 2 weeks could again lead to problems. There is no way for us to know how long these periods without Internet should be allowed to take. In the worst case, one day after the app installation a critical update might be necessary. In the best case you can go on for months without Internet. Also, if you stay without Internet then even publishing a new version on the Play Store wouldn't help.

It's probably easier to think of the "offline-capable" aspect as "it's safest if you're offline for less than a day". Any longer period without Internet puts you at a higher and higher risk of not noticing certificate revocations (thus accepting people who shouldn't be allowed) or missing new certificates (thus revoking people who should be allowed).

**Comment by wkornewald** [comment]
Closing as the original issue could be resolved.

**Comment by llouc** [comment]
server-side dependencies, due to concept... understood ;)
I hate to say that 99% will not understand this.
right now there is zero indicator, if "impfling" or "gate-keeper" is "out-of-date" (criteria)

**Comment by wkornewald** [comment]
I agree that it's not ideal. On the other hand there is no way to know that it's out of date. Maybe displaying a warning on first open and after e.g. 14 days without update is something we should consider, like you suggested. I'll forward this internally.

**Comment by llouc** [comment]
just a simple "timestamp/date" (= last criteria update) NEXT to "pass/fail"

so impfling and gate-keeper can compare PASS/FAIL and timestamp

.... ah mine is newer....get an update!

wild guess :)

**Comment by mk123c** [comment]
Hello,
I don't think this issue should be closed, just yet.
My wife has an Umidigi X Android Phone (with Android 10). When trying to scan the QR-codes of her 1st and 2nd vaccinations, it rejects the codes as invalid. WiFi is connected. A pin is set up for the phone (since I read that some phones - like IPhones - won't accept the QR-code if no PIN has been set for the lock screen).
The same codes do work on 
1) My Samsung S8 with the CovPass app (same version of the app)
2) Her Umidigi X with the Corona Warn-App
So it does seem something to do with the CovPass app on certain phones!

**Comment by wkornewald** [comment]
@mk123c I don't know if it's too much to ask for, but would you be able to launch the prod app with Android Studio and post the logs that appear when scanning? Unfortunately we don't yet have a "report error" button (and backend) which would send us such logs.

**Comment by skyerjoe** [comment]
Dont close the issue 
Device: mi9tpro
CPC Version: 1.28.4
Related to: Digitaler-Impfnachweis/covpass-android#18

2 Certs EU Vaccinations Certifiacte printed from Pharmacy :

Check with CPC:

-2/2 : Not Valid
-1/1 Recovered: Not Valid

best regards
