### ISSUE TITLE
CovPassCheck shall show time of sample drawing for tests additionally in German local time

### ISSUE THREAD

**Issue by jkrwdf** [Digitaler-Impfnachweis/covpass-android#183]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

This issue covers both Android and iOS. 
As this project has no repository for issues affecting both platforms, I open the issue for Android, but iOS is affected as well. 

## Current Implementation
CovPassCheck shows the sample drawing point in time (date and time) in the local device time only, and it does not show which timezone this is. 

![image](https://user-images.githubusercontent.com/5329491/152344908-5a342d64-98b9-48ba-b0ac-bfc4f6425954.png)

This allows the following error to happen (I was personally affected by it): The validation device is configured to have no automatic timezone configuration, and it has a time zone which is different from German time (e.g. Portugal). To "correct" the error that the time in the status bar of the device is wrong, the admin has manually changed the time so that it fits the wall clock. For the user of the device, everything now looks proper.

However, when a RAT test is scanned, the sample time is now shown in Portugal time (which is 1 hour earlier than the real sample time in Germany). 

I demonstrate that here with the same test (I needed 2 minutes to re-configure the time settings :-) )

![image](https://user-images.githubusercontent.com/5329491/152345104-9a48bbf9-0862-4e47-9bd1-5d78074e72c5.png)

## Suggested Enhancement
As CovPassCheck is mainly intended for Germany, I suggest that the sample time is mandatorily shown in German local time (currently CET), and this shall be indicated.

Only when the timezone of the device is different from that, then in addition the sample time in local timezone (and the name of the local timezone) shall be shown.

Example for the latter case: 

**01.02.2022  18.25** 
Zeitpunkt der Probennahme in Deutscher Zeit

**01.02.2022  17:25**
Zeitpunkt der Probennahme in lokaler Gerätezeit ("Portugal/Lissabon")

## Expected Benefits
As for example RAT tests are only valid for 24 hours, an indicated earlier sample time can lead to denial of access.
This shall be avoided. 

In my case, I could mitigate this situation by presenting the PDF of the test center, which luckily was also transmitted to me in addition to the certificate and which of course showed the sample time correctly.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
