### ISSUE TITLE
End of Privacy notice obscured by "OK" button on update

### ISSUE THREAD

**Issue by MikeMcC399** [Digitaler-Impfnachweis/covpass-android#184]
## Technical details

- Device name: various
- OS version: 8.0 and 12 (probably Android version independent)
- App version: 1.17.0

## Describe the bug

After update of CovPass from version 1.16.1 to 1.17.0, when the Privacy notice is displayed, the bottom of the text is obscured by the "OK" button and it is not possible to read it. The contact details (physical and e-mail address) of the data protection officer are hidden.

![image](https://user-images.githubusercontent.com/66998419/152306600-e0a19050-3a6f-45b1-831a-22806a02a301.png)

## Steps to reproduce the issue

1. Install CovPass 1.16.1
2. Open CovPass
3. Tap on "Get started", tap Next, tap Next, tap Next, tap down arrow, tap OK
4. Tap OK
5. Update to CovPass 1.17.0
6. Open CovPass
7. Note that Privacy notice app version 1.17 is shown
8. Scroll down to bottom of Privacy notice
9. Note that Section "11. Data protection officer and contact" is partially obscured by the "OK" button and it is not possible to scroll right to the bottom of the text.

## Expected behaviour

After app update, when the Privacy notice is displayed, it should be possible to read all the text when scrolling to the bottom.

## Possible Fix

Change the display layout so that the "OK" button allows all of the document to be read, including the last section "11. Data protection officer and contact".

## Workaround

After completing onboarding of update, tap on question-mark icon, select Privacy notice. In this case there is no "OK" button displayed and all of the text can be read.

**Comment by pucherd** [comment]
Hello @MikeMcC399,

Good catch, thank you for the finding. This bug will be fixed in 1.18.0 version.

**Comment by pucherd** [comment]
Hello @MikeMcC399, 1.18.0 is available now.

**Comment by MikeMcC399** [comment]
@pucherd 

Thanks! Confirmed fixed in CovPass Android 1.18.0.

Now closing.
