### ISSUE TITLE
Don't show changelog on app startup

### ISSUE THREAD

**Issue by niwla23** [Digitaler-Impfnachweis/covpass-android#186]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Current Implementation
Every time there is an update it will tell you what changed when you open up the app

## Suggested Enhancement
Hide changelogs in some menu so you can still find it but won't be annoyed by it.

## Expected Benefits
There are two reasons why this would make the UX better:

1. When you use this app you want it to be quick. You should be able to just open the app and let someone scan it. With long queues this might actually have an impact on the time it takes to get people in.
2. Most people don't care that the app does not show if you are vaccinated or recovered anymore, if something in the design changed, etc. Most people probably just want to open the app and use it for its sole purpose of showing if you are vaccinated / recovered

**Comment by timokoenig** [comment]
In my opinion the information that something changed is good. Not everyone will be interested in those changes but in case something critical changed, this would be a good place. Also the app only updates every two weeks and after a press of a button this view will not be shown until the next update. I don't think that is too much of a hassle

**Comment by niwla23** [comment]
well 2 weeks is circa everytime I use this app.
Also, last time I did it showed the changelog and a privacy policy, but it was showing a spinner only. Is it downloades from some server at runtime? I did not have internet connectivity at that time
If so, at least it should be available offline.

**Comment by timokoenig** [comment]
It should be offline available like it is for iOS. Maybe the team can have a look here

**Comment by voltcraft1** [comment]
> In my opinion the information that something changed is good. 

This is an app for mass market (i.e) common people. They have no clue about change log. Just put it behind some menu. Putting  changelog is absolutely annoying and causes people to get confused. Why?

1. The average user (not IT) people expect the app to look/display same thing when opening. Especially senior citizens. (For example: Learn from banks - they did not replace ATMs with complex 16 digitpassword - just 4 - good for everyone).
2. The common user may think something happened with their vaccination status when things pop-up.

Thanks

**Comment by timokoenig** [comment]
@voltcraft1 the app does not show a technical changelog so everyone is able to understand it. It also only includes important announcements.

e.g.

**Accessibility Statement**
The CovPass app as well as the CovPassCheck app now include an accessibility statement that can be found in the app settings. It provides information about how accessible the app currently is and what is still being improved.

**Improved certificate assignment**
The app can better match newly scanned certificates to the correct persons, even if there are differences in the spelling of the name, title or middle name.

**2G+ check: Recovery certificates**
It is now also possible to scan recovery certificates as valid 2G+ proofs. Also the combination of basic immunization and recovery is now possible as 2G+ proof.

**Comment by timokoenig** [comment]
Just a quick idea, instead of the dialog that pops up when the user opens the app, there could be a banner that shows the full announcements when clicked on. The announcements itself should also be placed in the settings.

With this alternative the user does not get prompted anything but sees that something is different. The banner could disappear on the next app start or with a click on a close button.

For example:

<img width="445" src="https://user-images.githubusercontent.com/4365095/157735026-01b76f70-0c54-4ea5-bb3e-e1698ee9eac8.png">

Maybe the team does have an opinion on this topic. I'm just putting out some ideas

**Comment by voltcraft1** [comment]
> the app does not show a technical changelog so everyone is able to understand it. It also only includes important announcements.

Firstly thanks for consideration. I do understand your point. But from what I have seen as an administrator (supporting) plenty people is that - anything that is different to standard view that users have been used to is a distraction. 


> It is now also possible to scan recovery certificates as valid 2G+ proofs. Also the combination of basic immunization and recovery is now possible as 2G+ proof.
> The app can better match newly scanned certificates to the correct persons, even if there are differences in the spelling of the name, title or middle name.



TBH, these are not necessarily for the average person to understand. You may put in many features but they want things to work SEAMLESS. Just that.

**Comment by niwla23** [comment]
I really like the approach of @timokoenig to make a small non-blocking popup instead of a full screen modal. I also agree to the things @markusgerber76 said, people who are not tech-savy tend to be easily confused by pop-ups. 
I also have the feeling that not all announced changes are important. I am not sure but I think there were some messages about design changes in the past, but correct me if I'm wrong. 

(Also Privacy Policy, probably nobody cares as this is an offline app but you have to do it because of GDPR but that is off-topic.)

**Comment by Ein-Tim** [comment]
- Seems like it will be possible to deactivate the changelog soon: https://github.com/Digitaler-Impfnachweis/covpass-apps-i18n/pull/236

**Comment by MikeMcC399** [comment]
@niwla23 

I noticed that this enhancement was implemented in CovPass 1.31.0, so you should be able to close your issue now.

![CovPass Information](https://user-images.githubusercontent.com/66998419/190350586-4ac00c3e-9b83-4416-9ce0-13fc5ca6659a.png)

![CovPass Update Notifications](https://user-images.githubusercontent.com/66998419/190350612-bc5036a9-3cb7-484d-8700-9f075e89be18.png)

Incidentally the information that the CovPassCheck App beeps when scanning is misleading. The default setting is for it not to beep. It can however be enabled.
