### ISSUE TITLE
Positive-test reports are not accepted

### ISSUE THREAD

**Issue by ydirson** [Digitaler-Impfnachweis/covpass-android#188]
In France positive tests are accepted as valid between 11 days and 6 months.  Scanning one in CovPass shows a message saying only negative tests can be imported.  It would be reasonable to just accept the positive test results as well, since the validity will anyway be decided by the software doing the check scan.

**Comment by alexcimander** [comment]
Hey @ydirson,

thank you for reporting this. Since a positive test result does not come with a direct "value" for the users of the CovPass(Check) wherare the CWA can use this information for reporting an infection etc. we had no intention to allow positive results in the app.

However I understand your Use-Case and we created a ticket for CovPass. We will keep you updated :-)

**Comment by Ein-Tim** [comment]
I don't really understand. Is there an EU DCC for positive tests? I don't think so, or?

**Comment by timokoenig** [comment]
@Ein-Tim at least from a technical perspective an EU DCCs can also have a positive test result

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
