### ISSUE TITLE
Check situation "Entering DE" recognizes an 11 month old 2/2 certificate as valid

### ISSUE THREAD

**Issue by jkrwdf** [Digitaler-Impfnachweis/covpass-android#189]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3 XL
- OS version: 12
- App version: 1.18.0

## Describe the bug

I have configured the app with the new feature "Check situation" as "Entering DE". 
My assumption is that then, the (stricter) travel rules in the EU are applied. 

They comprise (since Feb 2022) that 2/2 certificates are only valid for 9 months. 

However, when I scan such certificate (2/2, Date of vaccination 2021-03-08 which is > 9 months) in mode "Entering DE", I still get a "Certificate valid" (in 3G mode) or "Valid 2G proof" (in 2G+ mode).

## Steps to reproduce the issue

See above.

## Expected behaviour

Certificate invalid.

**Comment by timokoenig** [comment]
It is the same with a couple other tickets in the Android and iOS repository. The EU rules have not been updated in a while and still checks for 365 days, see https://timokoenig.github.io/eu-dcc-rules/?country=DE&rule=VR-DE-0004

**Comment by pucherd** [comment]
Hello @jkrwdf,

Thank you for report this bug.
Just double-check the domestic rule definition and it looks like the VR-DE-0004 rule is not updated on the domestic rules endpoint.
https://distribution.dcc-rules.de/domesticrules/1313e59f84f472694eece639cbe955b5c469ed7e0adb319a731d2d77f62f3e31

**Comment by timokoenig** [comment]
@pucherd from my understanding "Entering DE" should use the EU business rules and not the domestic ones, right?

**Comment by timokoenig** [comment]
Regarding the domestic rules, the full immunization should not have a expiration date as far as I am informed

**Comment by pucherd** [comment]
> @pucherd from my understanding "Entering DE" should use the EU business rules and not the domestic ones, right?

@timokoenig good catch, right the "Entering DE" is using EU business rules.

**Comment by jkrwdf** [comment]
The austrian check app "GreenCheck" identifies the mentioned certificate in mode "Einreise 3G" as invalid. 

Under the assumption that "GreenCheck" is based on the same rule set as CovPassCheck, the rule set seems to be OK (this statment holds true of course only if those rules are hosted at the same endpoint for all EU check apps).

**Comment by Ein-Tim** [comment]
@jkrwdf Can you check again? The rules have been updated: https://timokoenig.github.io/eu-dcc-rules/?ruleset=eu-dcc-rules&country=DE&rule=VR-DE-0004

**Comment by jkrwdf** [comment]
I confirm the effect of the new rules. 

The 2/2 certificate from March 2021 is now recognized as invalid with check mode "Entering", while in check mode "Within Germany" it is still shown as valid. 

Resolved, closing.
