### ISSUE TITLE
Publish library and components to Maven

### ISSUE THREAD

**Issue by pc-coholic** [Digitaler-Impfnachweis/covpass-android#19]
As far as I can tell, all the libraries and components are being already published to a private Nexus repository. Reading the gradle-files, it seems like a publishing them to Maven Central is also being discussed.

Since integrating the covpass-sdk into other apps is rather bothersome as it is right now, I would like to strongly advocate for either starting the publishing process to Maven Central or at least make the builds available somewhere else. From my understanding all required elements are already available at https://nexus.open-insurance-platform.com/repository/ega-releases/ - although hidden behind a login prompt. So perhaps you could at least remove the login requirement or share a set of credentials

**Comment by wkornewald** [comment]
We're in the process of setting up and validating Maven Central access and also switching to GitHub Actions. The internal repo unfortunately can't be made public, so I can only ask for a little bit more patience. :)

**Comment by wkornewald** [comment]
We have now published the libs to GitHub Packages in this repo. Maven Central (and the switch to the final group id de.rki.covpass) still depends on some organizational tasks and I'm not sure yet when this will be done. At least the current solution should already allow integration into third-party apps, even if it's not the final one.

**Comment by pc-coholic** [comment]
Great - thank you! Very much appreciated!

**Comment by wkornewald** [comment]
I'll close this ticket since the actual request is done. Maven Central might have too many bureaucratic consequences, so we might never publish there (I've done that for my OSS project and it's a pain and publishing can break from time to time and require manual intervention).
