### ISSUE TITLE
Source code on GitHub outdated - contradictory readme

### ISSUE THREAD

**Issue by G00fY2** [Digitaler-Impfnachweis/covpass-android#190]
Hi everyone,

not sure if that was always the case and the mirroring is only delayed. But recently (since end of the last year) the source code here on GitHub is always out of date. Latest release branches are not available (e.g. 1.18.x) and the main branch is outdated too.

This is contradictory to what is stated in the Readme:
> We publish stable releases in separate release/... branches (e.g. release/1.9.x). Pick the latest release branch to get the latest officially published app version.
The main branch contains the development state up to the latest stable release branch. 

I know that there was a big public outcry about the Luca app not providing the actual source code of the latest releases on their public repos.

Is there any official statement on the state of the source code management? Why don't you provide a nightly mirror of your code or something like that?

**Comment by pucherd** [comment]
Hello @G00fY2, sorry for the later release. The release/1.18.x is published now.

**Comment by G00fY2** [comment]
@pucherd Yet again an app version (1.19.0) and no chance for us users to see what changed. 😞

**Comment by timokoenig** [comment]
@G00fY2 from past experience it sadly takes one or two days after a release

**Comment by p-schneider** [comment]
Can we get one last push to this repo with the latest source code up to the "retirement release" 1.44.0?

@pucherd @edgar-oliveira-softinsa @wkornewald @Staeffy @ingowerren Thank you and Thanks to everyone who participated in working on this.

**Comment by pucherd** [comment]
Hello @p-schneider,
Thank you for your feedback, the branch is released now:
https://github.com/Digitaler-Impfnachweis/covpass-android/tree/release/1.44.x
