### ISSUE TITLE
CovPassCheck: Setting "Check 3G / Check 2G+" and for the latter "No test is needed..." are not persisted

### ISSUE THREAD

**Issue by jkrwdf** [Digitaler-Impfnachweis/covpass-android#191]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3 XL
- OS version: 12
- App version: 1.18.0

## Describe the bug

A checking person uses CovPassCheck in a certain setup. 
The application today supports three levels of configuration: 
- Check situation (configured in Settings)
- Decision between 3G and 2G+ Check
- For 2G+ the switch "No test is needed when a booster vaccination is given"

While the first setting is persisted and is kept when the application gets displaced from memory and restarted, the latter two are lost and need to be activated manually again. 

## Steps to reproduce the issue

Choose "Check 2G+" and set the switch "No test...".
Displace CovPassCheck from memory.
Start CovPassCheck.

You start again with "Check 3G" and when you switch to "Check 2G+" the switch is not set. 

## Expected behaviour

Those two settings are as relevant as "Check situation" from the perspective of the checking person. 

CovPassCheck is supposed to be used at a certain location. The rules for the location are not changing from check to check, therefore keeping those settings is an aide to the user in case the phone is also used for other applications and CovPassCheck started only on demand (and then eventually was displaced).

**Comment by timokoenig** [comment]
I can confirm the same for iOS

**Comment by alexcimander** [comment]
Hey everyone,

thank you for reporting this bug. We added it to one of the next sprints. 

- Selected rule-sets (domestic, travel)
- Selected Mode and
- Selected "Booster as Test replacement" 

Should be persistent soon. 

Thank you!

**Comment by pucherd** [comment]
Hello @jkrwdf,
As this feature is not available in the latest version and was replaced with Mask check / Immunity check (these settings are persisted now), can you please double-check?
Thank you.

**Comment by jkrwdf** [comment]
Hello @pucherd ,

what exactly does "double-check" mean? 

I agree that the actual version of CovPassCheck does not have the user interface elements any more which were related to this issue, but this does not automatically mean and they were deleted from the application codebase. It might be that they are still present, including the source code handling their actions, and depending on the future development of the situation they might be pulled out again. 

When we now close this issue today with the argument "out of sight, out of mind" and the issue then comes back, we have a roly-poly ("Stehaufmännchen"). 

If you ask me to close the issue, I will do so.

Best regards.

**Comment by pucherd** [comment]
Hello @jkrwdf,

The toggle in CovPassCheck (3G / 2G+) is present in the app but the text labels and the functionality behind it is different (Mask Check / Immunity Check). 
But the UI element itself already provides the persisting function you reported in this ticket. By "double-check" I meant if you could reproduce the issues with the current app version - switching between Mask Check and Immunity Check results in persisting these states.

**Comment by pucherd** [comment]
Closing this issue as the toggle in CovPassCheck persists its state.
Please reopen in case you encounter any issues. Thank you.
