### ISSUE TITLE
Check for travel... Not possible to validate

### ISSUE THREAD

**Issue by markusgerber76** [Digitaler-Impfnachweis/covpass-android#196]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation

This UI is clunky.

## Suggested Enhancement

1. Ask the time and date
2. Have a scrolling list of all countries with  

```
Green Tick  Country name
Red Tick Country name
Question mark Country name
```

## Expected Benefits

Simple scroll is better. In future, assuming 190 countries will be onboard, one can put a filter on top. To filter only selected country by typing few letters....

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
