### ISSUE TITLE
add syringe icons on the front page of app for quick verification

### ISSUE THREAD

**Issue by markusgerber76** [Digitaler-Impfnachweis/covpass-android#197]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation

In most shops/entry points they are checking if one has 3/3 vaccinations (at least in Germany).

## Suggested Enhancement

On the front page, of the app, can you put icons (emoticons); and text 3/3 in green colour. Or whatever 2/3 depending on the status. Make it red - if it is NOT valid.

And the icons for syringe is already in Android and iOS. Please do NOT ask (or contract a new graphic designer) to build a large 100 MB image just for this. So that app become large... 
https://emojipedia.org/syringe/

## Expected Benefits

Just look at first page to get status.

You may say ideally the shop should scan - but if you go in reality most shops do NOT scan. Please understand.

![2](https://user-images.githubusercontent.com/43269671/157899631-04330beb-c2e1-4ec3-b401-1fbf01c5e8f3.png)

**Comment by Ein-Tim** [comment]
> You may say ideally the shop should scan - but if you go in reality most shops do NOT scan. Please understand.

Then IHMO it is the wrong way to give them a reason to not scan but rather hide all details but the QR code to force them to scan the code. There is no other option to be sure that the certificate shown & the app is not manipulated, especially as it is open source. 

Anything that supports verification of EU DCCs but scanning them weakens protection against abuse.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
