### ISSUE TITLE
Allow Import of PDF/Image

### ISSUE THREAD

**Issue by MDXDave** [Digitaler-Impfnachweis/covpass-android#20]
In NRW (Vaccincation centers from the KVNO) you can download your vaccincation certificate as a PDF file.

To import the certificate to the Covpass App, you need to print it or scan it from another device.

It would be much more comfortable to allow the certificate to be importable via PDF or image. 

As example you can Look into the swiss _Covid Cert_ app you can import PDF files that includes the qr code and it will be added to the app automatically:

https://github.com/admin-ch/CovidCertificate-App-Android

**Comment by 10Meisterbaelle** [comment]
I have the problem that I need to import my test certificate

**Comment by jleufgen** [comment]
Hello, thank you for your feedback! With one of the next releases the import into the app will be possible. Best regards!

**Comment by jleufgen** [comment]
Thank you! This topic is currently under discussion with the client.

**Comment by jleufgen** [comment]
@MDXDave @10Meisterbaelle Such functionality is not currently planned. However the certificate can e.g. also be scanned at any time from the paper printout of the QR code or another smartphone. Best regards!

**Comment by alexcimander** [comment]
Hi everyone! 
Update: The import of the certificates was added to the backlog! We hope for an implementation soon! ⏲️ 
We will keep you updated.

Thank you for your great suggestions! 👍

**Comment by MikeMcC399** [comment]
@alexcimander 

> We hope for an implementation soon!

Is there any update to your time-scales for CovPass implementation of scanning certificate QR codes embedded in a PDF file?

The functionality has been part of the Corona-Warn-App since version 2.11 which was released on October 6, 2021. See https://www.coronawarn.app/en/blog/2021-10-06-cwa-version-2-11/.

**Comment by Ein-Tim** [comment]
Looking at i.e. PR https://github.com/Digitaler-Impfnachweis/covpass-apps-i18n/pull/225 it seems like this feature will be shipped soon.

**Comment by pucherd** [comment]
Hello @MikeMcC399 and @Ein-Tim,
You're right the feature will be released soon in version 1.28 (should be released during next week).

**Comment by MikeMcC399** [comment]
- See https://github.com/Digitaler-Impfnachweis/covpass-android/discussions/223

**Comment by memartinb** [comment]
This might also help with camera issues like #114 or #177.

**Comment by MikeMcC399** [comment]
- I was able to import a certificate from a PDF in CovPass 1.28.0, however a second attempt using the same certificate gave a misleading error message. See issue https://github.com/Digitaler-Impfnachweis/covpass-android/issues/225

**Comment by MikeMcC399** [comment]
Since this enhancement request has been fulfilled in the released version CovPass 1.28.0, it could be closed.
