### ISSUE TITLE
Certificate widget

### ISSUE THREAD

**Issue by TillJohanndeiter** [Digitaler-Impfnachweis/covpass-android#204]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Current Implementation

You have to open the app every time to show your main certificate, which is especially under 2G rules not comfortable.

## Suggested Enhancement

A widget could be added on the home screen that shows the main certificate of a given person. When a widget is placed, a holdername can be selected. 

## Expected Benefits

The user don't have to open the app every time to show the main certificate.

I already implemented a prototype on the branch certificateWidget https://github.com/TillJohanndeiter/covpass-android

**Comment by Ein-Tim** [comment]
FYI: Under iOS there was a PR (https://github.com/Digitaler-Impfnachweis/covpass-ios/pull/65) from the community which would implement this, however, the stakeholders (RKI) don't want to implement such a feature at the moment.

**Comment by pucherd** [comment]
Hello @TillJohanndeiter, thank you for bringing this up also for Android. 
We created a ticket in our Backlog and will inform you once this feature will be planned in one of our upcoming releases.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
