### ISSUE TITLE
What is the specific CovPass version that includes Certificate Renewals?

### ISSUE THREAD

**Issue by cookiengineer** [Digitaler-Impfnachweis/covpass-android#207]
My certificate for the COVID vaccination is going to be invalid starting next week.

So my question is now: What is the minimum version of CovPass that includes the certificate renewals that is implied/suggested on the website?

Link to the FAQ: https://digitaler-impfnachweis-app.de/faq/

FAQ specifically says:

```
Die technische Gültigkeit der digitalen COVID-Zertifikate läuft nach 365 Tagen automatisch ab. Für alle relevanten Zertifikate erhalten Sie dazu 28 Tage vor Ablauf eine Mitteilung in der CovPass-App. Um Ihren Impfstatus weiterhin nachweisen zu können, müssen die entsprechenden Zertifikate aktualisiert werden. Die dazu notwendige Neuausstellung können Sie demnächst in der App mit wenigen Klicks selbst durchführen.
Noch vor Ablauf Ihrer Zertifikate wird in den App Stores ein Update mit der Funktion zur Neuausstellung zur Verfügung stehen.
```

The German Press also started to confirm this, quoting your FAQ... but without naming any details.
After calling your hotline(s) I realized that this is way too technical for them to answer, hence this opened issue.

**Comment by MikeMcC399** [comment]
@cookiengineer 

The certificate re-issue functionality for expiring vaccination certificate is also offered by the Corona-Warn-App from version 2.23 onwards. This version is being rolled out over the next 48 hours for Android. See https://www.coronawarn.app/en/blog/2022-06-01-cwa-2-23/.

I would guess that there will soon be a new version of CovPass App and it would be good to get confirmation here from the developers.

**Comment by alexcimander** [comment]
Hey everyone,

1.26 will offer the renewal functionality for CovPass - The release will go into review within the next hours. With that a release is expected next week! 😊

**Comment by Ein-Tim** [comment]
Version 1.26 has been released to the public. Please close this issue @cookiengineer.

**Comment by cookiengineer** [comment]
It still hasn't been published to neither the GitHub releases/tags nor the [f-droid repo](https://f-droid.org/en/packages/de.rki.covpass.app/).

Can you please also push a new tag/release to this git repository so that build bots pick it up?

**Comment by Ein-Tim** [comment]
@cookiengineer 

Yeah, the missing source code & release tag are sadly normal, I opened an issue reg. this: https://github.com/Digitaler-Impfnachweis/covpass-android/issues/209

The F-Droid repo is not controlled by the official CovPass-Team. It is a fork maintained by the community. I'm sure @jugendhacker will downstream the changes as soon as the source code is published here.

**Comment by MikeMcC399** [comment]
I have updated to CovPass Android 1.26.0 with a 1/2 vaccination certificate which expires soon. 

I'm getting the message:
"Current certificate expires on ...
You can easily replace the certificate in the CovPass app by using the renewal function in the overview of your certificates or by scanning a newly issued certificate".

I couldn't find any button to request a renewal, however after I killed the app and restarted it, I got a "Renew vaccination certificate" button showing.

**Comment by Ein-Tim** [comment]
> I couldn't find any button to request a renewal, however after I killed the app and restarted it, I got a "Renew vaccination certificate" button showing.

Same here. Restart seems necessary somehow.
