### ISSUE TITLE
Tell users specifically why a cert is invalid

### ISSUE THREAD

**Issue by My1** [Digitaler-Impfnachweis/covpass-android#21]
![20210702_123502.jpg](https://user-images.githubusercontent.com/6696524/124262861-db5bb400-db32-11eb-8e25-ecaeea473c3a.jpg)

Had to be a photo because i can't screenshot

I very highly doubt that the app doesn't exactly know why the cert is invalid (in this case only 1 of 2 vax) and maybe tell that to the user instead that it is invalid for any or no reason (qr code not readable)

**Comment by Ein-Tim** [comment]
Can this be transferred to the documentation repository since this also affects iOS.

**Comment by My1** [comment]
it apparently has become worse, as it now literally shows just either not compliant or tech issue, just great...

**Comment by DinoTymo** [comment]
Especially after receiving two shots it's very confusing that the app shows "Impfzertifikat ungültig".
There should be something like "Impfzertifikat gültig in X Tagen" because when you're fully vaccinated but 14 days haven't passed yet, the app just shows that it's invalid.

**Comment by jleufgen** [comment]
Hi all :) This topic will be worked on in one of the next sprints. Thank you for the feedback! Best regards!
