### ISSUE TITLE
PRIO: Wrong reasoning for certificate renewal

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-android#210]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Huawei P Smart 2019
- OS version: Android 10
- App version: 1.26

## Describe the bug

The Android app has shows a wrong reasoning when attempting to reissue the certificate which can be found here: https://github.com/denysvitali/covid-cert-analysis/blob/master/RESULTS.md?rgh-link-date=2022-06-08T11%3A03%3A06Z#samplesbrandenburgtesttxt

<img src="https://user-images.githubusercontent.com/67682506/172603102-70f0b819-5091-4b3e-ad73-fe2094cdd556.png" width="300">

The certificate is simply expired and does not have the wrong format. I only have the 2/2 certificate in the app & not the 1/1 also. Please make sure that this is only a text issue and not that I actually get a 2/1 certificate then.

## Steps to reproduce the issue

1. Import a technically expired certificate into the app
2. Start the renewal process
3. See the wrong reasoning on the ""Änderungen bei Ihren Zertifikaten" text
4. Continue the renewal process and make sure that the certificate is not reissued as 2/1

## Expected behaviour

Same reasoning for certificate renewal as under iOS:
<img src="https://user-images.githubusercontent.com/67682506/172603412-29e01270-1eb3-47f1-aa64-9331062e2275.jpeg" width="300">

## Additional information

Certificate used to test: https://github.com/denysvitali/covid-cert-analysis/blob/master/RESULTS.md#samplesbrandenburgtesttxt

## Pings

I request prioritized work on this item to make sure that no certificates are renewed incorrectly. Thus I'm pinging:
@alexcimander
@pucherd
@wkornewald
@molk-ibm

**Comment by Ein-Tim** [comment]
As @MikeMcC399 said in #211 that the renewed certificate is the correct certificate, it seems like this is only a text issue. Please still fix this ASAP.

**Comment by alexcimander** [comment]
Hi @Ein-Tim, 
thank you for reporting this bug - it seems that the wrong text was used here. @pucherd catched it - we are working on a fix which we will provide asap.
Thank you

**Comment by alexcimander** [comment]
Hey everyone! Update: We are currently working on a HF 1.26.1 which will take care of:

**1.) Wrong reason for Re-Issue mentioned (Android only)**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/211
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/210

**2.) Misleading Text for (about to be expired) DCCs in DCC-Details**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/212
https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/194

**3.) Misleading Text within renewal process**
https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/192

**4.) "there are news" but not "there is news" within notification**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/217  

**5.) In Investigation: "No renewal offered for 1/2 vaccination if it is the only vaccination**  

-------------------------------------------------------

the bugs 

6.) Notification about expiry is played out twice (Android only)
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/214

7.) Re-Open of the App required (Android only) is not stated by the info text
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/213

are currently in investigation - we will provide a fix asap but these two are not expected to be fixed within the HF.


Thank you all for the patience and supporting discussions! 🦸

**Comment by Ein-Tim** [comment]
Closed as this is fixed according to @MikeMcC399: https://github.com/Digitaler-Impfnachweis/covpass-android/issues/211#issuecomment-1155600913

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I did not test with an expired 2/2 vaccination certification. I only tested with a 1/2 vaccination certificate that was due to expire in the next 28 days.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Ok, thanks. I will retest with a 2/2 when I'm back from vacation again.

**Comment by Ein-Tim** [comment]
Confirm fixed.
