### ISSUE TITLE
1/2 Vaccination certificate wants to renew to 2/1 certificate

### ISSUE THREAD

**Issue by MikeMcC399** [Digitaler-Impfnachweis/covpass-android#211]
## Technical details

- OS version: Android 12
- App version: 1.26.0

## Describe the bug

CovPass offers to renew a 1/2 vaccination certificate by replacing it with a 2/1 certificate.

The text says:

"The EU specifications for certain vaccination certificates have been changed. This certificate does not correspond to the current numbering. It is still valid. However, if it is a certificate for a booster vaccination, it will not be recognized as such when checked.

Therefore we recommend requesting a new certificate with the number 2/1 directly free of charge via the app."

In fact the new certificate produced is **not** a 2/1 certificate. The renewed certificate is correctly a 1/2 vaccination certificate.

## Steps to reproduce the issue

Renew an expiring 1/2 vaccination certificate

## Expected behaviour

The app should not suggest that an expiring 1/2 vaccination certificate be replaced by a 2/1 vaccination certificate. The text is incorrect and does not correspond to the renew action which actually takes place. The renewed certificate is correctly a 1/2 vaccination certificate.

**Comment by Ein-Tim** [comment]
Closely related to #210.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
- This issue is basically a duplicate of #210, however I was testing with my own valid 1/2 vaccination certificate, not a test certificate. Also I completed the reissue process, so I was able to examine the new certificate and determine that it was correct.

**Comment by Ein-Tim** [comment]
@MikeMcC399 Thanks. I'll leave my issue open to, as this is quite a serve text issue.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I suggest to leave both issues open and first see what the developer response is. I'm happy to close my issue if necessary.

**Comment by alexcimander** [comment]
Hi @MikeMcC399 , 
thank you for reporting this bug - it seems that the wrong text was used here. @pucherd catched it - we are working on a fix which we will provide asap.
Thank you

**Comment by alexcimander** [comment]
Hey everyone! Update: We are currently working on a HF 1.26.1 which will take care of:

**1.) Wrong reason for Re-Issue mentioned (Android only)**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/211
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/210

**2.) Misleading Text for (about to be expired) DCCs in DCC-Details**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/212
https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/194

**3.) Misleading Text within renewal process**
https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/192

**4.) "there are news" but not "there is news" within notification**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/217  

**5.) In Investigation: "No renewal offered for 1/2 vaccination if it is the only vaccination**  

-------------------------------------------------------

the bugs 

6.) Notification about expiry is played out twice (Android only)
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/214

7.) Re-Open of the App required (Android only) is not stated by the info text
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/213

are currently in investigation - we will provide a fix asap but these two are not expected to be fixed within the HF.


Thank you all for the patience and supporting discussions! 🦸

**Comment by MikeMcC399** [comment]
1.) Wrong reason for Re-Issue mentioned (Android only)
- https://github.com/Digitaler-Impfnachweis/covpass-android/issues/211
- https://github.com/Digitaler-Impfnachweis/covpass-android/issues/210

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Please check with version 1.26.1.

I'm currently on vacation and therefore doesn't have my Android device with me.

**Comment by MikeMcC399** [comment]
This issue is fixed in 1.26.1.
