### ISSUE TITLE
"Renew vaccination certificate" button only displayed after app restart

### ISSUE THREAD

**Issue by MikeMcC399** [Digitaler-Impfnachweis/covpass-android#213]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [ ] Bug is not already reported in another issue
The problem is also mentioned in https://github.com/Digitaler-Impfnachweis/covpass-android/issues/207#issuecomment-1149806209

## Technical details

- OS version: Android 12
- First reported in App version: 1.26.0
- Reproducible also in App version: 1.36.0

## Describe the bug

- When a 1/2 vaccination certificate with technical expiry date less than 28 days in the future is scanned, the app displays the text "You can easily replace the certificate in the CovPass app by using the renewal function in the overview of your certificates or by scanning a newly issued certificate" however there is no button "Renew vaccination certificate" available to carry out that function unless the app is stopped and restarted. (App version 1.26.0).

- When a 1/2 vaccination certificate with technical expiry date less than 28 days in the future is scanned, the app displays the text "You can easily renew your latest certificate in the CovPass app. Previous certificates will not be renewed. To do so, use the renewal function in the overview of your certificates or scan a newly issued certificate." however there is no button "Renew vaccination certificate" available to carry out that function unless the app is stopped and restarted. (App version 1.26.1 and later).

## Steps to reproduce the issue

1. Install CovPass
2. Go through onboarding
3. Scan a 1/2 vaccination certificate with technical expiry date less than 28 days in the future
4. Note the text information:<br>"Current certificate expires on ...<br>You can easily replace the certificate in the CovPass app by using the renewal function in the overview of your certificates or by scanning a newly issued certificate".  (1.26.0) or "You can easily renew your latest certificate in the CovPass app. Previous certificates will not be renewed. To do so, use the renewal function in the overview of your certificates or scan a newly issued certificate." (1.26.1 & later)
5. Click on back arrow
6. Click on "Display certificates"
7. Click on "Manage certificates"
8. Note that there is no button "Renew vaccination certificate" displayed yet
9. Exit the app and use Android to Close all apps
10. Restart the app
11. Note pop-up:<br>"**Check the validity of your certificates**<br>If you can renew this certificate in the app, you will receive a notification. You can find more information about replacing expired certificates in our FAQs."
12. Tap "OK"
13. Note for app versions before 1.28.0 the previous pop-up repeats:<br>"**Check the validity of your certificates**<br>If you can renew this certificate in the app, you will receive a notification. You can find more information about replacing expired certificates in our FAQs."
14. Tap "OK"
15. Tap "Display certificates" > Tap "Manage certificates"
16. Note that a new tile appears:<br>"**Renewal needed**<br>The technical expiry date of your vaccination certificate is coming up. Renew the certificate to continue using it." (1.26.0) or "**Renewal needed**<br>The technical validity of your vaccination certificate is about to expire or has already expired. Renew the certificate to continue using it." (1.26.1 and later) with the button "Renew vaccination certificate"

## Expected behaviour

The app should only display the text "You can easily replace the certificate in the CovPass app by using the renewal function in the overview of your certificates or by scanning a newly issued certificate" (1.26.0) or "You can easily renew your latest certificate in the CovPass app. Previous certificates will not be renewed. To do so, use the renewal function in the overview of your certificates or scan a newly issued certificate." (1.26.1 and later) if the button "Renew vaccination certificate" is also available.

**Comment by alexcimander** [comment]
Hi Mike,

thank you for reporting this bug - currently the re-issue for Android will be offered as soon as you restart the app. You are completely right: Again the text is misleading. We are currently working on several fixes. We will keep you updated.

Thank you!

**Comment by alexcimander** [comment]
Hey everyone! Update: We are currently working on a HF 1.26.1 which will take care of:

**1.) Wrong reason for Re-Issue mentioned (Android only)**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/211
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/210

**2.) Misleading Text for (about to be expired) DCCs in DCC-Details**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/212
https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/194

**3.) Misleading Text within renewal process**
https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/192

**4.) "there are news" but not "there is news" within notification**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/217  

**5.) In Investigation: "No renewal offered for 1/2 vaccination if it is the only vaccination**  

-------------------------------------------------------

the bugs 

6.) Notification about expiry is played out twice (Android only)
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/214

7.) Re-Open of the App required (Android only) is not stated by the info text
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/213

are currently in investigation - we will provide a fix asap but these two are not expected to be fixed within the HF.


Thank you all for the patience and supporting discussions! 🦸

**Comment by MikeMcC399** [comment]
The texts have changed in 1.26.1 (see PR https://github.com/Digitaler-Impfnachweis/covpass-apps-i18n/pull/213) so I updated the issue description and steps to reproduce.

**Comment by MikeMcC399** [comment]
Steps to reproduce updated for 1.28.0 release.

**Comment by MikeMcC399** [comment]
This confusing issue is still reproducible in CovPass Android 1.31.0.

By now the certificate I used to test has already expired. The "Renew vaccination certificate" button still does not appear after scanning an expired certificate, unless the app is killed and then restarted.

**Comment by MikeMcC399** [comment]
This issue has not been fixed in CovPass Android 1.36.0. It is still necessary to restart the CovPass app in order to renew a certificate.

**Comment by Ein-Tim** [comment]
According to https://github.com/Digitaler-Impfnachweis/covpass-android/releases/tag/v-1.675.0, this issue should be fixed with version 1.39. Can you cross-check @MikeMcC399?

**Comment by MikeMcC399** [comment]
After scanning a vaccination certificate which expired less than 90 days ago, the app immediately offered a "Renew now" button (and a "Renew later" option).

This issue is resolved with CovPass 1.39.0
