### ISSUE TITLE
"Check the validity of your certificates" notification displayed twice

### ISSUE THREAD

**Issue by MikeMcC399** [Digitaler-Impfnachweis/covpass-android#214]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)<br>~~The FAQ are not yet adjusted to cover the functionality in CovPass 1.26.0~~
* [ ] Bug is not already reported in another issue
The problem is also mentioned in https://github.com/Digitaler-Impfnachweis/covpass-android/issues/213

## Technical details

- OS version: Android 12
- First reported on App version: 1.26.0
- reproducible also on App version: 1.26.1 & 1.27.0

## Describe the bug

When a 1/2 vaccination certificate with technical expiry date less than 28 days in the future is scanned and the app is restarted, the notification "**Check the validity of your certificates**" is displayed and then repeated after the first notification is dismissed.

## Steps to reproduce the issue

1. Install CovPass
2. Go through onboarding
3. Scan a 1/2 vaccination certificate with technical expiry date less than 28 days in the future
4. Text information is displayed
5. Exit the app and use Android to Close all apps
6. Restart the app
7. Note pop-up:<br>"**Check the validity of your certificates**<br>If you can renew this certificate in the app, you will receive a notification. You can find more information about replacing expired certificates in our FAQs."
8. Tap "OK"
9. Note the previous pop-up repeats:<br>"**Check the validity of your certificates**<br>If you can renew this certificate in the app, you will receive a notification. You can find more information about replacing expired certificates in our FAQs." 

## Expected behaviour

The app should only display the notification "**Check the validity of your certificates**" once in the above scenario.

**Comment by alexcimander** [comment]
Hey everyone! Update: We are currently working on a HF 1.26.1 which will take care of:

**1.) Wrong reason for Re-Issue mentioned (Android only)**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/211
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/210

**2.) Misleading Text for (about to be expired) DCCs in DCC-Details**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/212
https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/194

**3.) Misleading Text within renewal process**
https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/192

**4.) "there are news" but not "there is news" within notification**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/217  

**5.) In Investigation: "No renewal offered for 1/2 vaccination if it is the only vaccination**  

-------------------------------------------------------

the bugs 

6.) Notification about expiry is played out twice (Android only)
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/214

7.) Re-Open of the App required (Android only) is not stated by the info text
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/213

are currently in investigation - we will provide a fix asap but these two are not expected to be fixed within the HF.


Thank you all for the patience and supporting discussions! 🦸

**Comment by MikeMcC399** [comment]
6.) Notification about expiry is played out twice (Android only)
- https://github.com/Digitaler-Impfnachweis/covpass-android/issues/214

**Comment by pucherd** [comment]
Hello @MikeMcC399, this bug will be fixed in release 1.28

**Comment by MikeMcC399** [comment]
This issue is confirmed fixed in CovPass 1.28.0.
