### ISSUE TITLE
Misleading display "You can easily replace the certificate" for 1/2 vaccination certificate if 2/2 also installed

### ISSUE THREAD

**Issue by MikeMcC399** [Digitaler-Impfnachweis/covpass-android#215]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)<br>~~The FAQ are not yet adjusted to cover the functionality in CovPass 1.26.0~~
* [ ] Bug is not already reported in another issue
The problem is also described in https://github.com/Digitaler-Impfnachweis/covpass-android/issues/212. This issue is a duplicate, however it gives detailed repo steps

## Technical details

- OS version: Android 12
- App version: 1.26.0

## Describe the bug

When CovPass holds a 1/2 vaccination certificate with technical expiry date less than 28 days in the future and a 2/2 vaccination certificate, which is not expiring, is also scanned in, the information displayed for the 1/2 certificates says:

"You can easily replace the certificate in the CovPass app by using the renewal function in the overview of your certificates or by scanning a newly issued certificate" 

although in fact there is no immediate way to renew the certificate, since the button "Renew vaccination certificate" is not displayed.

## Steps to reproduce the issue

1. Install CovPass
2. Go through onboarding
3. Scan a 1/2 vaccination certificate with technical expiry date less than 28 days in the future
4. Tap on back arrow
5. Tap on "+" and scan a 2/2 vaccination certificate which is valid for more than 28 days
6. Exit the app and use Android to Close all apps (due to other bug https://github.com/Digitaler-Impfnachweis/covpass-android/issues/213)
7. Restart the app
8. Tap "OK" on message "There are news about your certificates"
9. Tap "Display certificates"
10. Tap "Manage certificates"
11. Scroll down to "Vaccination certificate, Vaccine dose 1 of 2, Vaccinated on dd mmm yyyy, **Certificate expires soon**" and tap on this
13. Note information:<br>"**Certificate expires on dd mmm yyy at hh:mm**<br>You can easily renew the certificate in the CovPass app. To do so, use the renewal function in the overview of your certificates or scan a newly issued certificate."
14. Tap back arrow
15. Note there is no button "Renew vaccination certificate" available
    

## Expected behaviour

The app should only display the text "You can easily replace the certificate in the CovPass app by using the renewal function in the overview of your certificates or by scanning a newly issued certificate" if the button "Renew vaccination certificate" is also available.

If it is not intended for a 1/2 vaccination certificate to be renewed if a valid 2/2 vaccination certificate is also scanned in, then the above text message should not be displayed.

**Comment by alexcimander** [comment]
Hi @MikeMcC399,

thank you for reporting this bug - we are working on a fix!

**Comment by alexcimander** [comment]
Hey everyone! Update: We are currently working on a HF 1.26.1 which will take care of:

**1.) Wrong reason for Re-Issue mentioned (Android only)**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/211
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/210

**2.) Misleading Text for (about to be expired) DCCs in DCC-Details**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/212
https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/194

**3.) Misleading Text within renewal process**
https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/192

**4.) "there are news" but not "there is news" within notification**
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/217  

**5.) In Investigation: "No renewal offered for 1/2 vaccination if it is the only vaccination**  

-------------------------------------------------------

the bugs 

6.) Notification about expiry is played out twice (Android only)
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/214

7.) Re-Open of the App required (Android only) is not stated by the info text
https://github.com/Digitaler-Impfnachweis/covpass-android/issues/213

are currently in investigation - we will provide a fix asap but these two are not expected to be fixed within the HF.


Thank you all for the patience and supporting discussions! 🦸

**Comment by MikeMcC399** [comment]
2.) Misleading Text for (about to be expired) DCCs in DCC-Details
- https://github.com/Digitaler-Impfnachweis/covpass-android/issues/212
- https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/194

---

- https://github.com/Digitaler-Impfnachweis/covpass-android/issues/212 and this issue #215 are basically the same, so the fix would be covered in 2).
