### ISSUE TITLE
Enable screenshots (Follow up to #62)

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-android#216]
## Avoid duplicates
* [ ] This enhancement request has not already been raised before - This is a follow up to #62

## Current Implementation
CovPass does not allow to take screenshots. Attempting to take a screenshot results in an error message from the OS. 

## Suggested Enhancement
Allow taking screenshots of CovPass.

## Expected Benefits
Easier for debugging purposes and more. Also, the screenshot restriction can easily be bypassed, without root or anything, by saying "OK Google, take a screenshot". This screenshot protection does not add any security to the app, as there is literally a certificate export feature in the app. Why would you restrict a user to store a screenshot of the QR code of the certificate, but allow to export the whole certificate? You see, this makes no sense. 
If you have any points where the screenshot restriction actually adds security, please share them in this issue.

**Comment by Matt-17** [comment]
What happened? This feature worked and it was great - even I did not need it for some months. Now it's gone when I need it again? As in #53 it was enabled wihtout any further explanation. Now it's disabled again - without any note? At least explain the reasons.

**Comment by Ein-Tim** [comment]
@Matt-17 I do not remember a time where CovPass allowed to take screenshots.

**Comment by Matt-17** [comment]
@Ein-Tim I still have screenshots from October 2021 from this app. Maybe it was not for long, as I could use those for some time and did not recheck this feature once a month ;-) But I was pretty irritated today, when I could not take a new screenshot.

**Comment by MikeMcC399** [comment]
The history of https://github.com/Digitaler-Impfnachweis/covpass-android/blob/main/common-app/src/main/java/de/rki/covpass/commonapp/BaseActivity.kt shows how screenshots have been disabled, enabled and disabled.

https://github.com/Digitaler-Impfnachweis/covpass-android/commit/2a8cf01f65cdbf9afa982b30fdff1f45a3a86ac3 was the last disable it seems.

**Comment by Ein-Tim** [comment]
Has anyone actually assessed this issue in the last year? cc @staeffy

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
