### ISSUE TITLE
Covpass Check does not make use of dedicated barcode scanning imagers (e.g. Zebra TC25)

### ISSUE THREAD

**Issue by stkdiretto** [Digitaler-Impfnachweis/covpass-android#22]
Hey everybody,

in order to facilitate fast scanning, I would like to use dedicated (2D) barcode scanning android devices such as the Zebra TC25. Unfortunately, Covpass Check only offers me to use the (rather crappy) smartphone camera for scanning. 

Is there any way to incorporate Zebra's Scanner SDK and let the user choose between imagers?

**Comment by pc-coholic** [comment]
@stkdiretto Since my PR was declined for now, you might be happy to hear that the next release of your favourite ticket scanning app will integrate covpass-validation. Perhaps this will be good enough for your usecase?

**Comment by stkdiretto** [comment]
Some fans of my favorite ticket scanning app have already patched the app on my Zebra device, so I'm happy for my personal use case right now.

Bummer though that this won't be integrated into the official app. From my understanding, fast mass scanning would be _the_ use case for such a validation app, as opposed to the so-so integrated cameras.

**Comment by wkornewald** [comment]
It won't be integrated yet at least. The situation might change in the future.
