### ISSUE TITLE
Extra whitespace in EU printout

### ISSUE THREAD

**Issue by MikeMcC399** [Digitaler-Impfnachweis/covpass-android#222]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A52 5G SM-A526B/DS
- Android version: 12
- App version: 1.27.0

## Describe the bug

The EU printout contains extraneous whitespace:

- between the introductory words of each paragraph and the following text
- between the first part of a hyphenated word and the hyphen
- before a full-stop at the end of a sentence

See screenshot:
![Certificate infos](https://user-images.githubusercontent.com/66998419/179199150-fc804b3b-0ace-4091-b7b1-167595538588.jpg)

## Steps to reproduce the issue

In CovPass App

1. Tap "+" to scan a 1/2 vaccination certificate
2. Scroll down and tap on certificate
3. Scroll down and tap on "Create EU printout", tap "Next"
4. Tap Drive symbol
5. Tap Save

On Desktop

6. Open Drive https://drive.google.com/drive/my-drive
7. Open saved PDF with Adobe Acrobat DC
8. Note formatting gaps in information section

## Expected behaviour

No extra white space should be shown.

## Possible Fix

Review the certificate formatting.

**Comment by dsarkar** [comment]
Issue is monitored in Internal Tracking ID: [EXPOSUREAPP-13635](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13635)

**Comment by MikeMcC399** [comment]
- Also reported for Corona-Warn-App under https://github.com/corona-warn-app/cwa-app-android/issues/5356

**Comment by dsarkar** [comment]
corresponding CWA issue handled in Internal Tracking ID: [EXPOSUREAPP-13635](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13635)

**Comment by MikeMcC399** [comment]
@dsarkar 

This is a link to https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13635. Are you granting access to this link? If not, then probably it should be removed, since this is not an SAP-owned repository here.

**Comment by MikeMcC399** [comment]
@pucherd 

Has your team had a chance to look at this issue? If yes, is there any conclusion about whether the issue is in the CovPass Android app or in the template (or maybe both)?

**Comment by MikeMcC399** [comment]
This issue has been fixed in the Corona-Warn-App version 2.26.

Are there plans to fix it in CovPass?
