### ISSUE TITLE
[Question] Endpoints for updates on regulations

### ISSUE THREAD

**Issue by MarcoBuess** [Digitaler-Impfnachweis/covpass-android#229]
We're running behind a corp-firewall and would need the remote endpoints to which the app connects to update the latest regulations, so that we can setup proper firewall exceptions.

Thanks in advance.

**Comment by pucherd** [comment]
Hello @MarcoBuess,
These endpoints are used:
de.dscg.ubirch.com - Trust service host
de.crl.dscg.ubirch.com - Revocation list service
api.reissue.ubirch.com - Reissue service
distribution.dcc-rules.de - Business Rules (Check validity feature)

**Comment by MarcoBuess** [comment]
tyvm ❤️
