### ISSUE TITLE
Missing 1.30 release

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-android#230]
Version 1.30 of both CovPass as well as CovPassCheck are in the PlayStore, however, there is no GitHub release here and the source code is also not available. Please create a GitHub release and publish the source code.

**Comment by pucherd** [comment]
Hello @Ein-Tim, the version 1.30 was release on time 5 days ago. Please have a look here:
https://github.com/Digitaler-Impfnachweis/covpass-android/tree/release/1.30.x

**Comment by Ein-Tim** [comment]
@pucherd 

Ah, thanks. I somehow didn't see this!
