### ISSUE TITLE
New rules for "Fully vaccinated" in Germany since October 1st, 2022 seem not implemented

### ISSUE THREAD

**Issue by jkrwdf** [Digitaler-Impfnachweis/covpass-android#235]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 6
- OS version: 13
- App version: 1.32.0

## Describe the bug

According to [https://www.bundesregierung.de/breg-de/themen/corona-informationen-impfung/coronavirus-impfung-faq-1788988](https://www.bundesregierung.de/breg-de/themen/corona-informationen-impfung/coronavirus-impfung-faq-1788988), since October 1st, 2022 three vaccinations are necessary for the "fully vaccinated" status. 

This is not implemented in CovPassCheck. Even with fully updated rule sets, I can successfully scan a 2/2 certificate (mRNA) from July 2021 and get a "Certificate valid, green checkmark". 

## Steps to reproduce the issue

See above.

## Expected behaviour

Not green.

**Comment by Ein-Tim** [comment]
Confirm same behavior on iOS.

**Comment by MikeMcC399** [comment]
@jkrwdf 

The UI of CovPassCheck has changed and when I use 1.34.1 I get the mask rules. At the moment I'm getting "No present rules in Bavaria" 

It seems that this issue is now obsolete, since the rules applied in the app have completely changed.

**Comment by MikeMcC399** [comment]
@jkrwdf 

I'm seeing a tab "Vaccination status" in CovPassCheck app.

2/2 vaccination does not show full vaccination status.

It seems that your request has been implemented!

**Comment by jkrwdf** [comment]
I get this when scanning the 2/2:

![image](https://user-images.githubusercontent.com/5329491/203510397-eff015e1-4024-43f8-9600-3aa410acb6d0.png)

Scanning the 3/3 gives green. 

Issue no longer present. Closing.
