### ISSUE TITLE
CovPassCheck 1.34.1 crashes when accessing the camera

### ISSUE THREAD

**Issue by capncrunch** [Digitaler-Impfnachweis/covpass-android#236]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name:Android
- OS version:8.0
- App version:1.34.1

## Describe the bug

The current version of CovPassCheck crashes when accessing the camera, i.e. immediately after touching the Scan Now button. This happens before requesting permission to use the camera but happens regardless of whether the permission has been granted or not. The previously released version in the Play Store did not have this issue.

## Steps to reproduce the issue

1. Install the app (doesn't matter if update from the previously released version or new install) on Android 8.0.
2. Touch the Scan Now button

## Expected behaviour

I expect the camera preview window to appear.

**Comment by pucherd** [comment]
Hello @capncrunch, thank you for reporting it. Can you please provide us more information about the device where the app is crashing (manufacturer, model, ...)? Thank you

**Comment by capncrunch** [comment]
It's a Sony Experia X Compact (F5321) running the Sony Android build 8.0.0, build number 34.4.A.2.118.

**Comment by capncrunch** [comment]
I've now updated CovPass Check to 1.36.0 through the Play Store. The issue still persists, tapping the Scan button crashes the app.

**Comment by capncrunch** [comment]
I've now gone back to 1.30.0 using F-Droid and it does not crash when accessing the camera. I've then upgraded to 1.32.0, again using F-Droid, and it crashes again.

So it appears something has changed in how the camera is accessed between those two versions. Maybe that's helpful in pinpointing the reason.

I'm also happy to help debugging this issue by running a debug version on the affected phone.

**Comment by pucherd** [comment]
Hello @capncrunch, thank you for the offer to help debugging this issue. 
Can you please use this debug version to provide us some logs?
Thank you :) 

[covpasscheckdemo-1.36.0-1.605.3-debug.apk.zip](https://github.com/Digitaler-Impfnachweis/covpass-android/files/10070942/covpasscheckdemo-1.36.0-1.605.3-debug.apk.zip)

**Comment by capncrunch** [comment]
OK, I have installed the debug version and confirmed it, too, crashes when accessing the camera.
Where do I find the logs you need?

Interestingly, the CovPass app works fine on the same phone and can access the camera and scan certificates without crashing.

**Comment by pucherd** [comment]
@capncrunch One option would be to use Android Studio and get the logs from Logcat. Are you familiar with it?

**Comment by capncrunch** [comment]
No, sorry, I'm not an Android developer. I can follow instructions, though. :-)

**Comment by capncrunch** [comment]
I've today installed CovPassCheck version 1.37.0 and can confirm the crash is gone and the app works as intended.
