### ISSUE TITLE
Missing space quoting IfSG § 22a

### ISSUE THREAD

**Issue by MikeMcC399** [Digitaler-Impfnachweis/covpass-android#237]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Pixel 3a emulator
- OS version: Android 13
- App version: 1.36.0

## Describe the bug

There is a space missing when referring to the legal text  "IfSG § 22a".

## Steps to reproduce the issue 

1. Install CovPassCheck app
2. Complete onboarding
3. Click on "Vaccination status"

Note text "Vaccination status according to IfSG §22a"

![IfSG](https://user-images.githubusercontent.com/66998419/203299584-24e27546-1dd6-4dc6-83b3-d47f4759faab.jpg)

## Expected behaviour

There should be a space between "§" and "22a"

## Possible Fix

Add a non-breaking space so that the legal quotation appears as "IfSG §&nbsp;22a"

## References

- Gesetz zur Verhütung und Bekämpfung von Infektionskrankheiten beim Menschen (Infektionsschutzgesetz - IfSG)<br>[§ 22a Impf-, Genesenen und Testnachweis bei COVID-19; COVID-19-Zertifikate; Verordnungsermächtigung](http://www.gesetze-im-internet.de/ifsg/__22a.html)

**Comment by Staeffy** [comment]
@MikeMcC399 thanks for your feedback! We will fix that within the next release

**Comment by Ein-Tim** [comment]
- The fix for this is https://github.com/Digitaler-Impfnachweis/covpass-apps-i18n/pull/299

**Comment by MikeMcC399** [comment]
Although a space has been inserted in 1.37.0, it is not a non-breaking space, so during first use of vaccination status `§ 22a` appears split across two lines. This is not optimal.

![image](https://user-images.githubusercontent.com/66998419/205883707-cd2360c8-cb7d-471a-a6be-06c5accf8115.png)

**Comment by MikeMcC399** [comment]
I will close this issue, as the space has been inserted. @Staeffy You might want to consider converting the space into a non-breaking space `&nbsp;`.
