### ISSUE TITLE
Message says certificate can be renewed even if expiry more than 90 days ago

### ISSUE THREAD

**Issue by MikeMcC399** [Digitaler-Impfnachweis/covpass-android#238]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5 (2017)
- OS version: Android 8.0.0
- App version: CovPass 1.36.0

## Describe the bug

If the only certificate stored has expired more than 90 days ago then the information displayed that the certificate can be renewed is incorrect.

## Steps to reproduce the issue

1. Delete any existing stored certificates
2. Press "+" and "Add certificate" to scan a vaccination certificate which expired more than 90 days ago.
3. Scroll down to "Certificate expired" and note the text:<br>" ... You can conveniently renew this certificate in the CovPass app. ... To do so, use the renewal function in the overview of your certificates ..." 
![certificate expired](https://user-images.githubusercontent.com/66998419/203513925-169142dd-f665-4577-a372-633e6ff5fbb6.jpg)

4. Look for some button to renew the certificate - there is none!

## Expected behaviour

CovPass should only say that a certificate can be renewed if this is possible. 

## Possible Fix

- Change the text to specify the 90 day limitation for renewal or
- Change the logic so that the app only says that a certificate can be renewed if this is actually possible

**Comment by Staeffy** [comment]
Thanks for your feedback, we are currently refining the process flow for renewals and will take that into account!

**Comment by Ein-Tim** [comment]
@Staeffy 

Please also make sure that iOS gets the same fix!

**Comment by Ein-Tim** [comment]
According to https://github.com/Digitaler-Impfnachweis/covpass-android/releases/tag/v-1.675.0, this issue should be fixed with version 1.39. Can you cross-check @MikeMcC399?

**Comment by MikeMcC399** [comment]
This issue is resolved.

The text now advises:

"If you still need the certificate, please visit a pharmacy to have a new certificate issued.
