### ISSUE TITLE
Link to https://reopen.europa.eu badly formatted and unclickable

### ISSUE THREAD

**Issue by MikeMcC399** [Digitaler-Impfnachweis/covpass-android#239]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Pixel 3a emulator
- OS version: Android 13
- App version: CovPass 1.36.0

This is a regression from CovPass 1.34.1

## Describe the bug

If the result of "Check validity" is "Not possible to validate" then the message shown together with the certificate details includes a link target `#https://reopen.europa.eu::https://reopen.europa.eu#` which is not clickable and includes additional characters "#" and "::".

![reopen link](https://user-images.githubusercontent.com/66998419/204140629-96a0e119-7708-49bd-8207-db813621d6b3.jpg)

## Steps to reproduce the issue

1. Scan 1/2 valid vaccination certificate
2. Tap "Check validity"
3. Select Country "Austria"
4. Tap right-arrow at the right of "Not possible to validate"
5. Note the message "Please check at `#https://reopen.europa.eu::https://reopen.europa.eu#` whether the certificate is valid for entry into the selected country."

## Expected behaviour

The message should appear as "Please check at https://reopen.europa.eu whether the certificate is valid for entry into the selected country." and the link to https://reopen.europa.eu should be clickable.

**Comment by pucherd** [comment]
Hello @MikeMcC399, Thank you for reporting it. Will be fixed in one of our next releases.

**Comment by pucherd** [comment]
@MikeMcC399 Thank you for the confirmation. Yes, the release notes will be published soon.
