### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by tb-tw** [Digitaler-Impfnachweis/covpass-android#24]
opening CovPass on Android 11 only yields a blank screen, before and after 1 July patch. Android also complains that the app doesn't respond. Internet is working fine, Play Store indicates that I've installed the latest version from 1 July.
![Screenshot_20210703-103316_CovPass](https://user-images.githubusercontent.com/86870328/124348424-2684ce00-dbea-11eb-83f1-b845bbfdefbb.jpg)

**Comment by wkornewald** [comment]
Could you please provide some details about the device you're testing with? At least on our Android 11 devices we didn't hit this bug, so maybe it's device-specific.

**Comment by tb-tw** [comment]
Of course! please find attached - does this help? The problem persists. I also notice that opening up CovPass slows down the whole phone, even switching to another app takes a long time...Fingers crossed that you can find the problem! :)On 05/07/2021, 12:00 Waldemar Kornewald ***@***.***> wrote:

   
  Could you please provide some details about the device you're testing with? At least on our Android 11 devices we didn't hit this bug, so maybe it's device-specific.

**Comment by wkornewald** [comment]
I think uploading the attachment failed. Did you reply via mail or upload via the GitHub website?

**Comment by tb-tw** [comment]
![Screenshot_20210705-130411_Settings](https://user-images.githubusercontent.com/86870328/124521367-89938200-ddef-11eb-84c2-60761c595a8f.jpg)
![Screenshot_20210705-130357_Settings](https://user-images.githubusercontent.com/86870328/124521370-8a2c1880-ddef-11eb-95b5-12aba1e3024c.jpg)
Indeed, I had just replied to the email directly - apparently GitHub then deletes attached pictures... Here you go, is this helpful?

**Comment by wkornewald** [comment]
Yes, definitely, that's a good starting point for the bug hunt. Thanks!

**Comment by wkornewald** [comment]
Did you modify the OS (e.g. rooting / custom ROM / etc.) in any way? Or maybe override some app permissions? Or do you have some anti-virus software? Anything "unusual" that can interact with the CovPass app?

**Comment by wkornewald** [comment]
Are any other apps on your phone showing similar behavior? What if you uninstall and reinstall CovPass?

**Comment by wkornewald** [comment]
And adding yet more questions, did you change something in the developer options? Like "Don't keep activites", disallowing background processes or disabling animations or anything else?

**Comment by mindbreaker** [comment]
Same problem with 
Android: 10
Version: 1.16.4

**Comment by tb-tw** [comment]
Thank you for your follow-up, Waldemar - the only thing that changed on my phone since the initial successful installation of CovPass was the Samsung software update on 1 July. I have been running Norton 360 all along and otherwise haven't changed any developer options or modified the OS in any way. I just have deleted and reinstalled CovPass and it seems to be working like before - so the good news is that there doesn't seem to be a fatal flaw. It's nevertheless very disturbing that an app presumably doing the "easy" job of displaying a QR code isn't reliable - as being able to prove one's vaccine, malfunctioning could be fatal - imagine you miss a longhaul flight and forfeit an expensive ticket or miss a major event because you relied on the app to prove your vaccination status and because all you can do is produce a blank screen, you are denied entry/boarding...

**Comment by wkornewald** [comment]
Since a reinstall of the app fixes it, this at least hints at a certain part of the code that might have a bug (maybe some edge case during data migration). We'll investigate this. Thanks for the extra info.

As a side-note, I'm not sure if it's a good idea to use anti-virus software beyond what's already built into the OS (no matter if Android, Windows etc.). Ironically, that kind of software often contains pretty fundamental security issues and makes you even more vulnerable to attackers. Not only that, some of these companies sell your data:

* https://news.ycombinator.com/item?id=22159385
* https://news.ycombinator.com/item?id=13489100
* https://news.ycombinator.com/item?id=11710620
* https://news.ycombinator.com/item?id=14644742
* https://news.ycombinator.com/item?id=19409618
* https://news.ycombinator.com/item?id=10877396
* and so on... the list is long

**Comment by tb-tw** [comment]
Thank you - I'm indeed thinking more and more of uninstalling my AV software due to the problems increasingly found with them (although I always bought the for-pay version because it was clear to me that there cannot be anything "free" - but I wouldn't be surprised if these guys happily charge me AND sell my data, too... ;) ), so I just gave Norton 360 on my mobile the boot... I guess I am hesitating to let go of AV on my Windows machine because I twice was alerted of a genuine virus by it - plus I am using Firefox in order to reign in Google's snooping and protect myself better from ads, and that seems to come with its own security risks...

**Comment by jleufgen** [comment]
Since the error can no longer be reproduced by anyone, we assume that it has been fixed.
