### ISSUE TITLE
Navigating to to last certificate using the right arrow icon is impossible

### ISSUE THREAD

**Issue by p-schneider** [Digitaler-Impfnachweis/covpass-android#241]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Describe the bug

I have 1 Person with 2 Certificates relevant for scanning, so the pager shows 2 Certificates for my Person.
I can't navigate to the 2nd=last certificate using the right arrow button.
Swyping works, clicking the 2nd dot also works.

## Steps to reproduce the issue

1. Have **only 1 Person** but with **at least 2 relevant certificates**. (e.g. 2nd Vaccination + Recovery)
2. Click/Touch on the certificate on the main screen.
3. Click/Touch on the Right Arrow Button at the bottom.
4. It will not work. (Clicking the 2nd dot directly next to the arrow button would work, also swyping to the 2nd page would work.)

## Expected behaviour
It should navigate to the 2nd / last page.

## Possible Fix
Replace 
`val certSize = covpassDeps.certRepository.certs.value.certificates.size`
with
`val certSize = fragmentStateAdapter.itemCount`
in [CertificateSwitcherFragment.kt line 144](https://github.com/Digitaler-Impfnachweis/covpass-android/blob/main/common-app-covpass/src/main/java/de/rki/covpass/app/certificateswitcher/CertificateSwitcherFragment.kt#L144)

**Comment by pucherd** [comment]
Hello @p-schneider, thank you for reporting this bug. Have you tested it with version 1.38?

**Comment by p-schneider** [comment]
I thought I had, but I guess I didn't properly.
It's working in 1.38.0.
(I'm looking forward seeing the commits for 1.38.0 on GitHub.)

**Comment by p-schneider** [comment]
@pucherd Sorry for my confusion, I thought I had tested on 1.38.0.
(I knew I was debugging it on 1.37.0 because that's the source code I see, but I must have confused the app from the play store with my locally compiled build when confirming / testing the bug for 1.38.0.)
