### ISSUE TITLE
Release notes for CovPass 1.38

### ISSUE THREAD

**Issue by MikeMcC399** [Digitaler-Impfnachweis/covpass-android#242]
Happy New Year!

Please publish release notes for CovPass / CovPass Check 1.38! 

The last release documented in https://github.com/Digitaler-Impfnachweis/covpass-android/releases is [v.1.37.0](https://github.com/Digitaler-Impfnachweis/covpass-android/releases/tag/v-1.629.2).

**Comment by pucherd** [comment]
Hello @MikeMcC399,

Happy New Year 2023.
Thank you for mentioning it, now it should be updated.
