### ISSUE TITLE
Missing 1.40 GitHub release & source code

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-android#244]
Version 1.40 of CovPass & CovPassCheck is in the Play Store, but here on GitHub I can't find the corresponding GitHub release. Please create a GitHub release and also publish the source code.

**Comment by pucherd** [comment]
Hello @Ein-Tim, the source code is already published and can be find here:
https://github.com/Digitaler-Impfnachweis/covpass-android/tree/release/1.40.x

The release notes creation is in progress.

**Comment by pucherd** [comment]
Hi @Ein-Tim, release notes available now:
https://github.com/Digitaler-Impfnachweis/covpass-android/releases/tag/v-1.686.0

Sorry for the delay.
