### ISSUE TITLE
(Question) CoVPass Check shows test time in UTC instead of UTC +2

### ISSUE THREAD

**Issue by codejus** [Digitaler-Impfnachweis/covpass-android#27]
Good Sunday all,

for my last rapid antigen test via CWA I've generated a EU DCC via the app. Out of curiosity I've checked it with a other device via  CoVPass Check.

The CWA EU DCC was shown as valid, but the shown time for the test was converted into UTC  and so shown 2 hours earlier that the real test time. (17:35 instead of 19:35 was shown).

Is this conversation of the test time from UTC+2 (MESZ) into UTC intended or not?

Thanks!

**Comment by jkrwdf** [comment]
Scanning the same antigen test certificate with the Android version of CovPass Check and the iOS Version, the different is obvious: 

![image](https://user-images.githubusercontent.com/5329491/124514646-d40c0300-dddd-11eb-8674-f6d9446b452c.png)

Even the display format in iOS is not quite compatible with the intended target audience of the application, but at least it shows the wall-clock time of the devices timezone.

**Comment by jleufgen** [comment]
Hello, I would guess that it is outdated because we no longer display the time zone. Best regards
