### ISSUE TITLE
Validity check of root certificates could throw exceptions when root cerificates are expired

### ISSUE THREAD

**Issue by e7p** [Digitaler-Impfnachweis/covpass-android#29]
The validity check which is run on the specified root certificates can throw `CertificateExpiredException` and `CertificateNotYetValidException`, both inherit from `javax.security.cert.CertificateException`, whenever a root certificate becomes invalid. However, as far as I can tell, these Exceptions are not yet handled in the function itself and the function doesn't specifically document that it could throw any of these Exceptions.

As a second thought, maybe the signatures of the single root certificates might also be verified, but at least the whole dsc-list is signed with the dsc-list-signing-key which should be sufficient from a security point of view.

As a note, the call I am referencing to is: https://github.com/Digitaler-Impfnachweis/covpass-android/blob/3b95b05221e8108ea8cc3cb8e4268a5c1af124a6/covpass-sdk/src/main/java/de/rki/covpass/sdk/cert/CertValidator.kt#L104

**Comment by wkornewald** [comment]
We should be fine in this case because `CertificateException` inherits from `GeneralSecurityException` and we catch that to make sure any kind of javax.security exception is handled. Having more eyes on security critical code is always good, so we appreciate any reviews - thanks for having a look and please don't hesitate to report any other potential issues you find in the code.

And please reopen in case I've overlooked something.

**Comment by e7p** [comment]
Thanks for your kind answer. However, reading the Java documentation shows not that `CertificateException` inherits from `GeneralSecurityException`. In fact, it directly inherits from `Exception`. So maybe have a look again? I'm a bit unsure as Java / Kotlin is not my daily driver, but maybe it got somehow overlooked.

**Comment by wkornewald** [comment]
At least here it lists GeneralSecurityException: https://docs.oracle.com/javase/8/docs/api/java/security/cert/CertificateException.html

**Comment by e7p** [comment]
Alright, my mistake. I somehow looked at `javax.security` not `java.security`. Thanks again!
