### ISSUE TITLE
Expiration date of the certificate

### ISSUE THREAD

**Issue by handgh** [Digitaler-Impfnachweis/covpass-android#3]
I believe it would be nice to show in the App the date till which the certificate will be valid. I guess that the data necessary to do that is already in the code as it is needed to decide whether the certificate is still valid.

**Comment by wkornewald** [comment]
Thanks for your suggestion. That would indeed be nice and chances are good that we'll add this in some future release.

**Comment by TimLinsenmayer** [comment]
Maybe it would be useful to reuse the little text below the QR code for this - it could warn you a month prior to expiration to take action. (Or just a pop out dialogue).

**Comment by jleufgen** [comment]
Hi all, thanks for the feedback! It will be scheduled in one of the next sprints. Best regards!
