### ISSUE TITLE
Add app metadata folder for possible F-Droid release

### ISSUE THREAD

**Issue by mythsunwind** [Digitaler-Impfnachweis/covpass-android#30]
I opened a merge request for app inclusion into F-Droid here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9360

One open task is the app metadata (summary/description/images/changelog/etc) in a Fastlane or Triple-T folder structure.

The folder structures are described there for [Fastlane](https://gitlab.com/-/snippets/1895688) and [Triple-T](https://gitlab.com/-/snippets/1901490)

**Comment by jugendhacker** [comment]
This is kind of a follow up to #2, if RKI/IBM supports inclusion, then maybe Fastlane metadata for description, screenshots, etc. could be established.

**Comment by jleufgen** [comment]
Hello, it was decided against the publication, maintenance and community support of an f-droid version. Best regards
