### ISSUE TITLE
Bump version code on release

### ISSUE THREAD

**Issue by jugendhacker** [Digitaler-Impfnachweis/covpass-android#31]
Following up to #2 it seems like every current version of Covpass uses the `versionCode` 2, this is bad because it's the way how F-Droid and even Android in general determines what's a newer version of the app and what's not. In the specific case of F-Droid users won't get notified about updates if the version code stays the same. Some my question is why isn't the version code bumped on every release? And would IBM be willing to bump it with future releases?

**Comment by wkornewald** [comment]
The version is bumped automatically via Jenkins. We never manage this manually. Is this causing any difficulties?

**Comment by jugendhacker** [comment]
Seems like you only bump the versionName (e.g. 1.38.0 for the latest release) but not the versionCode, which appears to be hard coded [here](https://github.com/Digitaler-Impfnachweis/covpass-android/blob/main/gradle/common/android-app.gradle#L46). At least I always get versionCode 2 if I build locally. Independent of what version I'm actually building.

**Comment by wkornewald** [comment]
As you can see in the code you linked, the versionCode is fetched from the generatedProps, so we do bump it via Jenkins if you take a look at our Jenkinsfile.

**Comment by jugendhacker** [comment]
Okay so F-Droid has to do it in a similar way, thanks for the info.
