### ISSUE TITLE
Feature Request: App Lock (Android) per Face Unlock, Fingerprint or pattern

### ISSUE THREAD

**Issue by Dtrieb** [Digitaler-Impfnachweis/covpass-android#33]
It would give a bit more of security if the app can only opens if you have the right Face Unlock, Fingerprint or pattern.

Discussion here:
https://github.com/Digitaler-Impfnachweis/covpass-android/discussions/34#discussion-3453081

**Comment by jleufgen** [comment]
Thank's for your hint. However the specified safety measures are already ensured.
