### ISSUE TITLE
Certificate grouping should regard only standardized name

### ISSUE THREAD

**Issue by patlkli** [Digitaler-Impfnachweis/covpass-android#36]
I have the unfortunate situation that my pharmacy seems to have entered both my first and last name with extra spaces at the end.

I don't know if the certificate creation process had or still has an input sanitization issue.
In any case, I know have a certificate which has properly standardized `"fnt"` and `"gnt"` fields, but contains trailing whitespaces in both `"fn"` and `"gn"` fields.

CWA manages to still group the certificates by only using date of birth and the standardized names for identifying a person (see [here](https://github.com/corona-warn-app/cwa-app-android/blob/c87daaa408abdcb0296fbc1b1a4933918746b2bf/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/certificate/Dcc.kt#L44)).

CovPass however seems to group on the whole name structure including `"fn"` and `"gn"`, which should be redundant.

**Comment by jleufgen** [comment]
Done with the last releases :)
