### ISSUE TITLE
Covpass and LineageOS: not OK

### ISSUE THREAD

**Issue by Spielmops** [Digitaler-Impfnachweis/covpass-android#39]
The Covpass app does not work with LineageOS. When the QR code is scanned, I get the following output: "Covid certificate does not contain a valid signature". The Corona warning app has no problem with that.

Tried it again with clean app and clean cache with no success.

LineageOS 18.1 up to date
Covpass app 1.28.3

Spielmops

**Comment by Ein-Tim** [comment]
@Spielmops 

Are you sure that the Certificate has a valid signature? 

The Corona-Warn-App does not check the signature, so you can also import certificates without a valid signature in the CWA. See https://github.com/corona-warn-app/cwa-documentation/issues/634

**Comment by Spielmops** [comment]
The scanned document is a digital vaccination certificate from the pharmacy. If that doesn't have a valid certificate then ... How can I find out?

**Comment by Ein-Tim** [comment]
@Spielmops 

Scan it with the CovPassCheck App.

**Comment by Spielmops** [comment]
This is the solution to the problem:
the Covpass app says it works without an internet connection. That's why I started the app without a connection to the internet. But the app needs a connection once when it starts, presumably to load a list of the certificate issuers. After I started the app as new installed with an internet connection, the QR codes are accepted.

Spielmops
