### ISSUE TITLE
Add desugaring to apps using covpass-sdk (or at least a note about it to the usage instructions)

### ISSUE THREAD

**Issue by pc-coholic** [Digitaler-Impfnachweis/covpass-android#40]
`covpass-sdk` requires as of now a minimum Android API level of 23.

This is despite the fact that `java.timeInstant` is used, which would normally incur a minimum API level of 26.

When we built our app that includes to `covpass-sdk` against API-level 23, the app would work just fine on most devices - however some devices did crash for a lack of `java.timeInstant`. The stacktrace would read something like this:
```
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;
        at de.rki.covpass.sdk.dependencies.CoreKt.<clinit>(Core.kt:31)
        at de.rki.covpass.sdk.dependencies.CoreKt.getDefaultCbor(Core.kt:23)
        at de.rki.covpass.sdk.dependencies.SdkDependencies.<init>(SdkDependencies.kt:73)
        at eu.pretix.libpretixui.android.covid.DGC$init$1.<init>(DGC.kt:130)
        at eu.pretix.libpretixui.android.covid.DGC.init(DGC.kt:130)
        at eu.pretix.pretixscan.droid.PretixScan.onCreate(PretixScan.kt:86)
```

In covpass' `android-common.gradle` the workaround for this issue is already included - adding Desugaring.

Once we added it to our apps very own gradle-file, the the crashes are gone (example: https://github.com/pretix/pretixscan-android/commit/6bd8256f89edf20a4a109c84a6c5df437166b83f).

Ideally, I feel like the desugaring should be applied from the `covpass-sdk` library to the projects that include it. Since I'm however not fluent in gradle, I do not know if that is possible.

In case it isn't, perhaps a cautionary note in the usage instructions of the `covpass-sdk` might be a good alternative.

This issue is probably nothing that a seasoned programmer couldn't fix by themselves if encountered (the solution is literally in the first StackOverflow-post encountered when searching for this issue) - but I'm posting it here to as a service to fellow developers ;-)

**Comment by wkornewald** [comment]
We'll add documentation to our README soon. Closing this in advance.
