### ISSUE TITLE
Stock Android only? Make this work on LineageOS.

### ISSUE THREAD

**Issue by tplass** [Digitaler-Impfnachweis/covpass-android#41]
Phone is Google-free and runs LineageOS 16.0.

The offical Corona Warn App scans and processes QR codes generated by a local pharmacy w/o problems.

CovPass on a phone running stock Android scans and processes same QR codes OK.

CovPass installs OK, has access to camera and internet.  It locks onto QR codes shown to it, gives up and then the CommonErrorHandler falls through and displays the - nonfactual - error messages allocated to `BadCoseSignatureException` and `NoMatchingExtendedKeyUsageException` (ie. "COVID-Zertifikat enthält keine gültige Signatur Möglicherweise wurde...").

Does that mean that LineageOS is unsupported?  Could you please advise users of this fact and maybe fix the error handler?

**Comment by Ein-Tim** [comment]
@tplass Did you see #39 and tried what is written there? Connect to the internet.

**Comment by tplass** [comment]
In #39 the fix was to connect to the net.  I installed CovPass during my visit to the pharmacy, obviously connect. It would not work.

I tried again just now to verify: indeed CovPass works. So what was going on?

**Comment by Ein-Tim** [comment]
@tplass Maybe an internet connection glitch? But nice that it works now.

**Comment by wkornewald** [comment]
NoMatchingExtendedKeyUsageException Is usually thrown when the signing key used by the pharmacy doesn’t allow signing this type (test, recovery, vaccination) of certificate. The other exception is thrown when the signature isn’t valid.

Since you already looked at the code, would you also be able to debug which exception is really thrown in this case and for which signing key (the kid would be sufficient or the PEM or at least some textual representation that you can get with the debugger) and what type of certificate do you have?

**Comment by wkornewald** [comment]
Oh and the reason for the different app behaviors is that CovPass runs a more or less full check on your certificate before importing it, so you can be confident that it will also validate with CovPass Check and there are no bad surprises.

**Comment by tplass** [comment]
Sorry to have given some kind of wrong impression: I'm no Android dev at all.  I just grepped through the code to give the people in the know some clues (instead of re-typing the dialog box contents).

Anyway, this being some kind of human+network error, it might be advisable to check for connectivity when it's required.  And complain appropriately when unavailable.  Just a thought.  

I appreciate the strong tie with the Check side of things.

**Comment by 10Meisterbaelle** [comment]
It does work on LineageOS

**Comment by wkornewald** [comment]
Since the general issue is solved let's close this.
