### ISSUE TITLE
Camera is too dark when scanning a QR-code

### ISSUE THREAD

**Issue by java-crypto** [Digitaler-Impfnachweis/covpass-android#42]
I installed the Covpass-Check app on my Android Samsung A51 device with actual Android 11 running, but I could not scan my own vaccination certificate with this error message"Certificate ist ungültig". This seems to be because the camera picture taken by the app is much too dark. 

To check against a simple QR-code scanner, I installed your CovPass app in Android Studio and run the build app on an API30 emulator and get the picture as attached (covpass_qrreader_500.png).

![covpass_qrreader_500](https://user-images.githubusercontent.com/29948803/125769411-db3cf3ed-9c43-41fb-8434-4f1f29f20a89.png)

Then I ran a simple QR-code reader on the same emulator and got the picture as attached (simple_qrreader_500.png).

![simple_qrreader_500](https://user-images.githubusercontent.com/29948803/125769417-6824f936-6fb4-4086-80ba-d597402e40ab.png)

It is easy to see that the simple QR-code picture is much brighter than the one taken from the CovPass app.

In your source code, I did not find any camera settings, but there has to be one that forces the camera to reduce the brightness.

I took the source from this GitHub this morning (July 15th 2021 10:00 am).

If you should need more information, please let me know (you can use the German language and my public Email address javacrypto@gmx.de).

**Comment by G00fY2** [comment]
Looks like this is a design decision. If you check the screenshots in the app stores, you see this "design" too: 

- https://apps.apple.com/de/app/covpass/id1566140352
- https://play.google.com/store/apps/details?id=de.rki.covpass.app&hl=de&gl=US

There is just an overlay with a 0.57 alpha: https://github.com/Digitaler-Impfnachweis/covpass-android/blob/0589db73851a4d7a542663e2e3d63910304d763c/common-app/src/main/res/layout/fragment_qr_scanner.xml#L22

I am also not sure why they decided to style it like this. Would prefer a overlay with a cut out in the middle. Thats also what most people know for other QR scanner apps.

**Comment by java-crypto** [comment]
Thanks to @G00fY2/Thomas for pointing to the overlay that "darkens" the preview when scanning. I tested a value of 0.01 for alpha in https://github.com/Digitaler-Impfnachweis/covpass-android/blob/0589db73851a4d7a542663e2e3d63910304d763c/common-app/src/main/res/layout/fragment_qr_scanner.xml#L22 and the user experience was much better, especially when scanning a paper QR-code in a room. 

I'm for sure the developers used the alpha to darken the surrounding and leave a "cutout" in the middle with no alpha-darken... but forgot to assign the cutout to the ImageView with the alpha.

Maybe we read something from them that explains the behavior.

**Comment by jleufgen** [comment]
Hi all, thanks for the feedback the flashlight function will come with one of the next releases. Best regards

**Comment by G00fY2** [comment]
@jleufgen the issue is not about bad light conditions on camera itself, but a transparent dark overlay in the UI that is currently displayed on top of the camera preview. See the comments above.

Please reconsider if the dark overlay makes any sense.

**Comment by jleufgen** [comment]
@G00fY2 Hi, the overlay will also be fixed with one of the next releases :)
