### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by 10Meisterbaelle** [Digitaler-Impfnachweis/covpass-android#45]
Automatic Dark Mode through the Android Dark Mode like Corona-Warn-App

**Comment by TheChemicalWorkshop** [comment]
im thinking to fork this and FORCE dark mode (just change colors)

i just cant look at white anymore

**Comment by jleufgen** [comment]
Hello, thank you for your feedback! Dark mode support is currently under discussion.

**Comment by TheChemicalWorkshop** [comment]
> 
> 
> Hello, thank you for your feedback! Dark mode support is currently under discussion.

thank you !

**Comment by Ein-Tim** [comment]
Why has this been closed?

**Comment by jleufgen** [comment]
The Dark Mode setting is not supported at this time, as it is not conducive to the accessible implementation of the app.
