### ISSUE TITLE
Show when your test certificate expires and if it's expired

### ISSUE THREAD

**Issue by 10Meisterbaelle** [Digitaler-Impfnachweis/covpass-android#46]
You should be able to check if your test certificate is still valid (and if yes, how long) right inside the CovPass App

**Comment by AndiPopp** [comment]
The CovPass app does show the validity of the certificate. E.g. if I click on "Zertifikat anzeigen" below the QR code it gives me a green checkmark icon with a comment when my full vaccine protection is reached.

Still, I think it should be stated, that a proper validation - i.e. validating a certificate on another person's phone - has to be done via the CovPassCheck app. Never trust anything another person's phone shows you.

**Comment by 10Meisterbaelle** [comment]
Yes, obviously. But I don't only want to see if my vaccination is already valid, I also want to see if my test certificate is still valid.

**Comment by 10Meisterbaelle** [comment]
Edit: Clarified the issue

**Comment by 10Meisterbaelle** [comment]
I just found out this is a duplicate of #3
