### ISSUE TITLE
Bug: PCR Tests already hide after 2 days instead of 3

### ISSUE THREAD

**Issue by 10Meisterbaelle** [Digitaler-Impfnachweis/covpass-android#48]
When I add my PCR Test into my app, it will automatically go back to my vaccination certificate after two days instead of three.

**Comment by timokoenig** [comment]
Thanks for the report, we will look into this issue

**Comment by 10Meisterbaelle** [comment]
I think this behavior might be intended as antigen tests already hide after 24 hours.

**Comment by 10Meisterbaelle** [comment]
This is probably intended since some states want a PCR Test with a validity of 2 days
