### ISSUE TITLE
Google Pay Integration

### ISSUE THREAD

**Issue by 10Meisterbaelle** [Digitaler-Impfnachweis/covpass-android#52]
Since developers from healthcare organizations, government agencies and organizations authorized by public health authorities to distribute COVID vaccines and/or tests are now allowed to use the API for COVID Certificates in Google Pay, it would be great if CovPass would be one of the first apps to support it.

More information: https://developers.googleblog.com/2021/06/google-updates-passes-api-to-save-covid-testing-and-vaccination-information-on-Android-devices.html?m=1

**Comment by jleufgen** [comment]
Hi 10Meisterbaelle, 
the API isn’t yet available in Europe.

**Comment by DRSchlaubi** [comment]
Nonetheless, this should be requested [here](http://support.google.com/pay/merchants/contact/instore_merchants)

Only official authorities can request access to the API and if no one requests it, Google probably won't bother bringing it to Germany

**Comment by MikeMcC399** [comment]
This topic was declined under Corona-Warn-App https://github.com/corona-warn-app/cwa-app-android/issues/3486 - see https://github.com/corona-warn-app/cwa-app-android/issues/3486#issuecomment-864567221.

**Comment by DRSchlaubi** [comment]
> Hi 10Meisterbaelle, the API isn’t yet available in Europe.

Is is available to Spain and UK now, if we won't request this from Google it won't come here, they've made it very clear that you need to request access, so only officials can get it
