### ISSUE TITLE
The app is totally useless for providing the certificate to the "Digital Registration on Entry"

### ISSUE THREAD

**Issue by rjungbeck** [Digitaler-Impfnachweis/covpass-android#53]
The app actively prevents screenshots, so it does not allow the required upload of installed certificates.

This defeats the whole purpose of the the app: You need another (analog) prove of vaccination for entry.

**Comment by MikeMcC399** [comment]
@rjungbeck 
You are referring to https://www.einreiseanmeldung.de/ I guess.

As a workaround you can use the [Corona-Warn-App](https://www.coronawarn.app/en/) (CWA) which allows the storage of EU Digital COVID Certificates and allows screen shots.

In the early days of the CWA app, more than a year ago, screen shots were blocked for security reasons, however that restriction has been removed. Users worked around the blocked screen shots by taking photos of the screens, so blocking the screen shots didn't really increase security, it just made some things more difficult, also for reporting issues.

**Comment by rjungbeck** [comment]
I don't use CWA. 

Giving CWA access to personal identifying information (ie name in vaccination certificate) destroys most of its already limited data protection.

The issue is with CovPass and has to be solved there.

The solution could either be very simple (allow screenshots) or more advanced (automatically use the certificate in the browser if the app is installed and has a certificate).

**Comment by 10Meisterbaelle** [comment]
Solution: Don't allow screenshots, but there should be a button to save the QR Code

**Comment by Matt-17** [comment]
As my duplicate is closed, I add my last comment here:

> An export feature needs work while this solution (removing FLAG_SECURE) is almost free.
> What is the intention of setting the FLAG_SECURE?

Also it would be better for accessibility, isn't it?

**Comment by 10Meisterbaelle** [comment]
> What is the intention of setting the FLAG_SECURE

It might be because it prevents 3rd party apps from reading the QR Code from your screen

**Comment by Ein-Tim** [comment]
> It might be because it prevents 3rd party apps from reading the QR Code from your screen

In this case it would make no sense that screenshots are enabled in the Corona-Warn-App and disabled in CovPass.

**Comment by 10Meisterbaelle** [comment]
The Corona-Warn-App also had FLAG_SECURE before an update (I think)

Am Di., 10. Aug. 2021 um 12:16 Uhr schrieb Tim ***@***.***>:

**Comment by Matt-17** [comment]
> It might be because it prevents 3rd party apps from reading the QR Code from your screen

Well, if I have to use CWA for this, you just put this problem to another app. If I take a photo of my QR Code for the mentioned reason, third party apps can even get the Code even from storage (and from my screen). I don't see an upside while there are still downsides.

**Comment by Ein-Tim** [comment]
@10Meisterbaelle 

Yes, at the very beginning, see: https://github.com/corona-warn-app/cwa-app-android/issues/516 & https://github.com/corona-warn-app/cwa-app-android/issues/987

**Comment by Matt-17** [comment]
> The Corona-Warn-App also had FLAG_SECURE before an update (I think) 

Which actually is a reason to remove this flag here as well.

**Comment by 10Meisterbaelle** [comment]
> > It might be because it prevents 3rd party apps from reading the QR Code from your screen
> 
> Well, if I have to use CWA for this, you just put this problem to another app. If I take a photo of my QR Code for the mentioned reason, third party apps can even get the Code even from storage (and from my screen). I don't see an advantage while there are still downsides.

I do see the downsides, but there are more advantages, but I prefer my suggestion:

> Solution: Don't allow screenshots, but there should be a button to save the QR Code

**Comment by Matt-17** [comment]
Please explain more specific, would could the downside of this?
Also it would mean much more work than just allow it. If I need to use CWA, I can uninstall this app anyway.

**Comment by 10Meisterbaelle** [comment]
> Please explain more specific, would could the downside of this?

It would prevent 3rd party apps with permission to see your vaccination certificate, and it would also prevent accidentially showing the certificate while recording your screen, however, this is a minor benefit.

**Comment by Ein-Tim** [comment]
With version 1.7 you can now export certificates. They are exported as a PDF.

**Comment by Matt-17** [comment]
That's confusing. When I click on export it's recommending not to send an e-Mail or share with other people and then I get the share dialog? How do I save it into my downlaods folder and why does it use the share dialog if it's not recommended to share? 

But anyway, thanks for giving at least one possibility to export the QR Code somehow. Makes it much easier.
