### ISSUE TITLE
Reissued vaccination certificate not selected by default

### ISSUE THREAD

**Issue by MikeMcC399** [Digitaler-Impfnachweis/covpass-android#57]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- First reported on App version: CovPass-App 1.28.4
- Reviewed as not yet fixed on App version: CovPass-App 1.138.6

## Describe the bug

If a vaccination certificate is re-issued and scanned into the CovPass App, the new certificate will not be selected if there is already a vaccination certificate stored with the same vaccination date.

## Steps to reproduce the issue

1. Open CovPass App
2. Delete any existing certificates
3. Tap "+", tap QR-Code scannen, and scan an older complete EU Digital COVID Vaccination Certificate e.g. Number in a series of vaccinations/doses 2/2 
4. Scroll down to EU-Zertifikate, Impfzertifikat, note the label "Aktuell verwendetes Zertifikat"
5. Tap the certificate, scroll down to Unique certificate identifier and make a note of the last few characters
6. Tap back arrow twice
7. Tap "+", tap QR-Code scannen, and scan a re-issued complete EU Digital COVID Vaccination Certificate e.g. Number in a series of vaccinations/doses 2/2 for the same person and the same vaccination date as in step 3.
8. Repeat step 4. & 5. and see that the "Aktuell verwendetes Zertifikat" has not changed.

## Expected behavior

The "Aktuell verwendetes Zertifikat" should be the newer certificate, independently of the order that the certificates were scanned into the app.

## Possible Fix

The app could:

1. Notice that the user is scanning in a certificate for which there is already an equivalent certificate stored (same person, same vaccination date) and suggest to use only the newer certificate.
2. If both the older and the re-issued certificate are stored, then when deciding on the "Aktuell verwendetes Zertifikat" the newer vaccination certificate should be chosen.

## Additional context

The same issue with the Corona-Warn-App has been reported in https://github.com/corona-warn-app/cwa-app-android/issues/3838 by @vaubaehn

**Comment by wkornewald** [comment]
Thanks for reporting. We'll need to solve this for sure.

**Comment by MikeMcC399** [comment]
@wkornewald 
Have you decided how you will deal with this case?

You could prevent storing a duplicate certificate (same name, same vaccination date) and offer to replace an existing certificate if a newer one is presented for scanning in. CovPass already prevents an identical certificate being scanned in (COVID-Zertifikat wurde bereits hinzugefügt).

Or you could allow the storage of the additional certificate and then prefer the certificate with the newer issue date if there are multiple certificates for the same person and same vaccination date.

**Comment by MikeMcC399** [comment]
@wkornewald 
The issue I described for CovPass-App is in the process of being resolved for the Corona-Warn-App (see https://github.com/corona-warn-app/cwa-app-android/issues/3838).

Do you have concrete timing to resolve it for CovPass-App?

You did already say:
> We'll need to solve this for sure.

**Comment by MikeMcC399** [comment]
This issue is no longer reproducible in CovPass-App Version 1.165.6.
