### ISSUE TITLE
Where is the validation feature shown in the screenshot from Google Play

### ISSUE THREAD

**Issue by 10Meisterbaelle** [Digitaler-Impfnachweis/covpass-android#58]
* [x] None of the other issue templates apply to this issue.

I am wondering where the feature to validate your own certificates in different countries is? Will it come in the next update or is this a bug?
![unnamed](https://user-images.githubusercontent.com/45918080/127740034-4de71e79-5a32-42ef-a33c-4a1ad9bbb92e.png)

**Comment by jleufgen** [comment]
This will be fixed with the next release :)
