### ISSUE TITLE
Names in non-Latin alphabets

### ISSUE THREAD

**Issue by kernzerfall** [Digitaler-Impfnachweis/covpass-android#6]
If  the certificate holder's name isn't written in the Latin alphabet, the app should show its transliteration, which is usually also included in the certificate's payload.

Especially on the _checking_ side, people shouldn't be expected to be able to read other alphabets and check the values against whatever is written on the holder's ID document.

Currently, the transliteration is nowhere to be found:

(CovPass)

<img src="https://user-images.githubusercontent.com/25184224/122412605-61ea9000-cf8e-11eb-8b79-905a28676d38.png" alt="covpass main view" width="256"/>

<img src="https://user-images.githubusercontent.com/25184224/122412665-6f077f00-cf8e-11eb-8e91-db8240ed8ee1.png" alt="covpass detail view" width="256"/>

(CovPassCheck)

<img src="https://user-images.githubusercontent.com/25184224/122412683-729b0600-cf8e-11eb-9283-4c331fc97cc0.png" alt="covpasscheck" width="256"/>

 [Switzerland's certificate checking app](https://play.google.com/store/apps/details?id=ch.admin.bag.covidcertificate.verifier) does show it, for example, on the bottom:

<img src="https://user-images.githubusercontent.com/25184224/122412707-775fba00-cf8e-11eb-8454-c3e5bd2077f0.png" alt="swiss certificate check" width="256"/>

**Comment by kernzerfall** [comment]
I was able to come up with the following solution, involving minimal edits and avoiding any radical changes to the app

Basically, if the name contains characters deemed "unreadable," anything past U+00FF, the transliterations - if available - will be preferred over the original names.

I tested it against some of the data in [eu-digital-green-certificates/dgc-testdata](https://github.com/eu-digital-green-certificates/dgc-testdata), as well as with my own actual certificate and it seems to work as intended.

```patch
From 8059cd60b72cfffbde5c1c97048c39b0d7555399 Mon Sep 17 00:00:00 2001
From: kernzerfall <kernzerfall@mailbox.org>
Date: Thu, 17 Jun 2021 20:35:22 +0300
Subject: [PATCH] Use name transliteration if original name contains non-latin
 characters

---
 .../covpass/sdk/cert/models/CovCertificate.kt | 30 ++++++++++++++-----
 1 file changed, 22 insertions(+), 8 deletions(-)

diff --git a/covpass-sdk/src/main/java/de/rki/covpass/sdk/cert/models/CovCertificate.kt b/covpass-sdk/src/main/java/de/rki/covpass/sdk/cert/models/CovCertificate.kt
index 82801fc..02df9cf 100644
--- a/covpass-sdk/src/main/java/de/rki/covpass/sdk/cert/models/CovCertificate.kt
+++ b/covpass-sdk/src/main/java/de/rki/covpass/sdk/cert/models/CovCertificate.kt
@@ -73,17 +73,31 @@ public data class CovCertificate(
         get() = recoveries?.firstOrNull()
 
     public val fullName: String by lazy {
-        listOfNotNull(
-            name.givenName ?: name.givenNameTransliterated,
-            name.familyName ?: name.familyNameTransliterated
-        ).joinToString(" ")
+        if((name.givenName?.contains(Regex("[\u00FF-\uFFFF]")) == true) ||
+            (name.familyName?.contains(Regex("[\u00FF-\uFFFF]")) == true))
+            listOfNotNull(
+                name.givenNameTransliterated ?: name.givenName,
+                name.familyNameTransliterated ?: name.familyName
+            ).joinToString(" ")
+        else
+            listOfNotNull(
+                name.givenName ?: name.givenNameTransliterated,
+                name.familyName ?: name.familyNameTransliterated
+            ).joinToString(" ")
     }
 
     public val fullNameReverse: String by lazy {
-        listOfNotNull(
-            name.familyName ?: name.familyNameTransliterated,
-            name.givenName ?: name.givenNameTransliterated
-        ).joinToString(", ")
+        if((name.givenName?.contains(Regex("[\u00FF-\uFFFF]")) == true) ||
+            (name.familyName?.contains(Regex("[\u00FF-\uFFFF]")) == true))
+            listOfNotNull(
+                name.familyNameTransliterated ?: name.familyName,
+                name.givenNameTransliterated ?: name.givenName
+            ).joinToString(", ")
+        else
+            listOfNotNull(
+                name.familyName ?: name.familyNameTransliterated,
+                name.givenName ?: name.givenNameTransliterated
+            ).joinToString(", ")
     }
 
     public val validDate: LocalDate?
-- 
2.30.1


```

**Comment by wkornewald** [comment]
Thanks a lot for the patch. We'll have to check with the UX team how to best deal with that (e.g. should the normal name also be visible?). Also in the final regex we'd have to use `\p{IsLatin}` which is slightly more correct and remove some repetition from that code.

**Comment by kernzerfall** [comment]
Maybe something like this would look better

```kotlin 
public val fullName: String by lazy {
    var disallowedCharacters = Regex("[^\\p{IsLatin}\\-,\\.`'\\s]")
    var nameList: MutableList<String> = mutableListOf()

    listOf(
        Pair(name.givenName, name.givenNameTransliterated),
        Pair(name.familyName, name.familyNameTransliterated),
    ).forEach { namePart ->
        namePart.first?.let { it ->
            if(!it.contains(disallowedCharacters) || namePart.second.isNullOrEmpty()) {
                nameList.add(it)
                return@forEach
            }
        }
        namePart.second?.let { it ->
            nameList.add(it)
        }
    }

    nameList.joinToString(" ")
}
```

Also, a plain `\p{IsLatin}` would exclude cetrain diacritics in latin names like dots (e.g. in Dr.), apostrophes, spaces and dashes (e.g. in "Musterfrau-Gößinger" or "Peter Paul Maria"). I've changed this to ```[^\p{IsLatin}\-,\.`'\s]``` above

**Comment by My1** [comment]
I would say personally just show both if the transliteration is in and not identical to the main name (not sure how certs handle names that are already plain latin)

**Comment by kernzerfall** [comment]
That's purely a UX thing. For example the Polish (Unijny Certyfikat Covid) and Swiss apps show both, whereas the Dutch (Scanner voor CoronaCheck) and the Danish one (Coronapas) show only the transliteration. 

IMO, since the CovPass apps are intended for use in Germany, showing non-Latin names is kind of redundant and adds unnecessary details for controlling personnel to skim through. At the end of the day, either solution is fine anyway.

**Comment by My1** [comment]
to be honest I have no idea how all the national ID cards show names so both may be useful, I thought the covpass apps were an EU thing rather than purely german, as it would be weird that every place needs to make its own app when the covid certs and all the efforts around it are supposed to be across the EU

**Comment by kernzerfall** [comment]
The certificate that you put in the app is an EU thing, and you can use the CovPass app to show it anywhere in the EU. IMO, it also has great potential to be used outside of DE, because it isn't tied to a national healthcare system like the Belgian or the Danish apps and you can just import any EU cert.

CovPassCheck and other checking apps are/will be specific to each member state, however, because each one has its own rules for what is valid and what isn't.

**Comment by My1** [comment]
okay but even then at least in the EU you iirc can go around with national ID cards and not sure what variation of the names the ID cards all around the EU use.

**Comment by jleufgen** [comment]
Hi all, thanks for the feedback! It will be scheduled in one of the next sprints. Best regards!
