### ISSUE TITLE
Enable screenshots

### ISSUE THREAD

**Issue by Matt-17** [Digitaler-Impfnachweis/covpass-android#62]
## Current Implementation
Right now screenshots are disabled by a security flag. This happens in the file [BaseActivity.kt](https://github.com/Digitaler-Impfnachweis/covpass-android/blob/dc4dc3825818165ad58b18fb98709d65efe59906/common-app/src/main/java/de/rki/covpass/commonapp/BaseActivity.kt):
```
        if (!isDebuggable) {
            window.setFlags(
                WindowManager.LayoutParams.FLAG_SECURE,
                WindowManager.LayoutParams.FLAG_SECURE
            )
        }
```

## Suggested Enhancement
Remove those lines and allow screenshots. 

## Expected Benefits
There is no reason not to allow this. Copying the QR-Code (if this is the reason) is even easier with this app alone. 

The reason I needed this now, is [einreiseanmeldung.de](https://einreiseanmeldung.de/). I travel using this app, but to return, I need to upload my certificate which could have been done easy with a screenshot.

Also removing this would allow better accessibility.

**Comment by Ein-Tim** [comment]
Related to: #53

**Comment by wkornewald** [comment]
Since this is a duplicate, I hope it's ok if I close this. We'll provide an export feature in the future.

**Comment by Matt-17** [comment]
An export feature needs work while this solution is almost free. 
What is the intention of setting the FLAG_SECURE
