### ISSUE TITLE
Set time for complete vaccination

### ISSUE THREAD

**Issue by FlxiBoy1313** [Digitaler-Impfnachweis/covpass-android#63]
## Suggested Enhancement
- Currently only 14 days are displayed, which is now a countdown of how long you still have e.g. 10 days or 2 days

## Expected Benefits
- I think it looks better than when it says 14 days non-stop.

**Comment by jleufgen** [comment]
We always indicate the date of vaccination. So it is also agreed with the client.

**Comment by FlxiBoy1313** [comment]
thx 👌
