### ISSUE TITLE
personalaccesstoken

### ISSUE THREAD

**Issue by atrink1978** [Digitaler-Impfnachweis/covpass-android#64]
## Avoid duplicates
* [X] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Question has not already been asked in another issue

## Your Question

* Source File:  https://github.com/Digitaler-Impfnachweis/covpass-android#usage
* Line(s):  personalaccesstoken
* Question:

- Are there any technical or licensing or contractual or <someother> reasons to need for github-username personalaccesstoken to build this?

**Comment by kernzerfall** [comment]
It's for [Github Packages](https://docs.github.com/en/packages/learn-github-packages/introduction-to-github-packages), which [requires authentication](https://docs.github.com/en/packages/learn-github-packages/installing-a-package), and is used to get packages from [ehn-dcc-development](https://github.com/ehn-dcc-development).

https://github.com/Digitaler-Impfnachweis/covpass-android/blob/d8fad0b5c55cb3f3f48228d6b8622c48f0b99e53/build.gradle#L53-L61

 I think this has to do with business rule validation, i.e. the "Gültigkeit prüfen" function

**Comment by wkornewald** [comment]
Yes that’s right. Unfortunately, GitHub Packages requires authentication even for public repos/packages. They already fixed it for Docker images, so there’s hope that at some point the auth requirement will also be removed for Maven repos.
