### ISSUE TITLE
Adding validation from Intent to enable using for example NFC tags

### ISSUE THREAD

**Issue by Astagor** [Digitaler-Impfnachweis/covpass-android#65]
Hi, my company is working a lot with NFC tags and it would be great if the app could validate not only QR-based certificates, but could receive Intent with the data from the QR. This way we could provide to people NFC tags, which would provide the app with the same data as the QR does. People could have armbands with an NFC chip, or cards in their wallets, and be able to present their vaccination certificate to a person with the app. This would be very good for events, that people would not loose time searching for their certificate on their phones, but just tap their NFC card or armband against the phone of the person checking.

**Comment by jleufgen** [comment]
Hi @Astagor the topic of NFC support is currently under discussion.

**Comment by oliver-steinbrecher** [comment]
Thanks for raising this topic. Currently this topic is not on a short-/mid-term roadmap. Reason for this is that the priority for this topic on European level has been decreased in favor of more pressing topics like recovcation and booster handling.

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
