### ISSUE TITLE
Android 5.1.1

### ISSUE THREAD

**Issue by radekg** [Digitaler-Impfnachweis/covpass-android#66]
A question from the technical point of view, as I haven't done much Android development in the last few years:

What stands in the way of this having this application working with Android 5.1.1? Trying to install on Android 5.1.1 from the play store results in an error saying that the app is not supported on the device. Considering that the main purpose of the app is to store a scanned qr code info - what would it take to have this working on that version of Android?

## Avoid duplicates
* [ ] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [ ] Question has not already been asked in another issue

## Your Question

* Source File:
* Line(s):
* Question:

**Comment by Ein-Tim** [comment]
Hey @radekg 

FYI: The reasons for this were already discussed in #15. I suggest you read through this issue and if any questions still remain afterwards, you can comment on #15.

**Comment by radekg** [comment]
Thanks, for the reference: https://github.com/Digitaler-Impfnachweis/covpass-android/issues/15#issuecomment-907532105.
