### ISSUE TITLE
Link to the adverse reaction reporting tool

### ISSUE THREAD

**Issue by Nomis101** [Digitaler-Impfnachweis/covpass-android#69]
There is an online reporting tool for adverse reactions after COVID-19 vaccination from PEI.
https://nebenwirkungen.bund.de/nw/DE/home/home_node.html
(Then click on "zum COVID-19 Meldeformular").

Would it be possible to inform the vaccinated person after he has scanned his certificate about the possibility to report any adverse reactions he has after his vaccination? Maybe with a link to the reporting tool?

Same as https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/47 but for Android.

**Comment by jleufgen** [comment]
Thank you for the hint. We will discuss the topic.

**Comment by jleufgen** [comment]
@Nomis101 thanks for your efforts. Unfortunately, the link to the adverse reaction reporting tool is not supported in the implementation. However, we hope that you will continue to be so active in the community.
