### ISSUE TITLE
Long-Tap on QRCode should display it in maximum size and set screen brightness to highest

### ISSUE THREAD

**Issue by kralo** [Digitaler-Impfnachweis/covpass-android#7]
Machine readable codes should be displayed in maximum size.

Currently, there is no option to zoom the code (at least I found none).

I suggest that a Long-Tap on QRCode it should display it in maximum size and set screen brightness to highest.
Similar to what Deutsche Bahn does when you want to show your online ticket.

The maximum size should be a display overlay, that displays the qrcode, but leaves a white "quite zone" around the code for most readers.

This features would be helpful for everyone displaying the code, even on older smartphones that might not have the best screen resolution and thus pixel density.

**Comment by wkornewald** [comment]
Just wondering, did you see any scanning issues in practice? Often such solutions are necessary for special scanners (like the Deutsche Bahn or DHL ones) because they can only read very clearly visible codes, but that doesn't affect phones so much.

**Comment by Flole998** [comment]
Maybe at some point those special scanners (which are also often used at event locations by the way) will be used for this purpose aswell. I could imagine that I have to scan a ticket and a valid vaccination certificate that matches the name on the ticket and then I am granted access. In the end maximum compatibility should be achieved, especially if it is by doing something this simple. Also a small "Info-Symbol" next to the star symbol could show the information that is currently shown when tapping on the code as usually the code should be scanned.

**Comment by 10Meisterbaelle** [comment]
I don't think it should set the phone to maximum brightness, but it should set the QR Code to maximum size

**Comment by cdraeger** [comment]
> I don't think it should set the phone to maximum brightness, but it should set the QR Code to maximum size

Maximum brightness is indeed required, the scanning will otherwise in many conditions not work. You can take other apps examples like Deutsche Bahn ticket app, DHL app for scanning at package stations etc. They all increase size and display brightness temporarily for a reason.

**Comment by voltcraft1** [comment]
> I don't think it should set the phone to maximum brightness, but it should set the QR Code to maximum size

Yes please.

**Comment by jleufgen** [comment]
The flashlight function will be included in one of the next releases. Thus, the maximum brightness is also guaranteed. Thanks for the feedback! Best regards!

**Comment by treysis** [comment]
Yes, but if you tap the QR it should pop up with max brightness. Like the Swiss app does it. I stopped using CovPass because it is annoying to almost always have to adapt screen brightness when somebody tries to scan the certificate.

**Comment by cdraeger** [comment]
@treysis Thanks for sharing your experience, this was the reason for the tickets. I tried to explain this on the iOS ticket.

I am afraid @jleufgen did either not understand the nature/problem of these issues, or it's just closed because there is no will to invest the effort into an important fix (imho it is a technical debt, not a feature). Unfortunate..

**Comment by treysis** [comment]
I do understand it would be a design change as currently tapping the CR will open the details. However, I have no idea how this passed testing. Maybe test devices didn't need low brightness because it was in a well illuminated office. I also don't understand why CWA doesn't increase brightness as well.

Anyways, I am on the Swiss app until this is fixed.

**Comment by Flole998** [comment]
You could also fork this App and make the changes you want ;)

I've proposed a possible solution above:

> Also a small "Info-Symbol" next to the star symbol could show the information that is currently shown when tapping on the code as usually the code should be scanned.

**Comment by treysis** [comment]
Totally agree. I could even craft a PR. But I fear design decisions are difficult to propose, so it would be rejected. I also don't want to maintain a personal fork.

Why go through all the hassle, when there is a solution: Swiss Covid Cert.
