### ISSUE TITLE
Can I install this app outside of Play Store

### ISSUE THREAD

**Issue by radekg** [Digitaler-Impfnachweis/covpass-android#70]
and still have the verification of the vaccination properly functioning on the phone? Since nobody wants to follow up on the https://github.com/Digitaler-Impfnachweis/covpass-android/issues/15#issuecomment-907555068, I would like to proceed in the following way:

- adapt the forked application to work with 5.1.x Android
- install on the phone outside of the usual Play Store supply chain
- import the vaccination QR code
- have the certificate properly functioning

Will this work?

## Avoid duplicates
* [x] Question is not already answered in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Question has not already been asked in another issue

## Your Question

* Source File:
* Line(s):
* Question:

**Comment by wkornewald** [comment]
The forked app is maintained by a third-party not associated with this (official) app in any way. So, closing this issue.

However, I'd highly recommend not supporting (and not even using) Android 5 because that would be quite irresponsible from a security perspective.

**Comment by github-tomster** [comment]
@upper-level federal agency
publishing only on googlepray is irresponsible from a security perspective! 🤦🏻‍♂️ 
this is all a joke!
