### ISSUE TITLE
App crash if certificate was modified

### ISSUE THREAD

**Issue by Knollo** [Digitaler-Impfnachweis/covpass-android#71]
I just randomly played and tested with a normal QR-Reader to get the source-content from my certificate and recreate the QR-Code. It works, but if I delete just the last three or four characters and recreate the QR-Code, the Apps crash. This occurs with both the CovPass App and CovPass-Check App. The Corona-Warn-App doesn't care and it reports the certificate as invalid.
If i delete only 2 or more than 4 characters the apps reports a message because the QR is invalid.

I'm not sure if this is reported correctly here. It won't be a problem, but if someone wants to annoy the check app users, they can do that with it.

## Technical details
- OS version: Android 11
- App version: 1.85.6

**Comment by wkornewald** [comment]
Thanks for reporting. We’ll try to reproduce and fix this.

**Comment by jleufgen** [comment]
Thanks, the bug will be fixed with one of the next releases :-)
