### ISSUE TITLE
Allow user to select language

### ISSUE THREAD

**Issue by voltcraft1** [Digitaler-Impfnachweis/covpass-android#72]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
The app uses android phone's language as display language

## Suggested Enhancement

Please give an option to show other languages (at least EU languages).

## Expected Benefits

1. If you go to shops or government offices in Germany, they sometimes cannot read and understand "Fully vaccinated" in English. So not user-friendly.
2. I would suggest a country flag type button next to ? (information) button where the user can have a drop-down of all EU (+British) flags.

**Comment by jleufgen** [comment]
Thanks! The app is already available in English, other languages are currently not planned.

**Comment by voltcraft1** [comment]
Perhaps my suggestion was unclear.  Yes, I do know the app is available in English. 

I want to keep the phone in English but display app in German. (i.e) I am an expatriate living in Germany. I want to select app language to German so that in Burgeramt or other places I can show in Deutsch.
