### ISSUE TITLE
Wasted space at the bottom and top means this app is not good for small phones

### ISSUE THREAD

**Issue by voltcraft1** [Digitaler-Impfnachweis/covpass-android#73]
## Avoid duplicates
* [X] This enhancement request has not already been raised before

## Current Implementation
Please remove wasted white space at the bottom/top of the app and move the (+) button elsewhere. This is pain in small phones (like a 4,5 or 5 inch phone. Yes they do exist.

## Suggested Enhancement

Move the (+) button elsewhere (or a hamburger menu)

## Expected Benefits
Easy to see entire QR code and Name in totally/entirely

**Comment by jleufgen** [comment]
Thanks!! The issue will be fixed with one of the next releases.

**Comment by alexcimander** [comment]
Hi everyone! 
Update: We are working on a refactoring on the start screen of the CovPass which should improve the UI for smaller screens and should promote the usage of the CovPass. We will keep you updated about when the improvements are released. 

Thank you for your great suggestions! 👍

**Comment by pucherd** [comment]
Hello @voltcraft1, we did some minor refactoring on the start screen - can you please try out our latest 1.16.1 version?

**Comment by voltcraft1** [comment]
It is better than before. Thanks
