### ISSUE TITLE
no access to exported certificate pdf

### ISSUE THREAD

**Issue by pi-bie** [Digitaler-Impfnachweis/covpass-android#74]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Sony D5803
- OS version: Android 6.0.1
- App version: 1.95.12

## Describe the bug

When I try to export the certificate as a pdf file, I cannot share the file with any of the given options, as the file `Certificate-XXX-YYY.pdf` can't be found/accessed in the cache folder.

## Steps to reproduce the issue

Trying to save the file with file explorer app shows the error
`Datei nicht gefunden (/data/user/0/de.rki.covpass.app/cache/Certificate-XXX-YYY.pdf: open failed: EACCES (Permission denied)).`

## Expected behaviour

The pdf file is saved in a folder accessible to other apps/the user.

**Comment by jleufgen** [comment]
Thank you very much for the hint. This Bug will be fixed with the next release.

**Comment by jleufgen** [comment]
The bug is fixed! :)
