### ISSUE TITLE
QR Code cannot be displayed in total on phone with Screensize of 720 x 716 px

### ISSUE THREAD

**Issue by jlusiardi** [Digitaler-Impfnachweis/covpass-android#76]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name:  Unihertz Titan Pocket [(Specs)](https://www.gsmchoice.com/de/katalog/unihertz/titanpocket/)
- OS version: Android 11
- App version: 1.86.0

## Describe the bug

The  Unihertz Titan Pocket has a rather small scren resolution of 720 x 716 px and seems to be unable to display the QR in a total view. I found different places were the QR is displayed but on each the QR must be scrolled. That prevents it from being scanned by a verifying party.

## Steps to reproduce the issue

1. add certificate
2. exit app
3. start app again
4. on start screen the certificate is displayed in scrollable container

## Expected behaviour

The app should offer way to present a total view of the certificate.

**Comment by jleufgen** [comment]
Hi, this will be improved with one of the next releases. Best regards!

**Comment by alexcimander** [comment]
Hi everyone! 
Update: We are working on a refactoring on the start screen of the CovPass which should improve the UI for smaller screens and should promote the usage of the CovPass. We will keep you updated about when the improvements are released. 

Thank you! 👍

**Comment by shbert** [comment]
I have a similar issue with the original Unithertz Titan (not pocket), I assume, this is related to the quadratic display. So it is currently not possible, that the qr code is presented without scrolling the QR code. The QR code scrolls within the blue box.

**Comment by pucherd** [comment]
Hello @jlusiardi, we did some minor refactoring on the start screen - can you please try out our latest 1.16.1 version?

**Comment by jlusiardi** [comment]
After the new Version is available in the F-Droid app store (1.13.2 is the newest version there) i can perform a test

**Comment by jlusiardi** [comment]
sorry it took so long, but this is still broken in 1.19.0 from F-Droid .

**Comment by ingowerren** [comment]
In 2021, the European Union introduced the digital COVID certificate as an EU-wide recognised proof of vaccination, recovery or negative testing for COVID-19. This regulation expired on 30 June 2023. On a transitional basis, the EU will continue to operate the technical systems to enable cross-border certificate checks until 31 December 2023. The transitional operation will end on that date.
In Germany, the possibility of issuing digital COVID certificates such as vaccination and recovery certificates will therefore be discontinued on 31 December 2023. The CovPass app and the CovPassCheck app will therefore also be discontinued. The CovPass app will be switched to wallet mode, where the stored certificates will be retained.

What does this mean for you?
All functionalities will continue to beavailable until 31 December 2023.

**From 1 January 2024:**

Support for the app will no longer be offered.

- The apps will no longer be available for (re)download in the app store.
- No new functions will be published.
- Further information can also be found in the CovPass app privacy policy.
