### ISSUE TITLE
Blanks in names cause special characters

### ISSUE THREAD

**Issue by master4x** [Digitaler-Impfnachweis/covpass-android#77]
**This bug contains personal data and could be of high priority.**

## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3a
- OS version: Android 11
- App version: 1.95.12

## Describe the bug

Since the updated version of CovPass introduced the field option `standardized name, first name` the app converts my name wrong. Because I've got a second first name (middle name) written with **a blank character, the app converts the space into the following character: `<`.** Any other characters are correctly displayed in caps. I have no problem in the upper view of the 'normal' namespace. 

## Steps to reproduce the issue

I scanned my certificate as I got the app (before the new feature was released). 
As I checked out the new feature, I realised that my standardized name is spelled incorrect. 
You could reproduce my issue trough importing a certificate with a middle name.

_Since screenshots are blocked, it's hard to proof my point here._ 
But it looks like this:
> **Name, Vorname / name, first name**
>   Kelle, Leon Niklas
> **Standardisierter Name, Vorname / Standardized name, first name**
>   KELLE, LEON<NIKLAS

**This looks incorrect and could lead to problems during checks.**

## Expected behaviour

The standardized name field should convert blank spaces (eg. whitespaces) into blank spaces.

**Comment by Ein-Tim** [comment]
@master4x 

This is the intended behavior, however, I did not find a source currently, but I remember that somebody shared a document on this already. 

Maybe one of the devs could help out with the document here (:

**Comment by thinkberg** [comment]
It's not a bug. ICAO transliteration translates the machine readable space character into a <. It should probably not be displayed like this. But that is a visualization issue IMHO.

**Comment by MikeMcC399** [comment]
@thinkberg 
It's a little inconsistent with the ICAO format (see https://www.icao.int/publications/Documents/9303_p3_cons_en.pdf).

Probably the display should be either completely identical to the MRZ (Machine Readable Zone) like on an ID card or a passport, in this case
`KELLE<<LEON<NIKLAS`
or it should omit the "<" filler characters in the display completely. 

In 
`KELLE, LEON<NIKLAS`
using comma "," in one place and "<" in another place is not consistent. So probably
`KELLE, LEON NIKLAS`
would be better.

**Comment by thinkberg** [comment]
True, the dcc contains family and given name separately. I suggested already using either spaces and comma or the icao format.

**Comment by master4x** [comment]
Thanks for all the helpful information.
I think it would be best to put an entry about this in the FAQ to avoid confusion. 
The thread is now solved and I will close it.
Feel free to reopen it for internal editing by the team.
