### ISSUE TITLE
CovPass selects booster vaccination (3 of 3) immedeately as current certificate, and CovPassCheck then rejects it due to 14 days rule

### ISSUE THREAD

**Issue by jkrwdf** [Digitaler-Impfnachweis/covpass-android#79]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 3 XL
- OS version: Android 11
- App version: 1.138.6

## Describe the bug

My mother got her booster (3 of 3) today and I added it to CovPass. 
It is then selected as current certificate and shown in the entry screen for her person. 

![image](https://user-images.githubusercontent.com/5329491/134782552-89d3abb4-3de3-4ed9-ab9f-584572d3c575.png)

When scanning this then in CovPassCheck, the result is validation failure. 

Although CovPassCheck does not show the reason, I could find it out by performing the validity check for Germany in CovPass itself, and it turns out to be the "Since the last vaccination, 14 days must have passed" rule. 

## Steps to reproduce the issue

Add booster vaccination to CovPass and then perform CovPassCheck verification for the QR code shown in the entry screen of CovPass.

## Expected behaviour

Even after adding the "3 of 3", the person shall not be rejected by CovPassCheck.

## Possible Fix

When there are multiple vaccination certificates for the same person, the automatic selection in CovPass shall pick the most recent *valid* one (in the screenshot above, this would be the "2 of 2"). 

## Additional context

CWA does it right and ignores the "3 of 3" for now. 

![image](https://user-images.githubusercontent.com/5329491/134782745-c132df56-f68e-45a9-8334-1bd946624a7b.png)

And additionally, I would like to annotate that the rule "14 days after last vaccination" is in my opinion not applicable anyway for the "3 of 3" vaccination, because the "2 of 2" is still valid, and the fact that a "3 of 3" has been applied by the vaccinator proves that this was at least 6 months (which is more than 14 days) ago.

**Comment by Ein-Tim** [comment]
> And additionally, I would like to annotate that the rule "14 days after last vaccination" is in my opinion not applicable anyway for the "3 of 3" vaccination, because the "2 of 2" is still valid, and the fact that a "3 of 3" has been applied by the vaccinator proves that this was at least 6 months (which is more than 14 days) ago.

Yeah, that's actually a bug in the business rules which will be fixed soon hopefully. See https://github.com/corona-warn-app/cwa-documentation/issues/709

**Comment by jkrwdf** [comment]
Interestingly, people https://github.com/corona-warn-app/cwa-documentation/issues/709 claim that 3/3 certificates can be successfully be validated in CovPassCheck. 

This is something which I can clearly deny.

I assume those reports arise by people adding their 3/3 to CWA and then scanning the presented QR code for their identity, which in CWA is then still the 2/2.

**Comment by Ein-Tim** [comment]
@jkrwdf 

Yes, I opened this issue based on a Twitter report (user on Twitter complaining about a bug) and the user there said that CovPassCheck validates the certificate, however, he mixed something up there.
So no, CovPassCheck doesn't validate and will only do so once the Business Rules have been updated.

**Comment by jleufgen** [comment]
Thank you for your comments. We are aware of the problem and it should be fixed within the next few days. The validity check for booster vaccinations is currently being revised so that there will no longer be a two-week waiting period for these certificates.
