### ISSUE TITLE
Can't add Certificate issued from another country 

### ISSUE THREAD

**Issue by sobuj53** [Digitaler-Impfnachweis/covpass-android#81]
Hi,
I'm fully vaccinated and will move to Germany next month. However as I was vaccinated outside EU that is why I can't import my valid vaccine certificate. It would be really helpful if we could import our vaccine certificate in this app as well. I have attached a sample valid vaccine certificate here for your information. Would appreciate if you could take a look at this. Thank you very for your time and help. 

[sample_cert.pdf](https://github.com/Digitaler-Impfnachweis/covpass-android/files/7257843/sample_cert.pdf)

**Comment by jleufgen** [comment]
Hi, the citizen must have a vaccination entitlement according to the vaccination ordinance. For this purpose, there must be a connecting factor with Germany, e.g.:
- Employment contract
- Rental contract
- Health insurance
- Residence
There is no difference between EU citizens and non-EU citizens.

**Comment by alexcimander** [comment]
Besides that: The "wallet-app" named _CovPass_ and the  _Corona-Warn-App_ within Germany only accept QR-Codes that are based on the Digital-Covid-Certificate standard from the EU. There are countries outside of the EU which will be "onboarded" soon so maybe you will find some info on that for your country as well.

Information about the EU Digital COVID Certificate can be found here as well:

https://ec.europa.eu/info/news/eu-digital-covid-certificate-secure-eu-infrastructure-interoperability-and-open-source-heart-eu-gateway-2021-jun-01_de

I Hope that helps you a bit! I wish you a great time in Germany :-)

**Comment by sobuj53** [comment]
Thank you very much guys. Currently I'm in Germany with my printed hard copy certificate and so far it was accepted everywhere without an issue. However I'm not closing the issue, incase things change in the future.

**Comment by sobuj53** [comment]
Finally I have a solution. User with foreign vaccine certificate needs to visit the pharmacy (Apotheke), find something in the city center. Those who are in Munich can try Adalbert-Apotheke (Türkenstraße 80), Show your your current vaccine certificate (take a printed copy) and your passport. They will print you out a EU standard certificate with QR code for free. Pro tips, try to speak German when you go there. They are super helpful.
