### ISSUE TITLE
Any date output does not correspond to the set language environment.

### ISSUE THREAD

**Issue by eku** [Digitaler-Impfnachweis/covpass-android#83]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Doesn't matter
- OS version: Android 7.1 without Google Services
- App version: 1.95.12 from F-Droid

## Describe the bug

My device is set to the German language environment. The date display in the app in various places does not correspond to the set environment. This is especially annoying for people (which are mostly people in Germany) who check the imp status by reading the information. They have to "convert" the date YYYY-MM-DD each time. Why don't you make it easier for these persons and display the date according to the language environment? UX missing.

## Steps to reproduce the issue

Set your device to locale DE_DE, scan any certificate and display the "Impfzertifkat" as text.

## Expected behaviour

The date output corresponds to the set language environment, in Germany TT.MM.JJJJ.

**Comment by alexcimander** [comment]
Hey everyone - we will close this ticket since no further improvement is planned for now. We hope that we can further promote the usage of the CovPassCheck with the latest and upcoming improvements. 

Thank you for the participation and the honest feedback 👍
