### ISSUE TITLE
Does not show certificate as valid if it's the 3rd vaccination

### ISSUE THREAD

**Issue by otezun** [Digitaler-Impfnachweis/covpass-android#84]
Device: Samsung Galaxy A12
Version: 1.138.6
OS Version: Latest Android 11 available for device as of time of writing

Expected behavior: After scanning the QR code, either from another device or from the certificate issued by the vaccinator, the device should show the vaccination as "valid".

Actual behavior: Vaccination status is shown as not valid. 

Possible cause: Android application may not be able to show it as valid as it shows 3 of 2 vaccinations.

Other information:
In iOS application, the certificate is displayed correctly.

**Comment by alexcimander** [comment]
Hi @otezun thank you for the hint! Did you scan using the CovPass or CovPassCheck?

If it was CovPass:
1.) The QR-Code was readable and the vaccination was displayed as "invalid" or did you use the "check vadility" feature?
2.) The app stated that it was a 3/2 Vaccination?
3.) On your certificate issued by the vaccinator 3/3 is correctly shown?


Thank you for your help!

**Comment by otezun** [comment]
@alexcimander 
1.) Yes the QR-Code was readable and the vaccination was displayed as "invalid" in the main view of the CovPass application.
2.) It displayed it was 3/2 vaccinations, yes.
3.) Yes.

However, I just looked at it again and it now shows a full validation as expected. It now also shows 2/2 of vaccinations, which is incorrect, since it's actually 3/3 vaccinations. I'm not sure why it showed 3/2 directly after scanning the QR Code.

**Comment by otezun** [comment]
Alright. 
1) The QR was readable and the vaccination was displayed as invalid in the CovPass applications main view. 
2) The app stated 3/2 vaccinations, yes.
3) No. On the certificate from the vaccinator 3/2 is shown. 

After conferencing with the relevant local health department, they mentioned that this behavior is probably due to a software error in the certificate issuing software. They suggested a workaround.

"Use the second certificate instead of the third". When doing so, CovPass works as expected. This is not as software should be from a User friendliness point of view but I am pretty sure now it is not the fault of the CovPass application.
