### ISSUE TITLE
180 days or 6 months in case of recovery?

### ISSUE THREAD

**Issue by s09bQ5** [Digitaler-Impfnachweis/covpass-android#85]
* Source File: covpass-sdk/src/main/assets/covpass-sdk/eu-rules.json
* Line(s): There is only one :)
* Question: The RR-DE-0002 rule in the JSON file uses 180 days to check the validity of a recovery certificate. But the German SchAusnahmV talks in [§2](https://www.gesetze-im-internet.de/schausnahmv/__2.html) about 6 months and I was told that [BGB §188](https://www.gesetze-im-internet.de/bgb/__188.html) has to be applied as long as the regulation does not define 1 month = 30 days. Which one is correct?

**Comment by alexcimander** [comment]
Hey everyone - we will close this ticket and we hope that we answered your question. 

Thank you for the participation and the honest feedback 👍
