### ISSUE TITLE
Use eTag for Caching Trustlist / Signer Certificates

### ISSUE THREAD

**Issue by rowi1de** [Digitaler-Impfnachweis/covpass-android#89]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Current Implementation
- [The current implementation](https://github.com/Digitaler-Impfnachweis/covpass-android/blob/main/covpass-sdk/src/main/java/de/rki/covpass/sdk/cert/DscListService.kt) is always fetching the full trust list on every call

## Suggested Enhancement
- Use eTag Caching to avoid unnecessary Network Traffic 

## Expected Benefits
- Save Bandwidth for Client and Server

**Comment by alexcimander** [comment]
thank you for your feedback. Nice catch! - Multiple Improvements regarding the fetch of the trustlist - including the usage of eTag - will be implemented with one of the next releases!

**Comment by pucherd** [comment]
Hello @rowi1de, this improvement is added to our latest 1.16.1 release.
