### ISSUE TITLE
Generated QRCodes don't work.

### ISSUE THREAD

**Issue by Netzvamp** [Digitaler-Impfnachweis/covpass-android#93]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Samsung S7
- OS version: 8.0
- App version: 1.11.1

## Describe the bug

We're generating new QR codes from the raw data to print them on plastic cards. Our codes worked in previous versions of covpass/covpasscheck and also coronawarnapp. With one of the last updates our codes don't work and we can't figure out why. They are still working in coronawarnapp! And i can scan it in any other QR code app and the raw data are fine (exactly the same data is in my original qr code). And i can still scan my original QRcode just fine. Confusing.

## Steps to reproduce the issue

Try to scan the attached qr code. 

Just to clarify: This is my own QR code, so i can share it.

## Expected behaviour

It should scan.

## Possible Fix

Workaround: Can you give me the parameters (version, error correction, ...) to generate QR codes that are working in the app?

## Additional context

My generated QR-Code:

![image](https://user-images.githubusercontent.com/4619406/139239311-cd224687-ee3d-4bd4-8836-3b4d1ee8f155.png)

My original QR-Code that is still working in Covpass:

![image](https://user-images.githubusercontent.com/4619406/139241898-c6e2cbcb-1517-4852-b196-fd3681ace5c4.png)

**Comment by Netzvamp** [comment]
Any news on this? These qrcodes are already in use, so we are a bit in a rush 😝

**Comment by wkornewald** [comment]
Until this can be fixed on our end, do you have any alternative QR code generator that generates better codes? Your code also seems to fail here: https://qrlogo.kaarposoft.dk/qrdecode.html

It could take some time to debug and fix this and we'll have to work with the BoofCV team. We'll discuss a possible quick fix/workaround in the meantime.

**Comment by Netzvamp** [comment]
Thanks, Kudos to you 👍  

As i workaround i use a very old/unmaintained package: https://pypi.org/project/PyQRCode/ 
That works without any update since 2016, so that's kind of stable i guess 😉 
Would be nice to get the qrcode package codes also recognized again, so i'll hope for the bootcv project.

```python
from reportlab.lib.units import mm
from reportlab.pdfgen.canvas import Canvas
import pyqrcode

cert_raw = "HC1:6BFOXN*TS0BI$ZD8UH76PCM7ZJ7GZ20II/P3 43JUB/EBUMIU/3%$C2L9KST--M:UC*GPXS40 LHZA KEW%G%9DJ6K1AD1WMN+I0JK1WLB4DCHGLII3LN25OVLNF7LHCIZ09.9DM*GC9M$7JE9MZIIDOM1JAF.7IFNDXI03L9ZI4Q5%H0AN8EH06YB-TIP+P6OIB.VT*QNC2BFUF$SU%BO*N5PIBPIAOI-+R2YBV44PZB6H0CJ0QCK0YQK*R3T3+7A.N88J4R$F/MAITH6QS03L0QIRR97I2HOAXL92L0. KOKGTM8$M8SNCT64RR7+V4YC5/HQRPOHCR6W9.DPEA7IB65C94JB+ONS.CUIA7LE9JAF+B**O3-SY$NRUEG1AK/4C6DM.SY$NWYMG3GUBRCEIFRMLNKNM8POCJPG8/0NOLZGIZCUOY55*LTUJS1D7.J9$7$.IWQOMJV$6M53AA:6Z2S./BXPHRKGJUHB1WN5LH/M0:3P+E$$BWWNB8V5ZRF9JMKAX AAOL3H02YF*OF"

qr = pyqrcode.create(cert_raw, error='M', mode="binary")
qr.png('tmp.png', scale=10)
doc = Canvas('example_qrcode.pdf', pagesize=(85.7 * mm, 54 * mm))
doc.drawImage('tmp.png', 34.7 * mm, 2.5 * mm, width=49*mm, height=49*mm)
doc.showPage()
doc.save()
```

**Comment by lessthanoptimal** [comment]
@Netzvamp I looked into the QR Codes generated by that library and it's transposing the bits making the rendered marker non-compliant with the ISO standard. If you transpose the image that should fix it. This is a common mistake by encoders and many decoders will automatically try transposing the bits at the cost of some speed. To transpose the image you can apply a clock-wise rotation then a horizontal flip.

**Comment by Netzvamp** [comment]
Thank you all, nice to see how incredible effective the open source community is 👍 

I have a workaround for now, the qrcode python package will have a look at it and segno looks great ( Page 7 if you search for qrcode in pypi, wtf! https://pypi.org/search/?q=qrcode&page=7 )

**Comment by pucherd** [comment]
@Netzvamp We will provide a hotfix for 1.11.1

**Comment by Netzvamp** [comment]
> @Netzvamp We will provide a hotfix for 1.11.1

Now we have 1.12.0 without hotfix 😞

**Comment by alexcimander** [comment]
Hey Netzvamp,

you are right but stay with us - we are still on it and there will be a new version including the fix soon (planned for 1.12.1).

Thank you all!

**Comment by vincentfuhler** [comment]
@Netzvamp hi, can you please!!! remove youre QR Code form Github? I test it with Corona-Warn and it works! Now I have youre personal Data 🙈 youre 2. Vacanze was on 4.8.21 Bionatic

**Comment by Netzvamp** [comment]
I'm aware, that's how QR codes work 😉 I'll remove it, when it's fixed in Covpass-Check, that's more important for me right now.

**Comment by vincentfuhler** [comment]
Okay. I don't like that! Others can abuse with your code!

**Comment by Netzvamp** [comment]
Roger, thanks! 👍

**Comment by pucherd** [comment]
Hello @Netzvamp, 1.13.2 Android version is released and contains the mentioned fix ;)

**Comment by Netzvamp** [comment]
Thank you all! 🥳

**Comment by vaubaehn** [comment]
@Netzvamp 
You're not coding for "immunkarte", do you?
