### ISSUE TITLE
CovPass shows the date of a booster vaccination as "Vollständig seit dd.mm.yyyy" and not the date of the last required vaccination

### ISSUE THREAD

**Issue by Ein-Tim** [Digitaler-Impfnachweis/covpass-android#94]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://digitaler-impfnachweis-app.de/faq/)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: not relevant
- OS version: not relevant
- App version: 1.11

## Describe the bug

On the main screen CovPass shows since when the vaccination protection is complete. This should always be the date of the las required shot and not the date of a booster vaccination, as it is not required. However, CovPass actually does exactly this, it show the date of a booster vaccination as the date of since when the vaccination protection is complete.

Here are some screenshots:

| Main screen | Stored certificates |
|---|---|
| ![d0v3SWaH jpg-medium](https://user-images.githubusercontent.com/67682506/139256864-6b33383f-96ec-4797-8c8c-41fee42e11ed.jpeg) | ![yeqKoixj jpg-medium](https://user-images.githubusercontent.com/67682506/139256903-b10ba8de-0347-44ea-90c6-4696403b7b2c.jpeg) |

## Steps to reproduce the issue

1. Add a certificate of a booster vaccination to the app
2. See that the date on the start screen "Vollständig geimpft seit dd.mm.yyyy" shows that the vaccination protection is complete since your booster shot.

## Expected behaviour

The "Vollständig geimpft seit http://dd.mm.yyyy" should always be the date of the las required shot and not the date of a booster vaccination, as it is not required.... Last reqd date +14d (+28d on J&J).

**Comment by KinNeko-De** [comment]
On Version 1.12.0 on Android:
I had a J&J on 17:06.2021
And a booster Biontech on 03.11.2021

The screen shows: Vollständig seit 18.11.2021

So on version 1.12.0 with my combination of certificates my display is correct.

**Comment by Ein-Tim** [comment]
@KinNeko-De 

No it's not, as your vaccination protection is full since 15 days after your J&J shot & not after your booster shot.

**Comment by requiemmg** [comment]
In case of JJ vaccine: 28 days from first vaccination.

**Comment by pucherd** [comment]
Hello @KinNeko-De,
How is the Biontech booster vaccination displayed in the detail view?
- 1 von 1
- 2 von 2

**Comment by Ein-Tim** [comment]
@requiemmg 

You're right, thanks for the correction (:

**Comment by KinNeko-De** [comment]
@pucherd 
2 von 2.
As it is the only certificate that is shown to the reader I think this is more correct than 1/1.
It gives less confusion to not developers and not doctors ;)

@Ein-Tim 
That depends on the definition.
If you calculate only one certificate then 18.11.2021 is correct.
If you calculate every certificate, then your argument might be valid. But what if the certificate becomes invalid for 1 day and then your booster is active. Doing the calculation based on multiple certificates is more complex.
And as we all pay a lot of money for the implementation I would suggest keeping it as simple as possible.

The original issue was that the date of vaccination was shown. In my case, it would be 03.11.2021. which would be completely wrong. Was this issue fixed in version 1.12.0 maybe?

**Comment by ThiefMaster** [comment]
What's important is that getting a booster and using that QR code does NOT show you as "not yet fully vaccinated" for 2 weeks! Apparently people got sent back at the UK border because they used their booster code...

**Comment by KinNeko-De** [comment]
@ThiefMaster 
My booster was with Biontech and it switched on 18.11.2021.. not before. So still in my case, it was correct.

Except for the fact that the active certificate does not use UTC, which also is relevant for UK.
I opened a new issue for that #Digitaler-Impfnachweis/covpass-android/issues/106

**Comment by pucherd** [comment]
@KinNeko-De 
Ok, now I see that your booster vaccination Biontech is 2/2 what is also not correct because in this case we identify it as a second vaccination and the +14 days will be added until full vaccination.

If a Booster vaccination is a no single dose vaccine (Biontech, AstraZeneca, Moderna) - the vaccination should be 1/1 and in this case no +14 days will be added (full vaccination will be from the day of booster vaccination).
The issuing entity needs to create the DCC for Booster vaccination (no single dose vaccines) as 1/1.

**Comment by vaubaehn** [comment]
> The issuing entity needs to create the DCC for Booster vaccination (no single dose vaccines) as 1/1.

Hi @pucherd ,
as far as I can think CWA does not handle it like this... CWA and CovPass should be aligned here...
Did you have an exchange with SAP, i.e., @mlenkeit about that issue?

**Comment by vaubaehn** [comment]
Or am I wrong, @Ein-Tim ?

**Comment by Ein-Tim** [comment]
@KinNeko-De 

> That depends on the definition.

It does not. By law your vaccination protection is full 14 days after your second shot (for Biontech, Moderna or AstraZeneca) or 28 days after your first shot of the J&J vaccine.

>If you calculate only one certificate then 18.11.2021 is correct.

Yes, if only the booster certificate is added to the app, the app has no way to tell when your "Grundimmunisierung" was finished, so in this scenario the date is acceptable.

>If you calculate every certificate, then your argument might be valid. But what if the certificate becomes invalid for 1 day and then your booster is active. 

Why should my certificate become invalid for one day? A certificate only gets valid after 1 year after it's issuing. 

**For all other issues I ask you to create a new issue and not discuss in this issue!**

---

@vaubaehn You're right, see also https://www.coronawarn.app/en/faq/#vac_booster_jj, which says:
"Since only one vaccination is required for a basic immunization with the J&J vaccine, the entry '2 of 2' must be made in the vaccination certificate for the booster vaccination under 'Number in a series of vaccinations'."

Also, @pucherd's statement contradicts what is written on https://digitaler-impfnachweis-app.de/en/faq:

"Is the booster vaccination your second vaccination? 

Then the number 2/2 must be noted in the certificate. In this case, the app cannot recognize whether it is the second vaccination of the basic immunization or a booster vaccination. Therefore a two-week waiting period is indicated. In this case, please show your old certificate with the number 1/1. This is still valid."

**Comment by ThiefMaster** [comment]
> Then the number 2/2 must be noted in the certificate. In this case, the app cannot recognize whether it is the second vaccination of the basic immunization or a booster vaccination. Therefore a two-week waiting period is indicated. In this case, please show your old certificate with the number 1/1. This is still valid."

Maybe the app should then prefer that certificate and not require the user? Because if I was a non-techie user I would certainly not expect that I need to keep using an old certificate for 2 weeks...

Of course the ideal solution would be to have a way to indicate a booster in the certificate's data which would then not require the 2 week wait period...

**Comment by Ein-Tim** [comment]
@ThiefMaster 

Please create a new issue for this.

**Comment by ThiefMaster** [comment]
Looks like #106 already covers this :)

**Comment by vaubaehn** [comment]
@Ein-Tim thanks for your exhaustive and helpful research/explanations! ❤️ 
And sorry I joined hijacking the issue... But I felt it needs an immediate response to @pucherd .

**Comment by github-bugsubmit** [comment]
Can confirm this bug.

I have 3x Biontec, they show as 1/2, 2/2, and 3/3 in the detail view (note how it's counting differently, once /2 and once /3).

The front page shows "Vollständig seit:" with the date of the booster vaccination, which is wrong.

**Comment by Ein-Tim** [comment]
@alexcimander

Is there any fix for this issue planned?

**Comment by requiemmg** [comment]
may I suggest a thing?
Wait for a while. Yes, it is a bug. But as of December 2nd, Germany plans to implement a time limit in certificate validity.
I'd suggest to wait for the new rules and reimplent the routines when the new rules are set; I'd expect this to happen in Jan 22.

**Comment by Ein-Tim** [comment]
@requiemmg 

I know what you mean and understand your thoughts, however, I disagree. This is a bug now & should be fixed. If something changes, it's easy to revert this change & align the app to new rules.

**Comment by alexcimander** [comment]
Hey everyone!

we are working on a design refactoring which will also affect the "Vollständig seit dd.mm.yyyy".

The refactoring will fix the mentioned bug. 👍 

Thank you for the discussion and the feedback - We will keep you updated ⛑️ 

stay safe everyone!

**Comment by Ein-Tim** [comment]
This has been improved in version 1.16, as the start screen no longer displays the information. 

However, on the detail screen (after clicking on the person), the wrong date is still shown: 

![image](https://user-images.githubusercontent.com/67682506/150159943-8cf32196-e68d-45ae-bb02-bc4f6e967b5f.jpeg)

![image](https://user-images.githubusercontent.com/67682506/150159959-67f98e72-3c70-4498-b9e2-fc904c19ea6a.jpeg)

Either you remove the date there too or you add a some kind of logic which recognizes this and writes the correct date.

**Comment by pucherd** [comment]
Hello @Ein-Tim, this should be fixed in 1.18.0 version

**Comment by Ein-Tim** [comment]
@pucherd 

Ok, I'll check when the version get's released!

**Comment by Ein-Tim** [comment]
Confirm fixed under Android.
Closing.
