### ISSUE TITLE
New user guide is shown after an update

### ISSUE THREAD

**Issue by ThiefMaster** [Digitaler-Impfnachweis/covpass-android#95]
I just got this report from my 70-year-old mother. Recently the app had an auto update and when launching it for the first time after the update, the whole "new user" guide was displayed, even though the app still contained her pass.

I think this is terrible UX especially for older people who are not that tech-savvy. The only message shown should be about new features (and even there it should be made very clear that there are still passes in the app).

**Comment by Ein-Tim** [comment]
Related issue:

- https://github.com/Digitaler-Impfnachweis/covpass-ios/issues/15

**Comment by jleufgen** [comment]
Thank's for pointing this out, we are working on this topic right now.

**Comment by alexcimander** [comment]
Update: The exclusion of the onboarding screens was planned into one of the next sprints - so please bear with us for a few more days and we will exclude them for "updated only" apps! Thank you one more :-)

**Comment by alexcimander** [comment]
Hey everyone,

as you might noticed with the latest release the onboarding screens for updates and the "what is new"  for new installations are still present. Please bear with us - we did not forget it and we are working on it 🚧 🏗️ 

thank you!

**Comment by alexcimander** [comment]
UPDATE: This issue will be solved with the app version 1.16. 1.16 is planned to be released mid-january! 🚧 🏗️

New behavior: Onboarding-Screens will be shown only for fresh installations. The fix will affect the CovPass and CovPassCheck.

Thank you for your patience and happy new year everyone!

**Comment by timokoenig** [comment]
@alexcimander how do you display new data privacy updates and get the consent if the onboarding is not shown?

**Comment by ThiefMaster** [comment]
Consent for what exactly? There's no data transfer, is t here?

**Comment by alexcimander** [comment]
Good Point: We will show data-privacy statements + consent as part of the onboarding and every time they changed👍

**Comment by timokoenig** [comment]
@ThiefMaster there is a download of additional information like signing certificates but no data transfer of the users certificate. But since the certificate is being processed there is a data privacy notice present in CovPass and CovPassCheck. IMO any updates need to be presented to the user but seems like @alexcimander already thought of it

**Comment by pucherd** [comment]
Hello @ThiefMaster, the latest 1.16.1 release will not show the onboarding again.

**Comment by Ein-Tim** [comment]
This should be fixed. Can you close this issue @ThiefMaster?
